import json,tempfile
from pathlib import Path
from conscious_agent.reflective_subject_intake import ReflectiveSubjectIntakeStore
from conscious_agent.model_backed_reflective_session import ModelBackedReflectiveSessionStore
from conscious_agent.reflective_outcome_lineage import ReflectiveOutcomeLineageStore
from conscious_agent.continuous_thought_threads import ContinuousThoughtThreadStore
from conscious_agent.thought_thread_execution_sessions import ThoughtThreadExecutionSessionStore
from conscious_agent.thought_thread_arbitration import ThoughtThreadArbitrationStore
r=Path(tempfile.mkdtemp());sid=ReflectiveSubjectIntakeStore(r).register('s',subject_kind='concern',source_contract='t',source_id='c',importance=.8,uncertainty=.3)['subject_id'];ss=ModelBackedReflectiveSessionStore(r,model_generate=lambda p:'{"outcome":"conclusion","conclusion":"x","uncertainty":0.2,"evidence_refs":["r"],"communication_recommendation":"silence"}').run('m',subject_id=sid);oid=ReflectiveOutcomeLineageStore(r).record('o',session_id=ss['session_id'])['outcome_id'];tid=ContinuousThoughtThreadStore(r).create('t',reflection_outcome_id=oid)['thread_id'];es=ThoughtThreadExecutionSessionStore(r).open('e',thread_id=tid)['session_id'];st=ThoughtThreadArbitrationStore(r);a=st.arbitrate('a',session_id=es,requested_outcome='conclude_thread',conclusion_supported=True);b=st.arbitrate('a',session_id=es);i=st.inspection_summary();c=[a['outcome']=='conclude_thread',b['idempotent'],i['contract_version']=='v1127.4',i['outcome_count']==1,'branch_thread' in i['recognized_outcomes'],'remain_unresolved' in i['recognized_outcomes'],not i['raw_content_exposed'],not i['provider_contacted'],not i['belief_updated'],not i['external_action_executed']];print(json.dumps({'passed':sum(c),'total':10,'suite':'v1127.4'}));raise SystemExit(0 if all(c) else 1)
