import sys,tempfile,shutil;from pathlib import Path
R=Path(__file__).resolve().parents[1];sys.path[:0]=[str(R),str(R/'conscious_agent'),str(R/'tools')]
from self_model_map import build_self_model;from self_improvement_backlog import *;from self_change_isolation import *;from protected_core import *;from dogfood_verification import *;from shadow_execution import *;from canary_self_update import *;from automatic_self_rollback import *;from update_lineage import *;from self_modification_checkpoint import *;from v1390_test_support import *
N=0
with tempfile.TemporaryDirectory() as td:
 r=Path(td);src=fixture(r);baseline=r/'baseline';shutil.copytree(src,baseline);installed=r/'installed';shutil.copytree(src,installed)
 sm=build_self_model(source_root=R)['self_model'];obs=[{'category':'failure','evidence_digest':D('finding'),'scope_digest':D('app.py'),'issue_class':'fixture_repair','impact':5,'confidence':100,'effort':1,'risk':'low','protected_boundary':False}];back=build_self_improvement_backlog(self_model_digest=sm['self_model_digest'],observations=obs)['self_improvement_backlog'];bc=back['candidates'][0]['candidate_id'];cid='selfc_'+bc[:12]
 iso=create_self_change_workspace(source_root=src,runtime_root=r/'runtime',candidate_id=cid,self_model_digest=sm['self_model_digest'],backlog_candidate_digest=bc);(Path(iso['private_workspace']['work_root'])/'app.py').write_text('VERSION="new"\n');scope=classify_self_change_scope(changed_paths=['app.py'])['scope']
 dog=run_dogfood_verification(private_workspace=iso['private_workspace'],expected_lineage_digest=iso['self_change_workspace']['lineage_digest'],protected_scope=scope,expected_scope_digest=scope['scope_digest'],test_paths=['tools/self_test.py'])['dogfood_verification'];req(dog['passed']==1,'dogfood');N+=1
 sha=run_shadow_execution(baseline_root=baseline,private_workspace=iso['private_workspace'],expected_lineage_digest=iso['self_change_workspace']['lineage_digest'],scenario_paths=['shadow/scenario.py'])['shadow_execution'];req(sha['regression_count']==0,'shadow');N+=1
 can=run_canary_self_update(private_workspace=iso['private_workspace'],expected_lineage_digest=iso['self_change_workspace']['lineage_digest'],dogfood_verification=dog,expected_dogfood_digest=dog['verification_digest'],shadow_execution=sha,expected_shadow_digest=sha['shadow_digest'],health_scenarios=['canary/health.py'])['canary_self_update'];req(can['canary_passed'],'canary');N+=1
 txr=execute_self_update_with_auto_rollback(installed_root=installed,candidate_work_root=iso['private_workspace']['work_root'],runtime_root=r/'txruntime',transaction_id='selftx_139013901390',canary_self_update=can,expected_canary_digest=can['canary_digest'],health_scenarios=['health/post.py'],operator_authorized=True);tx=txr['self_update_transaction'];req(txr['ok'] and 'new' in (installed/'app.py').read_text(),'install');N+=1
 lr=record_update_lineage(runtime_root=r/'lineage',candidate_id=cid,source_digest=sm['module_manifest_digest'],finding_digest=D('finding'),repair_digest=D('repair'),test_digest=dog['verification_digest'],canary_digest=can['canary_digest'],transaction_digest=tx['transaction_digest'],active_version='1390.9',outcome='installed')['update_lineage'];q=build_self_modification_checkpoint(self_model=sm,self_model_digest=sm['self_model_digest'],self_improvement_backlog=back,backlog_digest=back['backlog_digest'],self_change_workspace=iso['self_change_workspace'],protected_scope=scope,dogfood_verification=dog,shadow_execution=sha,canary_self_update=can,self_update_transaction=tx,update_lineage=lr);req(q['ok'],'checkpoint');N+=1
print({'ok':N==5,'passed':N,'total':5,'suite':'v1390-integration'})
