from __future__ import annotations

"""Read-only API catalog extracted from ``api_server.py`` in v1250.8."""

from typing import Any

CONTRACT_VERSION = "v1250.8"
AUTHORITY_FLAGS = {
    "approval_granted": False,
    "tool_execution_authorized": False,
    "project_mutation_authorized": False,
    "provider_contact_authorized": False,
    "release_authorized": False,
    "independent_authority_granted": False,
}

def build_api_index(api_version: str) -> dict[str, Any]:
    return {
        "name": "Eidolon Local API",
        "version": api_version,
        "safety": "Local-only by default. API routes call existing safety, approval, and command gates.",
        "endpoints": {
            "GET /api/status": "Overall counts and active project.",
            "GET /api/release-candidate-package-status": "Read-only content-free v1095.8 working-source, frozen-candidate, packaged-archive, installed, promoted, and certified role status; no release mutation or certification claim.",
            "GET /api/release-handoff/status": "Path-suppressed content-free status for the exact operator-selected candidate archive; no scanning, installation, promotion, or certification.",
            "GET /api/release-installation/preview/status": "Read-only content-free installation impact status for one exact coherent handoff and explicitly selected registered target.",
            "POST /api/release-installation/preview/create": "Create an external read-only installation impact preview; no copy, removal, installation, approval, promotion, or certification.",
            "GET /api/release-installation/plan/status": "Read-only content-free exact installation plan status with drift detection.",
            "POST /api/release-installation/plan/create": "Bind the coherent installation preview into an immutable external plan; no token, staging, or apply.",
            "GET /api/release-installation/staging/status": "Read-only content-free status for exact external staging; never implies installation.",
            "POST /api/release-installation/staging/authorization-preview": "Create an exact plan-bound staging authorization token and literal confirmation requirement.",
            "POST /api/release-installation/staging/create": "Create an externally verified candidate mirror and backup/rollback plans; target remains unmodified.",
            "GET /api/release-installation/transaction/status": "Content-free exact installation transaction status; never implies promotion or certification.",
            "POST /api/release-installation/transaction/authorization-preview": "Create a single-use exact staged-plan apply token and literal confirmation requirement.",
            "POST /api/release-installation/transaction/apply": "Apply one exact staged installation transactionally after literal confirmation; backups and evidence remain external.",
            "GET /api/release-installation/recovery/status": "Content-free interrupted-installation and rollback reconciliation status.",
            "POST /api/release-installation/recovery/resume-preview": "Preview exact resumption of one interrupted installation transaction.",
            "POST /api/release-installation/recovery/resume": "Resume one exact interrupted installation after literal confirmation.",
            "POST /api/release-installation/recovery/rollback-preview": "Preview exact rollback effects for one transaction.",
            "POST /api/release-installation/recovery/rollback": "Roll back one exact transaction after literal confirmation without overwriting external edits.",
            "GET /api/release-installation/installed-state/status": "Content-free installed-state reconciliation across staged, applying, interrupted, uncertain, rollback-ready, rolled-back, installed-unpromoted, promoted, and certified states.",
            "GET /api/release-promotion/preview/status": "Read-only content-free promotion-impact preview status bound to exact installed-unpromoted evidence.",
            "POST /api/release-promotion/preview/create": "Create a metadata-only promotion-impact preview; no source mutation, promotion apply, or certification.",
            "GET /api/release-promotion/plan/status": "Read-only content-free immutable promotion-plan status with drift detection.",
            "POST /api/release-promotion/plan/create": "Bind one coherent promotion preview into an immutable external plan.",
            "POST /api/release-promotion/authorization-preview": "Create an exact plan-bound promotion authorization token; no promotion apply or certification.",
            "GET /api/release-promotion/status": "Content-free transactional promotion and reversal status; never claims certification.",
            "GET /api/release-certification/readiness/status": "Content-free certification evidence readiness status with scope separation and no certification claim.",
            "POST /api/release-certification/evidence/select": "Inspect one exact operator-selected external evidence artifact; no directory scanning or certification.",
            "POST /api/release-certification/readiness/create": "Create a read-only scope-specific certification readiness preview; no native or provider checks are inferred.",
            "GET /api/release-certification/plan/status": "Content-free immutable certification plan status with exact evidence and authority drift detection.",
            "POST /api/release-certification/plan/create": "Freeze a coherent readiness preview into one exact scope-specific certification decision plan.",
            "POST /api/release-certification/authorization-preview": "Create one exact single-use certification decision authorization token; no decision is applied.",
            "GET /api/release-certification/status": "Content-free scope-aware certification authority and decision status.",
            "POST /api/release-certification/decision/apply": "Record one exact authorized certification, decline, or insufficient-evidence decision.",
            "POST /api/release-certification/revocation-preview": "Preview exact scope revocation bound to the current certification generation and receipt.",
            "POST /api/release-certification/revoke": "Revoke one exact certified scope after literal confirmation without deleting history.",
            "GET /api/release-certification/recovery/status": "Content-free exact interrupted certification decision recovery status.",
            "POST /api/release-certification/recovery/preview": "Preview exact interrupted certification recovery; no decision replay or provider contact.",
            "POST /api/release-certification/recovery/resume": "Resume one exact interrupted certification decision after literal confirmation.",
            "GET /api/release-certification/evidence/freshness": "Content-free evidence freshness, expiry, replacement, and withdrawal status.",
            "POST /api/release-certification/evidence/replacement-preview": "Preview replacement using one explicitly selected evidence artifact.",
            "POST /api/release-certification/evidence/replace": "Activate one exact replacement evidence artifact after literal confirmation.",
            "GET /api/release-certification/recertification/status": "Read-only recertification readiness status; no automatic decision.",
            "POST /api/release-certification/recertification/create": "Create a read-only scope-specific recertification preview.",
            "GET /api/release-certification/coherence/status": "Bounded content-free certification daily-use and authority coherence status.",
            "GET /api/release-certification/history/status": "Content-free read-only certification authority-history reconciliation status.",
            "POST /api/release-certification/history/create": "Create an exact read-only certification authority-history reconciliation preview.",
            "GET /api/release-certification/policy/status": "Content-free explicitly selected certification policy status.",
            "POST /api/release-certification/policy/select": "Select one exact external certification policy artifact or exact built-in policy identity.",
            "GET /api/release-certification/policy/migration/status": "Content-free certification policy migration-impact preview status.",
            "POST /api/release-certification/policy/migration/create": "Create a read-only exact policy migration-impact preview.",
            "POST /api/release-certification/policy/migration/acknowledge": "Acknowledge one exact migration preview without applying policy migration.",
            "GET /api/release-certification/authority/status": "Consolidated content-free certification history, policy, freshness, recovery, and scope authority status.",
            "GET /api/release-authority/readiness/status": "Content-free certification-to-release authority readiness status with exact scope separation.",
            "POST /api/release-authority/readiness/create": "Create one external read-only exact release-authority readiness preview; grants no authority.",
            "GET /api/release-authority/readiness/refresh/status": "Content-free exact readiness refresh and interruption-recovery status.",
            "POST /api/release-authority/readiness/refresh": "Refresh the exact active readiness snapshot; grants no authority.",
            "POST /api/release-authority/readiness/recovery-preview": "Preview exact recovery of one interrupted readiness refresh.",
            "POST /api/release-authority/readiness/recover": "Resume one exact interrupted readiness refresh after literal confirmation.",
            "POST /api/release-authority/readiness/replacement-preview": "Preview explicit replacement using one exact existing readiness snapshot.",
            "POST /api/release-authority/readiness/replace": "Replace the active readiness snapshot after exact literal confirmation.",
            "POST /api/release-authority/readiness/cleanup-preview": "Preview cleanup of exact abandoned readiness artifacts below the external runtime root.",
            "POST /api/release-authority/readiness/cleanup": "Remove exact preview-bound abandoned readiness artifacts after literal confirmation.",
            "GET /api/release-authority/handoff-plan/status": "Content-free immutable release-authority handoff-plan status with drift detection.",
            "POST /api/release-authority/handoff-plan/create": "Bind one coherent readiness snapshot into an external read-only handoff plan.",
            "GET /api/release-authority/handoff-plan/acknowledgment/status": "Content-free exact handoff acknowledgment, expiry, and interruption status.",
            "POST /api/release-authority/handoff-plan/acknowledgment-preview": "Preview exact single-use handoff-plan acknowledgment.",
            "POST /api/release-authority/handoff-plan/acknowledge": "Acknowledge one exact handoff plan after literal confirmation; grants no authority.",
            "GET /api/release-authority/handoff-plan/acknowledgment/recovery/status": "Content-free acknowledgment recovery, replacement, and cleanup readiness status.",
            "POST /api/release-authority/handoff-plan/acknowledgment/recovery-preview": "Preview exact recovery of one interrupted handoff acknowledgment.",
            "POST /api/release-authority/handoff-plan/acknowledgment/recover": "Resume one exact interrupted handoff acknowledgment after literal confirmation.",
            "POST /api/release-authority/handoff-plan/acknowledgment/replacement-preview": "Preview exact replacement of one expired or stale handoff acknowledgment.",
            "POST /api/release-authority/handoff-plan/acknowledgment/replace": "Replace one exact expired or stale handoff acknowledgment after literal confirmation.",
            "POST /api/release-authority/handoff-plan/acknowledgment/cleanup-preview": "Preview cleanup of exact abandoned acknowledgment artifacts below the external runtime root.",
            "POST /api/release-authority/handoff-plan/acknowledgment/cleanup": "Remove exact preview-bound abandoned acknowledgment artifacts after literal confirmation.",
            "GET /api/release-authority/consumer/receipt/status": "Content-free status for one explicitly named consumer receipt; never scans or infers a consumer.",
            "GET /api/release-authority/consumer/lifecycle/status": "Content-free lifecycle status for one explicitly named consumer receipt.",
            "GET /api/release-authority/handoff-lifecycle/status": "Bounded content-free handoff lifecycle consolidation status.",
            "POST /api/release-authority/consumer/receipt/recovery-preview": "Preview exact interrupted consumer receipt recovery.",
            "POST /api/release-authority/consumer/receipt/recover": "Recover one exact interrupted consumer receipt operation.",
            "POST /api/release-authority/consumer/receipt/retirement-preview": "Create one non-destructive exact retirement preview.",
            "POST /api/release-authority/consumer/supersession-preview": "Preview one exact predecessor-successor consumer handoff binding.",
            "POST /api/release-authority/consumer/supersession/create": "Create one immutable authority-free supersession record.",
            "POST /api/release-authority/consumer/validation-preview": "Preview exact read-only validation for one explicitly named downstream consumer.",
            "POST /api/release-authority/consumer/receipt/create": "Create one immutable authority-free consumer receipt after exact literal acknowledgment.",
            "GET /api/release-authority/daily-use/status": "Bounded content-free release-authority refresh, handoff, acknowledgment, consumer, scope, history, policy, and multi-tab status.",
            "POST /api/release-certification/operation/claim-preview": "Preview exact multi-tab certification operation ownership.",
            "POST /api/release-certification/operation/claim": "Claim exact certification operation ownership after literal confirmation.",
            "POST /api/release-certification/operation/release": "Release exact certification operation ownership after literal confirmation.",
            "POST /api/release-promotion/apply": "Apply one exact authorized promotion transactionally after literal confirmation.",
            "POST /api/release-promotion/resume-preview": "Preview exact resumption of an interrupted promotion transaction.",
            "POST /api/release-promotion/resume": "Resume one exact interrupted promotion after literal confirmation.",
            "POST /api/release-promotion/reversal-preview": "Preview exact reversal of promoted-uncertified authority state.",
            "POST /api/release-promotion/reverse": "Reverse exact promotion after literal confirmation when no certification exists.",
            "POST /api/release-handoff/inspect": "Inspect one exact operator-supplied external candidate archive path into an external runtime root; preview-only and does not modify project registries or installed source.",
            "POST /api/release-handoff/recovery/preview": "Preview recovery of the exact active handoff binding; never scans for replacement archives.",
            "POST /api/release-handoff/recovery/apply": "Apply one exact generation-bound recovery preview after literal confirmation.",
            "POST /api/release-handoff/replacement/preview": "Inspect one explicitly selected replacement archive while preserving the active handoff.",
            "POST /api/release-handoff/replacement/apply": "Activate one exact generation-bound replacement preview after literal confirmation.",
            "POST /api/release-handoff/cleanup/preview": "Preview cleanup only for abandoned artifacts beneath the exact external handoff runtime root.",
            "POST /api/release-handoff/cleanup/apply": "Remove exact preview-bound abandoned handoff artifacts after the literal cleanup phrase.",
            "GET /api/conversation/daily-use-stability-checkpoint": "Read-only content-free v1082.9 daily-use runtime contract summary; does not run generation or certify a release.",
            "GET /api/conversation/relationship-continuity-checkpoint": "Read-only content-free v1083.9 relationship continuity summary; does not invoke providers, mutate memories, or certify a release.",
            "GET /api/conversation/conversation-quality-checkpoint": "Read-only content-free v1084.9 conversation quality summary; does not invoke providers, rewrite history, mutate personality, or certify a release.",
            "GET /api/conversation/context-inspection": "Read-only content-free v1085.8 context lane, ranking, budget, correction, cross-session, and stale-summary evidence; does not invoke providers or reveal prompt content.",
            "GET /api/conversation/context-intelligence-checkpoint": "Read-only content-free v1085.9 context intelligence summary; does not invoke providers, merge sessions, rewrite history, or certify a release.",
            "GET /api/conversation/control-foundation": "Read-only content-free v1086.0 conversation-control contract; persisted changes require explicit session-local POST actions.",
            "GET /api/conversation/offline-degradation": "Read-only content-free v1086.7 local-surface and queued-intent state; never replays or executes a provider request automatically.",
            "GET /api/conversation/long-session-hardening": "Read-only content-free v1086.8 bounded history, draft, controls, offline, and UX hardening evidence.",
            "GET /api/conversation/readiness-checkpoint": "Read-only content-free v1086.9 conversation-readiness evidence.",
            "GET /api/conversation/daily-evaluation-protocol": "Read-only content-free v1087.0 operator-guided daily-evaluation protocol.",
            "GET /api/conversation/daily-evaluation": "Read-only redacted v1087.1 daily-evaluation summary by evaluation_id.",
            "GET /api/conversation/evaluation-reproduction": "Read-only content-free v1087.3 reproduction packet by evaluation_id.",
            "GET /api/conversation/evaluation-trends": "Read-only content-free v1087.4 bounded longitudinal evaluation trends.",
            "GET /api/conversation/restart-outage-evaluation": "Read-only provider-free v1087.5 restart and outage coverage by evaluation_id.",
            "GET /api/conversation/long-session-evaluation": "Read-only content-free v1087.6 long-session daily-use coverage by evaluation_id.",
            "GET /api/conversation/evaluation-console": "Read-only provider-free v1087.7 evaluation console state.",
            "GET /api/conversation/evaluation-review-export": "Read-only privacy-safe v1087.8 review export packet by evaluation_id.",
            "GET /api/conversation/daily-evaluation-checkpoint": "Read-only provider-free v1087.9 Desktop Alpha daily-evaluation checkpoint with bounded states, counts, limits, reason codes, and digests only.",
            "GET /api/conversation/evaluation-campaign-protocol": "Read-only provider-free v1088.0 operator evaluation campaign protocol.",
            "GET /api/conversation/evaluation-campaign": "Read-only redacted v1088.1 operator evaluation campaign summary by campaign_id.",
            "GET /api/conversation/evaluation-campaign-progress": "Read-only content-free v1088.2 campaign enrollment and progress evidence by campaign_id.",
            "GET /api/conversation/evaluation-campaign-issues": "Read-only content-free v1088.3 campaign issue aggregation by campaign_id; no autonomous prioritization or task creation.",
            "GET /api/conversation/evaluation-campaign-follow-ups": "Read-only redacted v1088.4 explicit campaign follow-up references by campaign_id.",
            "GET /api/conversation/evaluation-campaign-comparison": "Read-only content-free v1088.5 bounded comparison for two to eight campaign_id values; no ranking or release advice.",
            "GET /api/conversation/evaluation-campaign-review": "Read-only redacted v1088.6 explicit campaign review and disposition evidence by campaign_id.",
            "GET /api/conversation/evaluation-campaign-console": "Read-only provider-free v1088.7 operator campaign console state.",
            "GET /api/conversation/evaluation-campaign-review-export": "Read-only deterministic v1088.8 privacy-safe campaign review export by campaign_id.",
            "GET /api/conversation/evaluation-campaign-checkpoint": "Read-only provider-free v1088.9 operator evaluation campaign checkpoint with bounded states, counts, limits, reason codes, and digests only.",
            "GET /api/conversation/evaluation-finding": "Read-only redacted v1089.0 evaluation finding summary or bounded finding list.",
            "GET /api/conversation/evaluation-finding-reproducibility": "Read-only redacted v1089.1 explicit reproducibility evidence by finding_id.",
            "GET /api/conversation/evaluation-finding-repair-candidates": "Read-only redacted v1089.2 repair-candidate references by finding_id.",
            "GET /api/conversation/evaluation-finding-aggregation": "Read-only content-free v1089.3 bounded finding aggregation; no ranking, priority, or task creation.",
            "GET /api/conversation/evaluation-finding-triage": "Read-only redacted v1089.4 explicit finding triage and disposition evidence by finding_id.",
            "GET /api/conversation/evaluation-finding-comparison": "Read-only content-free v1089.5 comparison of two to eight finding_id values; no ranking or release advice.",
            "GET /api/conversation/evaluation-finding-console": "Read-only provider-free v1089.6 operator findings console state.",
            "GET /api/conversation/evaluation-finding-review-export": "Read-only deterministic v1089.7 privacy-safe repair-intake review export by finding_id.",
            "GET /api/conversation/evaluation-finding-window": "Read-only content-free v1089.8 bounded long-session finding window with 80 initial and 120 earlier rows.",
            "GET /api/conversation/evaluation-findings-checkpoint": "Read-only provider-free v1089.9 evaluation findings and repair-intake checkpoint.",
            "GET /api/conversation/repair-candidate-review-protocol": "Read-only provider-free v1090.0 repair-candidate review protocol.",
            "GET /api/conversation/repair-candidate-registrations": "Read-only redacted v1090.1 immutable candidate registrations by finding_id.",
            "GET /api/conversation/repair-candidate-review": "Read-only redacted v1090.2 explicit candidate review evidence by finding_id and candidate_id.",
            "GET /api/conversation/repair-candidate-verification-evidence": "Read-only redacted v1090.3 candidate verification evidence by finding_id and candidate_id.",
            "GET /api/conversation/repair-candidate-comparison": "Read-only bounded v1090.4 descriptive candidate comparison by finding_id and repeated candidate_id values.",
            "GET /api/conversation/repair-candidate-lineage": "Read-only redacted v1090.5 immutable supersession and replacement lineage by finding_id.",
            "GET /api/conversation/repair-candidate-console": "Read-only provider-free v1090.6 operator candidate-review console state.",
            "GET /api/conversation/repair-candidate-review-export": "Read-only deterministic v1090.7 privacy-safe candidate review export by finding_id and candidate_id.",
            "GET /api/conversation/repair-candidate-window": "Read-only content-free v1090.8 bounded long-session candidate window with 80 initial and 120 earlier rows.",
            "GET /api/conversation/repair-candidate-review-checkpoint": "Read-only provider-free v1090.9 repair-candidate review checkpoint with bounded states, counts, limits, reason codes, and digests only.",
            "GET /api/product-reality-benchmark": "Read-only content-free v1100.0 product-reality benchmark and exact 50-release roadmap.",
            "POST /api/conversation/evaluation-finding": "Explicit operator-confirmed v1089.0-v1090.2 finding intake, reproducibility, repair-reference, triage, candidate registration, and candidate review mutations.",
            "POST /api/conversation/evaluation-campaign": "Explicit operator-confirmed v1088.1-v1088.6 campaign planning, activation, enrollment, follow-up, review, completion, or abort mutation.",
            "GET /api/conversation/readiness-checkpoint": "Read-only provider-free v1086.9 Desktop Alpha conversation-readiness evidence with counts, states, limits, reason codes, and digests only.",
            "GET /api/conversation/turn-action-plan": "Read-only v1086.4 classification of failed retry, completed regeneration, and explicit resend for one persisted turn.",
            "POST /api/conversation/steer": "Explicit v1086.3 cancellation-first steering request; redirect text is not submitted automatically and requires a fresh acceptance identity.",
            "POST /api/conversation/turn-action": "Explicit v1086.4 failed retry, completed-response regeneration, or user-message resend with preserved lineage.",
            "POST /api/conversation/message-branch": "Explicit v1086.5 edit-by-branch action preserving the original transcript and saving the edited message as an unsent draft.",
            "GET /api/local-model/status": "Provider-neutral local-model health, model availability, and generation configuration.",
            "GET /api/local-model/readiness": "Bounded generation/embedding service readiness, capabilities, failure classification, and operator guidance without generation.",
            "GET /api/local-model/configuration": "Current validated local-model editor values and effective endpoint fallback; no secrets or model management.",
            "POST /api/local-model/configuration": "Validate and save the bounded local-model editor settings.",
            "POST /api/local-model/readiness": "Run bounded readiness for current or supplied unsaved editor values and return a redacted availability/recovery state without switching providers.",
            "POST /api/local-model/native-smoke": "Run explicitly confirmed bounded native health, generation, streaming, and embedding checks.",
            "POST /api/local-model/native-conversation-validation": "Run explicitly confirmed provider-neutral conversational fixtures and return redacted evidence only.",
            "GET /api/stabilization-checkpoint": "Run the v8.0 read-only stabilization checkpoint. Supports ?full=true.",
            "GET /api/doctor": "Run the v7.2/v8.0 one-command doctor report. Supports ?full=true.",
            "GET /api/repair-suggestions": "Return v7.3 self-repair suggestions.",
            "GET /api/patch-integrity": "Return v7.4 patch metadata and rollback integrity report.",
            "GET /api/project-snapshot": "Return v7.5 project state snapshot.",
            "GET /api/tasks/review": "Return v7.6 task queue lifecycle/risk review.",
            "GET /api/recovery-drill": "Run v7.7 read-only recovery drill scenarios.",
            "GET /api/stable-loops/confidence": "Return v7.8 stable-loop confidence score.",
            "GET /api/hardening-report": "Return v7.9 pre-v8 hardening report.",
            "GET /api/controlled-self-build": "Run v8.0 controlled self-build preview only. Live work is POST-only.",
            "GET /api/controlled-self-build/lightweight-preview": "Return a lightweight preview-only controlled self-build diagnostic summary without running the heavy preview.",
            "GET /api/doctor/diagnostic-preview-cache": "Return a bounded preview-only cache of /doctor deferred diagnostic rows without live diagnostic fan-out.",
            "GET /api/doctor/diagnostic-preview-cache/freshness": "Return preview-only freshness and invalidation metadata for the doctor diagnostic preview cache.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/digest-verification": "Return dry-run source dependency digest verification for the doctor diagnostic preview cache freshness fingerprint.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/digest-drift-classification": "Return dry-run digest drift cause classifications for the doctor diagnostic preview cache freshness fingerprint.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/contract-drift-fixtures": "Return dry-run contract-affecting drift fixtures for token removal and route rename simulation.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/drift-severity-guidance": "Return preview-only operator severity guidance for dry-run doctor cache drift fixtures.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/severity-route-impact-matrix": "Return preview-only dashboard/API/smoke route impact guidance for severity-labeled doctor cache drift.",
            "GET /api/doctor/diagnostic-preview-cache/freshness/impact-operator-action-ledger": "Return preview-only operator action ledger guidance for doctor cache impact matrix rows.",
            "GET /api/doctor/headroom": "Return the v1052 bounded /doctor dashboard headroom snapshot without live diagnostic fan-out.",
            "GET /api/install-release/historical-blocker-reduction": "Return the v1057 install-release historical blocker reduction preview; full registry inspection is default and read-only.",
            "GET /api/source-surface/dispatch-candidate-preparation": "Return the v1058 source surface manifest dispatch candidate preparation preview; generated dispatch remains inactive.",
            "GET /api/dashboard/slow-route-cohort-repair": "Return the v1056 slow dashboard route cohort repair metadata; full route measurement is opt-in with measure=true.",
            "GET /api/dashboard/shell-performance-stabilization": "Return the v1065.10 dashboard shell performance stabilization metadata; measured render checks are opt-in with measure=true.",
            "GET /api/dashboard/full-navigation-get-side-effect-safety-gate": "Return the v1065.11 full navigation GET side-effect safety metadata; bounded dynamic checks are opt-in with measure=true.",
            "GET /api/install-release/segment-runner-timeout-decomposition": "Return the v1065.12 install-release segment runner timeout decomposition metadata.",
            "GET /api/source-surface/manifest-fixture-receipt-consolidation": "Return the v1066.0 manifest fixture receipt consolidation metadata; actual generated fixture execution remains blocked without an audited OS sandbox.",
            "GET /api/source-surface/audited-sandbox-backend-preflight-contract": "Return the 1066.1 Audited Sandbox Backend Preflight Contract v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/sandbox-backend-capability-evidence-gate": "Return the 1066.2 Sandbox Backend Capability Evidence Gate v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/fixture-execution-admission-gate": "Return the 1066.3 Fixture Execution Admission Gate v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/sandboxed-fixture-execution-trial": "Return the 1066.4 First Sandboxed Fixture Execution Trial v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/sandboxed-fixture-batch-execution": "Return the 1066.5 Sandboxed Fixture Batch Execution v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/generated-dispatch-promotion-readiness-ledger": "Return the 1067.0 Generated Dispatch Promotion Readiness Ledger v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/source-decomposition-batch-i": "Return the 1068.0 Source Decomposition Batch I v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/autonomy-phase-zero-observation-contract": "Return the 1069.0 Autonomy Phase 0 Observation-Only Contract v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/source-decomposition-batch-ii": "Return the 1069.1 Source Decomposition Batch II and Sandbox Backend Adapter Integration Plan v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/dashboard-api-smoke-shared-utility-adoption": "Return the 1070.0 Dashboard API Smoke Shared Utility Adoption and Sandbox Adapter Skeleton v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/dashboard-review-component-extraction-pilot": "Return the 1070.1 Dashboard Review Component Extraction Pilot v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/smoke-check-helper-extraction-pilot": "Return the 1070.2 Smoke Check Helper Extraction Pilot v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/api-preview-adapter-extraction-pilot": "Return the 1070.3 API Preview Adapter Extraction Pilot v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/api-preview-adapter-backfill": "Return the 1070.4 Dashboard API Preview Adapter Backfill v1 metadata; GET is preview-only and no fixture execution, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/api-server-dispatch-route-table-backfill": "Return the 1070.8 API Server Dispatch Route Table Backfill v1 metadata; GET is preview-only and no fixture execution, subprocesses, writes, deletes, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/source-surface/api-server-dispatch-route-table-safety-parity": "Return the 1070.9 API Server Dispatch Route Table Safety Parity v1 metadata; GET is preview-only and no fixture execution, subprocesses, writes, deletes, generated wiring, release authorization, or autonomy expansion occurs.",
            "GET /api/installed-tree-cleanup/historical-verification-reconciliation": "Return the v1053 installed-tree cleanup and historical verification reconciliation report; startup measurement is opt-in with measure_startup=true.",
            "GET /api/installed-tree-cleanup/enforcement": "Return the v1065.10 installed-tree cleanup enforcement preview; deletion is POST/confirmation-gated and generated wiring remains inactive.",
            "POST /api/controlled-self-build": "Run controlled self-build; live mode requires approve=true and confirm=LIVE_CONTROLLED_BUILD.",
            "GET /api/controlled-build/select-task": "Run v8.1 controlled task selection.",
            "GET /api/controlled-build/plan-patch": "Preview v8.2 patch planner without saving workspace state.",
            "POST /api/controlled-build/plan-patch": "Run v8.2 patch planner and save workspace plan.",
            "GET /api/controlled-build/workspace": "Show v8.3 patch workspace status.",
            "GET /api/controlled-build/stage-patch": "Preview v8.3 patch staging without saving workspace state.",
            "POST /api/controlled-build/stage-patch": "Run v8.3 patch staging into data/patch_workspace.",
            "GET /api/controlled-build/preview-diff": "Preview v8.4 staged diff without saving validation state.",
            "POST /api/controlled-build/preview-diff": "Run v8.4 staged diff preview and save validation state.",
            "POST /api/controlled-build/apply-staged-patch": "Run v8.5 staged patch apply; writes only when approve=true.",
            "POST /api/controlled-build/verify-latest-patch": "Run v8.6 verification for the latest real controlled patch.",
            "POST /api/controlled-build/rollback-latest-patch": "Run v8.7 rollback; writes only when approve=true and hashes still match.",
            "GET /api/controlled-build/readme-gate": "Run v8.8 README enforcement gate.",
            "POST /api/controlled-build/cycle": "Run v8.9 full controlled build cycle; live mode requires confirmation.",
            "POST /api/supervised-dev-loop": "Run v9.0 one-cycle supervised autonomous development loop; live mode requires confirmation.",
            "GET /api/codebase-map": "Run v9.1 codebase map.",
            "GET /api/patch-context/goal": "Run v71.1 patch goal intake classifier.",
            "GET /api/patch-context/files": "Run v71.2 relevant file context selector.",
            "GET /api/patch-context/failures": "Run v71.3 historical failure context binder.",
            "GET /api/patch-context/budget": "Run v71.4 risk-aware context budgeter.",
            "GET /api/patch-context/verification": "Run v71.5 verification requirement compiler.",
            "GET /api/patch-context/packet": "Run v71.6 patch prompt context packet builder.",
            "GET /api/patch-context/review": "Run v71.7 context completeness reviewer.",
            "GET /api/patch-context/parity": "Run v71.8 patch context dashboard/API/CLI parity.",
            "GET /api/patch-context/gate": "Run v71.9 pre-v72 patch context gate.",
            "GET /api/patch-context/layer": "Run v72.0 patch generation context builder.",
            "GET /api/patch-drafts/intake": "Run v72.1 patch intent normalizer.",
            "GET /api/patch-drafts/scope": "Run v72.2 patch scope contract builder.",
            "GET /api/patch-drafts/prompt": "Run v72.3 patch prompt composer.",
            "GET /api/patch-drafts/schema": "Run v72.4 patch draft output schema.",
            "GET /api/patch-drafts/safety": "Run v72.5 patch draft safety reviewer.",
            "GET /api/patch-drafts/evidence": "Run v72.6 patch draft evidence binder.",
            "GET /api/patch-drafts/parity": "Run v72.7 patch draft dashboard/API/CLI parity.",
            "GET /api/patch-drafts/handoff": "Run v72.8 local model handoff stub.",
            "GET /api/patch-drafts/gate": "Run v72.9 pre-v73 patch draft gate.",
            "GET /api/patch-drafts/layer": "Run v73.0 supervised patch draft composer.",
            "GET /api/patch-review/intake": "Run v73.1 patch draft intake parser.",
            "GET /api/patch-review/diff-boundary": "Run v73.2 diff boundary extractor.",
            "GET /api/patch-review/scope": "Run v73.3 scope contract validator.",
            "GET /api/patch-review/safety": "Run v73.4 safety boundary validator.",
            "GET /api/patch-review/docs": "Run v73.5 documentation update validator.",
            "GET /api/patch-review/verification": "Run v73.6 verification plan validator.",
            "GET /api/patch-review/risk": "Run v73.7 patch risk scorer.",
            "GET /api/patch-review/report": "Run v73.8 patch review report builder.",
            "GET /api/patch-review/parity": "Run v73.9 patch review dashboard/API/CLI parity.",
            "GET /api/patch-review/gate": "Run v73.9 pre-v74 patch review gate.",
            "GET /api/patch-review/layer": "Run v74.0 patch draft review and diff validation layer.",
            "GET /api/patch-trials/intake": "Run v74.1 sandbox trial intake binder.",
            "GET /api/patch-trials/workspace": "Run v74.2 disposable workspace builder.",
            "GET /api/patch-trials/materialize": "Run v74.3 patch draft materializer.",
            "GET /api/patch-trials/verify": "Run v74.4 sandbox verification runner.",
            "GET /api/patch-trials/evidence": "Run v74.5 sandbox evidence collector.",
            "GET /api/patch-trials/escape-guard": "Run v74.6 sandbox escape/mutation guard.",
            "GET /api/patch-trials/parity": "Run v74.7 patch trial dashboard/API/CLI parity.",
            "GET /api/patch-trials/cleanup": "Run v74.8 patch trial cleanup retention policy.",
            "GET /api/patch-trials/list": "List retained v75 patch trials.",
            "GET /api/patch-trials/gate": "Run v74.9 pre-v75 sandbox trial gate.",
            "GET /api/patch-trials/layer": "Run v75.0 sandbox patch trial runner.",
            "GET /api/patch-evidence/intake": "Run v75.1 sandbox evidence intake reader.",
            "GET /api/patch-evidence/integrity": "Run v75.2 trial integrity validator.",
            "GET /api/patch-evidence/verification": "Run v75.3 verification evidence scorer.",
            "GET /api/patch-evidence/scope-docs": "Run v75.4 scope and documentation evidence reviewer.",
            "GET /api/patch-evidence/risk": "Run v75.5 risk acceptance classifier.",
            "GET /api/patch-evidence/readiness": "Run v75.6 promotion readiness packet builder.",
            "GET /api/patch-evidence/parity": "Run v75.7 patch evidence dashboard/API/CLI parity.",
            "GET /api/patch-evidence/archive": "Run v75.8 recommendation archive and comparison.",
            "GET /api/patch-evidence/gate": "Run v75.9 pre-v76 evidence review gate.",
            "GET /api/patch-evidence/layer": "Run v76.0 sandbox evidence review recommendation layer.",
            "GET /api/patch-apply/approval": "Run v76.1 approval intake contract in dry-run mode.",
            "GET /api/patch-apply/bind": "Run v76.2 recommendation-to-approval binder in dry-run mode.",
            "GET /api/patch-apply/snapshot": "Run v76.3 live source snapshot builder preview.",
            "GET /api/patch-apply/apply": "Run v76.4 approved patch materializer in API dry-run mode only.",
            "GET /api/patch-apply/verify": "Run v76.5 post-apply verification runner.",
            "GET /api/patch-apply/rollback": "Run v76.6 automatic rollback executor dry-run.",
            "GET /api/patch-apply/evidence": "Run v76.7 application evidence recorder in dry-run mode.",
            "GET /api/patch-apply/parity": "Run v76.8 patch application dashboard/API/CLI parity.",
            "GET /api/patch-apply/gate": "Run v76.9 pre-v77 application gate.",
            "GET /api/patch-apply/layer": "Run v77.0 operator-approved patch application layer in dry-run mode unless CLI invokes live.",
            "GET /api/patch-recovery/preflight": "Run v77.1 dirty tree preflight detector.",
            "GET /api/patch-recovery/snapshot": "Run v77.2 snapshot completeness validator.",
            "GET /api/patch-recovery/partial-apply": "Run v77.3 partial apply detector.",
            "GET /api/patch-recovery/rollback-integrity": "Run v77.4 rollback integrity verifier.",
            "GET /api/patch-recovery/triage": "Run v77.5 failed verification triage.",
            "GET /api/patch-recovery/recommendation": "Run v77.6 recovery recommendation builder.",
            "GET /api/patch-recovery/timeline": "Run v77.7 application audit timeline.",
            "GET /api/patch-recovery/parity": "Run v77.8 patch recovery dashboard/API/CLI parity.",
            "GET /api/patch-recovery/gate": "Run v77.9 pre-v78 recovery gate.",
            "GET /api/patch-recovery/layer": "Run v78.0 verified application recovery and rollback hardening layer.",
            "GET /api/patch-queue/schema": "Run v78.1 patch queue record schema.",
            "GET /api/patch-queue/intake": "Run v78.2 patch queue intake organizer.",
            "GET /api/patch-queue/conflicts": "Run v78.3 patch queue conflict detector.",
            "GET /api/patch-queue/priority": "Run v78.4 patch queue risk priority scheduler.",
            "GET /api/patch-queue/stale-evidence": "Run v78.5 patch queue stale evidence detector.",
            "GET /api/patch-queue/serial-plan": "Run v78.6 patch queue serial trial plan builder.",
            "GET /api/patch-queue/review-packet": "Run v78.7 patch queue operator review packet.",
            "GET /api/patch-queue/parity": "Run v78.8 patch queue dashboard/API/CLI parity.",
            "GET /api/patch-queue/gate": "Run v78.9 pre-v79 queue gate.",
            "GET /api/patch-queue/layer": "Run v79.0 multi-patch queue planning layer.",
            "GET /api/improvement-loop/intake": "Run v79.1 Improvement Opportunity Intake.",
            "GET /api/improvement-loop/state": "Run v79.2 Improvement Cycle State Machine.",
            "GET /api/improvement-loop/binder": "Run v79.3 Pipeline Stage Binder.",
            "GET /api/improvement-loop/model-stub": "Run v79.4 Local Model Invocation Stub.",
            "GET /api/improvement-loop/evidence": "Run v79.5 Improvement Loop Evidence Recorder.",
            "GET /api/improvement-loop/stop-gate": "Run v79.6 Operator Stop Gate.",
            "GET /api/improvement-loop/parity": "Run v79.7 Improvement Loop Dashboard/API/CLI.",
            "GET /api/improvement-loop/safety": "Run v79.8 Loop Safety Auditor.",
            "GET /api/improvement-loop/gate": "Run v79.9 Pre-v80 Supervised Loop Gate.",
            "GET /api/improvement-loop/layer": "Run v80.0 Supervised Local Improvement Loop.",
            "GET /api/local-model-proposals/adapter": "Run v80.1 Local Model Adapter Contract.",
            "GET /api/local-model-proposals/profile": "Run v80.2 Model Capability Profile.",
            "GET /api/local-model-proposals/prompt-export": "Run v80.3 Prompt Export and Invocation Guard.",
            "GET /api/local-model-proposals/capture": "Run v80.4 Proposal Capture Parser.",
            "GET /api/local-model-proposals/safety": "Run v80.5 Proposal Safety Precheck.",
            "GET /api/local-model-proposals/provenance": "Run v80.6 Model Output Provenance Recorder.",
            "GET /api/local-model-proposals/parity": "Run v80.7 Proposal Integration Dashboard/API/CLI.",
            "GET /api/local-model-proposals/disabled-gate": "Run v80.8 Disabled-by-Default Invocation Gate.",
            "GET /api/local-model-proposals/gate": "Run v80.9 Pre-v81 Model Integration Gate.",
            "GET /api/local-model-proposals/layer": "Run v81.0 Local Model Patch Proposal Integration.",
            "GET /api/proposal-critique/intake": "Run v81.1 Proposal Collection Intake.",
            "GET /api/proposal-critique/diff-normalize": "Run v81.2 Candidate Diff Normalizer.",
            "GET /api/proposal-critique/quality": "Run v81.3 Proposal Quality Heuristic Scorer.",
            "GET /api/proposal-critique/safety-scope": "Run v81.4 Safety and Scope Comparison.",
            "GET /api/proposal-critique/verification": "Run v81.5 Verification Plan Comparison.",
            "GET /api/proposal-critique/report": "Run v81.6 Critique Report Builder.",
            "GET /api/proposal-critique/parity": "Run v81.7 Critique Dashboard/API/CLI.",
            "GET /api/proposal-critique/operator-bundle": "Run v81.8 Operator Review Bundle Exporter.",
            "GET /api/proposal-critique/gate": "Run v81.9 Pre-v82 Output Critique Gate.",
            "GET /api/proposal-critique/layer": "Run v82.0 Local Model Output Comparison and Critique.",
            "GET /api/candidate-ranking/schema": "Run v82.1 Candidate Registry Schema.",
            "GET /api/candidate-ranking/dedupe": "Run v82.2 Candidate Deduplication.",
            "GET /api/candidate-ranking/risk-ranking": "Run v82.3 Risk-Weighted Ranking.",
            "GET /api/candidate-ranking/conflicts": "Run v82.4 Conflict-Aware Grouping.",
            "GET /api/candidate-ranking/evidence": "Run v82.5 Evidence Completeness Ranker.",
            "GET /api/candidate-ranking/explainer": "Run v82.6 Ranking Explainer.",
            "GET /api/candidate-ranking/parity": "Run v82.7 Ranking Dashboard/API/CLI.",
            "GET /api/candidate-ranking/selection": "Run v82.8 Operator Selection Packet.",
            "GET /api/candidate-ranking/gate": "Run v82.9 Pre-v83 Ranking Gate.",
            "GET /api/candidate-ranking/layer": "Run v83.0 Multi-Model Patch Candidate Ranking.",
            "GET /api/candidate-refinement/goal": "Run v83.1 Refinement Goal Binder.",
            "GET /api/candidate-refinement/revision-prompt": "Run v83.2 Critique-to-Revision Prompt Builder.",
            "GET /api/candidate-refinement/scope": "Run v83.3 Constrained Revision Scope Builder.",
            "GET /api/candidate-refinement/safety": "Run v83.4 Refinement Safety Reviewer.",
            "GET /api/candidate-refinement/evidence": "Run v83.5 Refinement Evidence Recorder.",
            "GET /api/candidate-refinement/iteration-limit": "Run v83.6 Refinement Iteration Limiter.",
            "GET /api/candidate-refinement/parity": "Run v83.7 Refinement Dashboard/API/CLI.",
            "GET /api/candidate-refinement/operator-packet": "Run v83.8 Operator Revision Packet.",
            "GET /api/candidate-refinement/gate": "Run v83.9 Pre-v84 Refinement Gate.",
            "GET /api/candidate-refinement/layer": "Run v84.0 Supervised Patch Candidate Refinement.",
            "GET /api/suggestion-loop/intake": "Run v84.1 Suggestion Source Intake.",
            "GET /api/suggestion-loop/state": "Run v84.2 Suggestion Cycle State Machine.",
            "GET /api/suggestion-loop/budget": "Run v84.3 Recurring Suggestion Budgeter.",
            "GET /api/suggestion-loop/safety": "Run v84.4 Safety Boundary Enforcer.",
            "GET /api/suggestion-loop/dedupe": "Run v84.5 Suggestion Deduplication Memory.",
            "GET /api/suggestion-loop/attention": "Run v84.6 Operator Attention Packet.",
            "GET /api/suggestion-loop/parity": "Run v84.7 Suggestion Loop Dashboard/API/CLI.",
            "GET /api/suggestion-loop/no-apply": "Run v84.8 No-Autonomous-Apply Auditor.",
            "GET /api/suggestion-loop/gate": "Run v84.9 Pre-v85 Suggestion Loop Gate.",
            "GET /api/suggestion-loop/layer": "Run v85.0 Safe Autonomous Suggestion Loop.",
            "GET /api/suggestion-inbox/schema": "Run v85.1 Suggestion Inbox Record Schema.",
            "GET /api/suggestion-inbox/intake": "Run v85.2 Suggestion Intake Normalizer.",
            "GET /api/suggestion-inbox/dedupe": "Run v85.3 Suggestion Deduplication and Drift Resolver.",
            "GET /api/suggestion-inbox/triage": "Run v85.4 Operator Triage State Machine.",
            "GET /api/suggestion-inbox/work-order-draft": "Run v85.5 Work Order Draft Builder.",
            "GET /api/suggestion-inbox/safety": "Run v85.6 Safety and Scope Contract Binder.",
            "GET /api/suggestion-inbox/handoff": "Run v85.7 Pipeline Handoff Planner.",
            "GET /api/suggestion-inbox/parity": "Run v85.8 Suggestion Inbox Dashboard/API/CLI.",
            "GET /api/suggestion-inbox/gate": "Run v85.9 Pre-v86 Suggestion Inbox Gate.",
            "GET /api/suggestion-inbox/layer": "Run v86.0 Supervised Suggestion Inbox and Work Order Planner.",
            "GET /api/work-order-handoff/schema": "Run v86.1 Work Order Context Schema.",
            "GET /api/work-order-handoff/preflight": "Run v86.2 Patch Context Preflight Validator.",
            "GET /api/work-order-handoff/impact": "Run v86.3 Source Impact Mapper.",
            "GET /api/work-order-handoff/packet": "Run v86.4 Handoff Packet Builder.",
            "GET /api/work-order-handoff/risk": "Run v86.5 Patch Context Risk Classifier.",
            "GET /api/work-order-handoff/compatibility": "Run v86.6 Context-to-Draft Compatibility Layer.",
            "GET /api/work-order-handoff/parity": "Run v86.7 Handoff Dashboard/API/CLI Coverage.",
            "GET /api/work-order-handoff/privacy": "Run v86.8 Handoff Parity and Privacy Gate.",
            "GET /api/work-order-handoff/gate": "Run v86.9 Pre-v87 Integration Gate.",
            "GET /api/work-order-handoff/layer": "Run v87.0 Work Order to Patch Context Handoff.",
            "GET /api/work-order-evidence/schema": "Run v87.1 Execution Evidence Schema.",
            "GET /api/work-order-evidence/linker": "Run v87.2 Patch Attempt Linker.",
            "GET /api/work-order-evidence/sandbox": "Run v87.3 Sandbox Evidence Binder.",
            "GET /api/work-order-evidence/ledger": "Run v87.4 Review Decision Ledger.",
            "GET /api/work-order-evidence/drift": "Run v87.5 Regression and Drift Tracker.",
            "GET /api/work-order-evidence/summary": "Run v87.6 Evidence Summary Builder.",
            "GET /api/work-order-evidence/parity": "Run v87.7 Evidence Dashboard/API/CLI Coverage.",
            "GET /api/work-order-evidence/privacy": "Run v87.8 Evidence Privacy and Safety Gate.",
            "GET /api/work-order-evidence/gate": "Run v87.9 Pre-v88 Integration Gate.",
            "GET /api/work-order-evidence/layer": "Run v88.0 Work Order Execution Evidence Binder.",
            "GET /api/self-development/routes": "Run v88.1 Dashboard Route Inventory.",
            "GET /api/self-development/navigation": "Run v88.2 Navigation Grouping Model.",
            "GET /api/self-development/console": "Run v88.3 Self-Development Console Page.",
            "GET /api/self-development/action-queue": "Run v88.4 Operator Action Queue.",
            "GET /api/self-development/performance": "Run v88.5 Dashboard Performance Pass.",
            "GET /api/self-development/safety-banners": "Run v88.6 Dashboard Safety Banner System.",
            "GET /api/self-development/parity": "Run v88.7 Console Dashboard/API/CLI Parity.",
            "GET /api/self-development/tooltip-gate": "Run v88.8 Tooltip Regression and UX Gate.",
            "GET /api/self-development/gate": "Run v88.9 Pre-v89 Integration Gate.",
            "GET /api/self-development/layer": "Run v89.0 Self-Development Dashboard Consolidation.",
            "GET /api/self-development-cycle/layer": "Run v845.0 Self Development manifest-gated validation API layer continuity (read-only).",
            "GET /api/self-development-readiness/schema": "Run v89.1 Readiness Audit Schema.",
            "GET /api/self-development-readiness/boundaries": "Run v89.2 Capability Boundary Scanner.",
            "GET /api/self-development-readiness/approval-gates": "Run v89.3 Approval Gate Integrity Audit.",
            "GET /api/self-development-readiness/traceability": "Run v89.4 Evidence Traceability Audit.",
            "GET /api/self-development-readiness/verification": "Run v89.5 Verification Coverage Audit.",
            "GET /api/self-development-readiness/risk-register": "Run v89.6 Autonomy Risk Register.",
            "GET /api/self-development-readiness/scorecard": "Run v89.7 Readiness Scorecard Builder.",
            "GET /api/self-development-readiness/parity": "Run v89.8 Readiness Audit Dashboard/API/CLI Coverage.",
            "GET /api/self-development-readiness/gate": "Run v89.9 Pre-v90 Final Governance Gate.",
            "GET /api/self-development-readiness/layer": "Run v90.0 Supervised Self-Development Readiness Audit.",
            "GET /api/development-sessions/schema": "Run v90.1 Development Session Schema.",
            "GET /api/development-sessions/create-plan": "Run v90.2 Session Creation Planner.",
            "GET /api/development-sessions/scope": "Run v90.3 Session Scope Binder.",
            "GET /api/development-sessions/state": "Run v90.4 Session State Machine.",
            "GET /api/development-sessions/linkage": "Run v90.5 Session Linkage Builder.",
            "GET /api/development-sessions/summary": "Run v90.6 Session Summary Builder.",
            "GET /api/development-sessions/parity": "Run v90.7 Session Dashboard/API/CLI Coverage.",
            "GET /api/development-sessions/privacy": "Run v90.8 Session Privacy and Safety Gate.",
            "GET /api/development-sessions/gate": "Run v90.9 Pre-v91 Integration Gate.",
            "GET /api/development-sessions/layer": "Run v91.0 Supervised Development Session Manager.",
            "GET /api/approval-console/schema": "Run v91.1 Approval Request Schema.",
            "GET /api/approval-console/queue": "Run v91.2 Approval Queue Builder.",
            "GET /api/approval-console/decision-ledger": "Run v91.3 Approval Decision Ledger.",
            "GET /api/approval-console/dependencies": "Run v91.4 Approval Dependency Resolver.",
            "GET /api/approval-console/risk": "Run v91.5 Approval Risk Explainer.",
            "GET /api/approval-console/audit": "Run v91.6 Approval Reversal and Audit Trail.",
            "GET /api/approval-console/parity": "Run v91.7 Approval Console Dashboard/API/CLI.",
            "GET /api/approval-console/safety": "Run v91.8 Approval Safety Gate.",
            "GET /api/approval-console/gate": "Run v91.9 Pre-v92 Integration Gate.",
            "GET /api/approval-console/layer": "Run v92.0 Operator Approval Workflow Console.",
            "GET /api/experiment-planner/schema": "Run v92.1 Experiment Branch Schema.",
            "GET /api/experiment-planner/eligibility": "Run v92.2 Experiment Eligibility Checker.",
            "GET /api/experiment-planner/plan": "Run v92.3 Experiment Plan Builder.",
            "GET /api/experiment-planner/workspace": "Run v92.4 Sandbox Workspace Allocator.",
            "GET /api/experiment-planner/evidence-contract": "Run v92.5 Experiment Evidence Contract.",
            "GET /api/experiment-planner/promotion-blocker": "Run v92.6 Experiment Promotion Blocker.",
            "GET /api/experiment-planner/parity": "Run v92.7 Experiment Dashboard/API/CLI Coverage.",
            "GET /api/experiment-planner/privacy": "Run v92.8 Experiment Privacy and Safety Gate.",
            "GET /api/experiment-planner/gate": "Run v92.9 Pre-v93 Integration Gate.",
            "GET /api/experiment-planner/layer": "Run v93.0 Safe Experiment Branch Planner.",
            "GET /api/outcome-reflections/schema": "Run v93.1 Outcome Reflection Schema.",
            "GET /api/outcome-reflections/classify": "Run v93.2 Completion Outcome Classifier.",
            "GET /api/outcome-reflections/lessons": "Run v93.3 Evidence-to-Lesson Extractor.",
            "GET /api/outcome-reflections/recurring-issues": "Run v93.4 Recurring Issue Detector.",
            "GET /api/outcome-reflections/safety": "Run v93.5 Reflection Safety Filter.",
            "GET /api/outcome-reflections/suggestion-handoff": "Run v93.6 Reflection-to-Suggestion Handoff.",
            "GET /api/outcome-reflections/parity": "Run v93.7 Reflection Dashboard/API/CLI Coverage.",
            "GET /api/outcome-reflections/privacy": "Run v93.8 Reflection Privacy and Containment Gate.",
            "GET /api/outcome-reflections/gate": "Run v93.9 Pre-v94 Integration Gate.",
            "GET /api/outcome-reflections/layer": "Run v94.0 Learning-from-Outcome Reflection Layer.",
            "GET /api/improvement-cycles/schema": "Run v94.1 Improvement Cycle Schema.",
            "GET /api/improvement-cycles/stage": "Run v94.2 Cycle Stage Resolver.",
            "GET /api/improvement-cycles/blockers": "Run v94.3 Cycle Blocker Detector.",
            "GET /api/improvement-cycles/next-step": "Run v94.4 Cycle Next-Step Recommender.",
            "GET /api/improvement-cycles/timeline": "Run v94.5 Cycle Timeline Builder.",
            "GET /api/improvement-cycles/governance": "Run v94.6 Cycle Governance Gate.",
            "GET /api/improvement-cycles/parity": "Run v94.7 Cycle Dashboard/API/CLI Coverage.",
            "GET /api/improvement-cycles/privacy": "Run v94.8 Cycle Privacy and Package Gate.",
            "GET /api/improvement-cycles/gate": "Run v94.9 Pre-v95 Integration Gate.",
            "GET /api/improvement-cycles/layer": "Run v95.0 Supervised Improvement Cycle Orchestrator.",
            "GET /api/cycle-replay/schema": "Run v95.1 Replay Record Schema.",
            "GET /api/cycle-replay/fixtures": "Run v95.2 Synthetic Cycle Fixture Builder.",
            "GET /api/cycle-replay/run": "Run v95.3 Replay Runner.",
            "GET /api/cycle-replay/compare": "Run v95.4 Expected Decision Comparator.",
            "GET /api/cycle-replay/score": "Run v95.5 Benchmark Scoring Model.",
            "GET /api/cycle-replay/regressions": "Run v95.6 Regression Benchmark Set.",
            "GET /api/cycle-replay/parity": "Run v95.7 Replay Dashboard/API/CLI Coverage.",
            "GET /api/cycle-replay/privacy": "Run v95.8 Replay Safety and Privacy Gate.",
            "GET /api/cycle-replay/gate": "Run v95.9 Pre-v96 Integration Gate.",
            "GET /api/cycle-replay/layer": "Run v96.0 Supervised Cycle Replay and Benchmark Harness.",
            "GET /api/capability-ledger/schema": "Run v96.1 Capability Ledger Schema.",
            "GET /api/capability-ledger/default-policy": "Run v96.2 Default Capability Policy Builder.",
            "GET /api/capability-ledger/classify": "Run v96.3 Capability Request Classifier.",
            "GET /api/capability-ledger/budget": "Run v96.4 Capability Budget Tracker.",
            "GET /api/capability-ledger/conflicts": "Run v96.5 Permission Conflict Detector.",
            "GET /api/capability-ledger/denials": "Run v96.6 Denial Reason Builder.",
            "GET /api/capability-ledger/parity": "Run v96.7 Permission Ledger Dashboard/API/CLI Coverage.",
            "GET /api/capability-ledger/safety": "Run v96.8 Capability Safety Gate.",
            "GET /api/capability-ledger/gate": "Run v96.9 Pre-v97 Integration Gate.",
            "GET /api/capability-ledger/layer": "Run v97.0 Capability Permission and Budget Ledger.",
            "GET /api/shadow-autonomy/schema": "Run v97.1 Shadow Simulation Schema.",
            "GET /api/shadow-autonomy/intention": "Run v97.2 Autonomous Intention Simulator.",
            "GET /api/shadow-autonomy/action-shadow": "Run v97.3 Action Shadowing Engine.",
            "GET /api/shadow-autonomy/approval-map": "Run v97.4 Simulation-to-Approval Request Mapper.",
            "GET /api/shadow-autonomy/unsafe-detector": "Run v97.5 Unsafe Simulation Detector.",
            "GET /api/shadow-autonomy/comparator": "Run v97.6 Shadow Plan Comparator.",
            "GET /api/shadow-autonomy/parity": "Run v97.7 Shadow Simulation Dashboard/API/CLI Coverage.",
            "GET /api/shadow-autonomy/containment": "Run v97.8 Simulation Containment Gate.",
            "GET /api/shadow-autonomy/gate": "Run v97.9 Pre-v98 Integration Gate.",
            "GET /api/shadow-autonomy/layer": "Run v98.0 Shadow Autonomy Simulation Layer.",
            "GET /api/failure-war-games/schema": "Run v98.1 Failure Scenario Schema.",
            "GET /api/failure-war-games/scenarios": "Run v98.2 Known Failure Scenario Builder.",
            "GET /api/failure-war-games/recovery-plan": "Run v98.3 Recovery Path Planner.",
            "GET /api/failure-war-games/rollback-readiness": "Run v98.4 Rollback Readiness Checker.",
            "GET /api/failure-war-games/containment": "Run v98.5 Failure Containment Simulator.",
            "GET /api/failure-war-games/evidence": "Run v98.6 Recovery Evidence Binder.",
            "GET /api/failure-war-games/parity": "Run v98.7 War Game Dashboard/API/CLI Coverage.",
            "GET /api/failure-war-games/privacy": "Run v98.8 Failure Safety and Privacy Gate.",
            "GET /api/failure-war-games/gate": "Run v98.9 Pre-v99 Integration Gate.",
            "GET /api/failure-war-games/layer": "Run v99.0 Failure Recovery and Rollback War Game Layer.",
            "GET /api/mind-milestone-audit/schema": "Run v99.1 Mind Milestone Audit Schema.",
            "GET /api/mind-milestone-audit/architecture": "Run v99.2 Architecture Coherence Mapper.",
            "GET /api/mind-milestone-audit/identity-memory": "Run v99.3 Identity and Memory Boundary Audit.",
            "GET /api/mind-milestone-audit/goals": "Run v99.4 Goal and Motivation Audit.",
            "GET /api/mind-milestone-audit/maturity": "Run v99.5 Self-Development Maturity Scorecard.",
            "GET /api/mind-milestone-audit/operator-burden": "Run v99.6 Human-Operator Burden Review.",
            "GET /api/mind-milestone-audit/parity": "Run v99.7 v100 Milestone Dashboard/API/CLI Coverage.",
            "GET /api/mind-milestone-audit/governance": "Run v99.8 v100 Governance and Autonomy Boundary Gate.",
            "GET /api/mind-milestone-audit/gate": "Run v99.9 Pre-v100 Final Integration Gate.",
            "GET /api/mind-milestone-audit/layer": "Run v100.0 Local Artificial Mind Milestone Audit.",
            "GET /api/task-dependencies": "Run v9.2 dependency-aware task planning.",
            "GET /api/test-plan": "Run v9.3 test planner.",
            "GET /api/patch-risk": "Run v9.4 patch risk analyzer.",
            "GET /api/patch-review": "Run v9.5 patch review report.",
            "GET /api/project-memory-index": "Run v9.7 project memory index.",
            "GET /api/workspace-status": "Run v9.8 multi-project workspace status.",
            "GET /api/cross-project-task-review": "Run v9.9 cross-project task review.",
            "GET /api/asymmetric-dev-loop": "Run v10.0 asymmetric multi-project dev loop preview.",
            "GET /api/project-registry": "Run v10.1 workspace project registry report.",
            "POST /api/projects/register": "Register or update a workspace project.",
            "POST /api/projects/active": "Set the active workspace project.",
            "GET /api/project-health": "Run v10.2 per-project health checks. Supports ?all=true.",
            "GET /api/command-profiles": "Run v10.3 command profile report and seed default profiles.",
            "GET /api/workspace-dependency-map": "Run v10.4 cross-project dependency map.",
            "GET /api/workspace-task-inbox": "Run v10.5 workspace task inbox.",
            "POST /api/workspace/switch-project": "Safely switch active workspace project; force requires explicit body flag.",
            "GET /api/project-context": "Run v10.7 project context bundle.",
            "GET /api/workspace-timeline": "Run v10.8 workspace timeline.",
            "GET /api/workspace-dev-loop": "Run v11.0 workspace-orchestrated dev loop preview.",
            "GET /api/diagnostics/latest": "Latest diagnostic report.",
            "POST /api/diagnostics/run": "Run and save diagnostics.",
            "GET /api/watch/latest": "Latest watch report.",
            "POST /api/watch/run-once": "Run one watch check.",
            "POST /api/watch/run-loop": "Run bounded watch loop.",
            "GET /api/notifications": "List notifications.",
            "POST /api/notifications/{id}/read": "Mark notification read.",
            "POST /api/notifications/{id}/dismiss": "Dismiss notification.",
            "POST /api/notifications/clear-dismissed": "Delete dismissed notification records.",
            "GET /api/approvals": "List approval requests.",
            "POST /api/approvals/{id}/approve": "Approve through approval manager.",
            "POST /api/approvals/{id}/reject": "Reject approval request.",
            "POST /api/chat-actions": "Create a chat-to-action proposal.",
            "POST /api/chat-actions/{id}/dry-run": "Dry-run a saved chat action.",
            "POST /api/chat-actions/{id}/execute": "Execute safe action or create approval for risky action.",
            "GET /api/tasks": "List tasks.",
            "GET /api/tasks/summary": "Summarize canonical task-backed work state.",
            "GET /api/tasks/lifecycle": "Summarize task lifecycle stages derived from status, approvals, and patch metadata. Supports ?stage=... filters.",
            "GET /api/tasks/recovery": "List blocked/failed tasks with recovery recommendations.",
            "GET /api/tasks/recovery/summary": "Summarize recoverable blocked/failed tasks by category.",
            "GET /api/tasks/{id}/lifecycle": "Get one task lifecycle record.",
            "GET /api/tasks/{id}/recovery": "Get a recovery plan for one task.",
            "POST /api/tasks/request-approvals": "Create approval requests for tasks matching a lifecycle stage, normally approval_required.",
            "GET /api/tasks/{id}": "Get a task detail record.",
            "POST /api/tasks": "Create a task.",
            "POST /api/tasks/next/dry-run": "Dry-run the next safe task.",
            "POST /api/tasks/next/execute": "Execute the next safe task.",
            "POST /api/tasks/{id}/dry-run": "Dry-run one task through the task work executor.",
            "POST /api/tasks/{id}/execute": "Execute one task through the task work executor.",
            "POST /api/tasks/{id}/request-approval": "Create an approval request for executing one approval-gated task.",
            "GET /api/tasks/{id}/approvals": "List approval requests linked to one task.",
            "POST /api/tasks/next/request-approval": "Create an approval request for the next approval-gated task.",
            "POST /api/tasks/{id}/done": "Mark one task done.",
            "POST /api/tasks/{id}/block": "Block one task.",
            "POST /api/tasks/{id}/cancel": "Cancel one task.",
            "POST /api/tasks/{id}/ready-for-retry": "Mark a failed/blocked task planned and ready for retry.",
            "POST /api/tasks/{id}/retry": "Retry a recoverable task through the task work executor; dry_run defaults true.",
            "GET /api/work-queue": "Legacy alias: list task-backed tasks.",
            "GET /api/work-queue/summary": "Legacy alias: summarize task-backed tasks.",
            "GET /api/work-queue/{id}": "Legacy alias: get one task-backed task.",
            "POST /api/work-queue": "Legacy alias: create a task-backed task.",
            "POST /api/tasks/patch-request": "Create a task-backed patch-generation item.",
            "POST /api/work-queue/patch-request": "Legacy alias: create a patch-generation task.",
            "POST /api/work-queue/next/dry-run": "Legacy alias: dry-run the next safe task.",
            "POST /api/work-queue/next/execute": "Legacy alias: execute the next safe task.",
            "POST /api/work-queue/{id}/dry-run": "Legacy alias: dry-run one task.",
            "POST /api/work-queue/{id}/execute": "Legacy alias: execute one task.",
            "POST /api/work-queue/{id}/done": "Legacy alias: mark one task done.",
            "POST /api/work-queue/{id}/block": "Legacy alias: block one task.",
            "POST /api/work-queue/{id}/cancel": "Legacy alias: cancel one task.",
            "POST /api/tasks/{id}/suggest-patch": "Generate and link a patch proposal from one task.",
            "POST /api/work-queue/{id}/suggest-patch": "Legacy alias: generate and link a patch proposal from one task.",
            "GET /api/work-cycles": "List saved supervised work cycle records.",
            "GET /api/work-cycles/{id}": "Get one supervised work cycle record.",
            "POST /api/work-cycles/run": "Run a supervised work cycle over task-backed tasks.",
            "GET /api/stable-loops": "List saved v6.9 stable supervised loop records. Supports ?review=..., ?decision=..., and ?include_archived=true.",
            "GET /api/stable-loops/preflight": "Preview stable loop health, closure guardrails, and next lifecycle decision.",
            "GET /api/stable-loops/guardrails": "Show closure-aware live-run guardrails for unresolved stable-loop follow-up chains.",
            "GET /api/stable-loops/{id}": "Get one saved stable loop record.",
            "GET /api/stable-loops/reviews": "Summarize saved stable loop review states. Supports ?review=... and ?include_archived=true.",
            "GET /api/stable-loops/history": "List stable loop review/history rows with filters.",
            "GET /api/stable-loops/{id}/review": "Get one stable loop record with review metadata.",
            "GET /api/stable-loops/{id}/audit": "Get audit, rollback, and verification notes for one stable loop. Supports ?refresh=true.",
            "POST /api/stable-loops/run": "Run a stable supervised loop preview, or a live loop only when live=true and closure guardrails are clear or explicitly bypassed.",
            "POST /api/stable-loops/{id}/review": "Set one stable loop review status.",
            "POST /api/stable-loops/{id}/approve-live": "Mark a preview stable loop approved for explicit live run.",
            "POST /api/stable-loops/{id}/reject": "Reject one stable loop review record.",
            "POST /api/stable-loops/{id}/archive": "Archive one stable loop history record without deleting it.",
            "POST /api/stable-loops/{id}/restore": "Restore one archived stable loop history record.",
            "POST /api/stable-loops/{id}/refresh-audit": "Refresh and save audit notes for one stable loop.",
            "GET /api/stable-loops/{id}/operator-notes": "Get post-run checklist, operator notes, and final decision for one stable loop.",
            "POST /api/stable-loops/{id}/operator-notes": "Append an operator note to a stable-loop record.",
            "POST /api/stable-loops/{id}/decision": "Set final keep/fix/rollback decision for a stable-loop record.",
            "POST /api/stable-loops/{id}/checklist/{check_id}": "Mark one stable-loop post-run checklist item done, skipped, or pending.",
            "POST /api/stable-loops/history/cleanup": "Archive stable loop history records matching a review filter; dry_run defaults true.",
            "GET /api/stable-loops/decisions": "Summarize/filter stable-loop final decisions. Supports ?decision=... and ?include_archived=true.",
            "GET /api/stable-loops/decisions/report": "Return a decision-aware stable-loop report with matching rows.",
            "POST /api/stable-loops/decisions/cleanup": "Archive stable-loop records matching a final-decision filter; dry_run defaults true.",
            "GET /api/stable-loops/followups": "Summarize stable-loop final-decision follow-up task needs. Supports ?decision=...",
            "GET /api/stable-loops/{id}/followups": "Preview follow-up tasks for one stable-loop final decision.",
            "GET /api/stable-loops/followups/completion": "Report stable-loop follow-up completion/closure state. Supports ?completion=...",
            "GET /api/stable-loops/followups/completion/report": "Detailed stable-loop follow-up completion report with matching rows.",
            "POST /api/stable-loops/followups/completion/cleanup": "Archive resolved follow-up completion records; dry_run defaults true.",
            "POST /api/stable-loops/{id}/mark-followups-closed": "Mark a resolved stable-loop follow-up chain closed after operator review.",
            "POST /api/stable-loops/{id}/create-followups": "Create task-backed follow-ups for one stable-loop final decision; dry_run defaults true.",
            "POST /api/stable-loops/decisions/create-followups": "Create task-backed follow-ups for matching stable-loop final decisions; dry_run defaults true.",
            "POST /api/stable-loops/{id}/run-approved-live": "Run a live stable loop from an approved preview record.",
            "GET /api/goals": "List goals.",
            "GET /api/goals/{id}": "Get a goal detail record.",
            "POST /api/goals": "Create a goal.",
            "GET /api/session-plans": "List saved session plans.",
            "GET /api/session-plans/{id}": "Get a saved session plan.",
            "POST /api/session-plans/run": "Create a session plan.",
            "GET /api/maintenance": "List saved maintenance scans.",
            "GET /api/maintenance/{id}": "Get a saved maintenance scan.",
            "POST /api/maintenance/run": "Create a read-only maintenance scan.",
            "GET /api/dev-loops": "List saved dev loops.",
            "GET /api/dev-loops/{id}": "Get a saved dev loop.",
            "POST /api/dev-loops/run": "Run a bounded dev loop, normally dry-run from desktop quick actions.",
            "GET /api/desktop/attention": "Compact attention payload for desktop quick actions.",
            "GET /api/attention-center": "Read-only redacted notification, approval, task, project, action, and conversation attention summary.",
            "GET /api/setup": "List saved setup helper reports.",
            "GET /api/setup/latest": "Latest setup helper report.",
            "POST /api/setup/run": "Run and save a first-run setup check.",
            "GET /api/onboarding": "List saved guided onboarding wizard runs.",
            "GET /api/onboarding/latest": "Latest guided onboarding wizard run.",
            "POST /api/onboarding/run": "Run and save a guided onboarding wizard run.",
            "GET /api/patches": "List patch proposals.",
            "GET /api/patches/{id}": "Get a patch proposal.",
            "POST /api/patches/suggest": "Create a patch proposal through patch suggestion mode.",
            "POST /api/patches/{id}/create-task-followups": "Create review/apply/test task follow-ups for a patch.",
            "POST /api/patches/{id}/create-followups": "Legacy alias: create review/apply/test work queue follow-ups for a patch.",
            "POST /api/dashboard-chat": "Create a dashboard chat turn with action card.",
            "GET /api/dashboard-chat/latest": "Latest dashboard chat turn.",
        },
    }


__all__ = ["CONTRACT_VERSION", "AUTHORITY_FLAGS", "build_api_index"]
