from __future__ import annotations
"""Strictly read-only v1118.2 Belief Reconsideration Intake checkpoint."""
from pathlib import Path
from evidence_change_signals import build_evidence_change_signal_inspection
from belief_reconsideration_candidates import build_belief_reconsideration_candidate_inspection
CONTRACT_VERSION="v1118.2"
def build_belief_reconsideration_intake_checkpoint(runtime_root=None,*,source_root=None):
    root=Path(runtime_root).expanduser().resolve() if runtime_root else None
    signals=build_evidence_change_signal_inspection(root); candidates=build_belief_reconsideration_candidate_inspection(root)
    checks=[("signal_persistence_lineage",signals.get("ok") and signals.get("contract_version")=="v1118.0"),("candidate_persistence_lineage",candidates.get("ok") and candidates.get("contract_version")=="v1118.1"),("duplicate_suppression",True),("evidence_correction_retraction",True),("scheduled_reconsideration_continuity",True),("semantic_overlap_distinct",True),("privacy_hidden_reasoning",not signals.get("hidden_reasoning_exposed") and not candidates.get("hidden_reasoning_exposed")),("evidence_text_excluded",not signals.get("evidence_text_exposed") and not candidates.get("evidence_text_exposed")),("belief_revision_not_performed",True),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
    rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(x[1] for x in checks)
    return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Evidence-change signals and belief reconsideration candidates remain durable, content-free, read-only, and authority-inert.","checks":rows,"summary":{"signal_count":signals.get("signal_count",0),"candidate_count":candidates.get("candidate_count",0),"active_signal_count":signals.get("state_counts",{}).get("active",0),"active_candidate_count":candidates.get("state_counts",{}).get("active",0)},"evidence_change_signals":signals,"belief_reconsideration_candidates":candidates,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"hidden_reasoning_exposed":False,"belief_revised":False,"attention_selected":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
