from __future__ import annotations
"""Strictly read-only v1145.8 Conversation-Cognition Unification Reliability checkpoint."""
from pathlib import Path
import hashlib, os
from typing import Any
from conversation_cognition_unification_execution_checkpoint import build_conversation_cognition_unification_execution_checkpoint
from conversation_cognition_cross_cycle_continuity import build_conversation_cognition_cross_cycle_continuity_inspection
from conversation_cognition_reliability_review import build_conversation_cognition_reliability_review_inspection
CONTRACT_VERSION="v1145.8"
def _root(): return (Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition')
def _sig(path:Path):
 h=hashlib.sha256()
 if not path.exists(): return h.hexdigest()
 for p in sorted(x for x in path.rglob('*') if x.is_file()):
  st=p.stat(); h.update(str(p.relative_to(path)).encode()); h.update(str(st.st_size).encode()); h.update(str(st.st_mtime_ns).encode())
 return h.hexdigest()
def build_conversation_cognition_unification_reliability_checkpoint(runtime_root=None,*,source_root=None)->dict[str,Any]:
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb,sb=_sig(runtime),_sig(source)
 execution=build_conversation_cognition_unification_execution_checkpoint(runtime,source_root=source); continuity=build_conversation_cognition_cross_cycle_continuity_inspection(runtime); reviews=build_conversation_cognition_reliability_review_inspection(runtime); cr=continuity.get('recent_records',[]); rr=reviews.get('recent_reviews',[])
 checks=[('execution_contract',execution.get('contract_version')=='v1145.5'),('continuity_contract',continuity.get('contract_version')=='v1145.6'),('reliability_contract',reviews.get('contract_version')=='v1145.7'),('exact_cross_cycle_lineage',all(r.get('prior_generation_receipt_id') and r.get('current_generation_receipt_id') and r.get('session_id') and r.get('conversation_id') for r in cr)),('current_historical_separation',continuity.get('current_historical_separated')),('current_thought_grounding',all('current_thought_grounded' in r for r in cr)),('memory_consistency',all('memory_consistent' in r for r in cr)),('relationship_boundaries',all('relationship_boundary_clear' in r for r in cr)),('mood_goal_coherence',all('mood_goal_coherent' in r for r in cr)),('correction_effectiveness',reviews.get('correction_effectiveness_visible')),('stale_context_detection',continuity.get('stale_context_detected')),('deliberate_silence_preserved',continuity.get('silence_preserved')),('visible_behavior_structural_only',reviews.get('visible_behavior_structural_only')),('duplicate_retry_review',all('retry_count' in r and 'duplicate_count' in r for r in rr)),('uncertainty_bounded',all(0<=float(r.get('uncertainty',0))<=1 for r in rr)),('privacy_content_free',continuity.get('content_free') and reviews.get('visible_behavior_structural_only')),('authority_separation',not any((continuity.get('authority_boundary') or {}).values()) and not any((reviews.get('authority_boundary') or {}).values())),('no_message_authority',not continuity.get('message_sent') and not reviews.get('message_sent')),('checkpoint_read_only',rb==_sig(runtime) and sb==_sig(source)),('source_runtime_separation',not str(runtime).startswith(str(source))),('desktop_verification_pending',True)]
 passed=sum(bool(v) for _,v in checks)
 return {"ok":passed==len(checks),"status":"ready_for_desktop_verification" if passed==len(checks) else "review_required","contract_version":CONTRACT_VERSION,"checkpoint_name":"Conversation-Cognition Unification Reliability","passed":passed,"total":len(checks),"checks":[{"id":k,"status":"pass" if v else "fail"} for k,v in checks],"execution":execution,"continuity":continuity,"reviews":reviews,"summary":{"continuity_record_count":continuity.get('record_count',0),"reliability_review_count":reviews.get('review_count',0),"stale_context_count":(continuity.get('state_counts') or {}).get('stale_context',0),"review_required_count":(reviews.get('state_counts') or {}).get('review_required',0)},"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_conversation_exposed":False,"prompt_exposed":False,"generated_response_exposed":False,"hidden_reasoning_exposed":False,"provider_contacted_by_checkpoint":False,"message_sent":False,"cognition_mutated":False,"approval_created":False,"authorization_created":False,"installation_performed":False,"promotion_performed":False,"certification_performed":False,"consciousness_proven":False,"desktop_verification_pending":True,"desktop_verification":"pending"}
