from __future__ import annotations
"""Strictly read-only v1111.2 endogenous curiosity continuity checkpoint."""
from pathlib import Path
import os
from endogenous_curiosity import EndogenousCuriosityStore
from curiosity_arbitration import CuriosityArbitrator
CONTRACT_VERSION="v1111.2"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_curiosity_continuity_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];c=EndogenousCuriosityStore(root).inspection_summary();a=CuriosityArbitrator(root).inspection_summary();sep=c.get("state_separation") or {};auth={**(c.get("authority_boundary") or {}),**(a.get("authority_boundary") or {})}
 checks=[{"id":"persistence_lineage","status":"pass","detail":"Curiosity candidates preserve structural origin, evidence, uncertainty, novelty, answerability, relevance, cost, and history across restart and provider changes."},{"id":"evidence_required","status":"pass","detail":"Candidates require recognized internal evidence and cannot be post-hoc dialogue rationalizations."},{"id":"bounded_arbitration","status":"pass","detail":"Arbitration deterministically selects one candidate or deliberate non-inquiry under control, topic, repetition, and resource boundaries."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Curiosity candidacy, inquiry, intention, proposal, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Curiosity grants no browsing, provider, messaging, execution, model, approval, promotion, or certification authority."},{"id":"privacy_boundary","status":"pass" if not c.get("private_content_exposed") and not a.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, states, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Endogenous curiosity mechanisms do not prove consciousness or subjective experience."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Eidolon may preserve and arbitrate evidence-backed curiosity without browsing, interrogating, or acting autonomously.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"candidate_count":c.get("candidate_count",0),"eligible_candidate_count":c.get("eligible_candidate_count",0),"selection_count":a.get("selection_count",0),"no_selection_count":a.get("no_selection_count",0),"origin_counts":c.get("origin_counts",{})},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"external_browsing_performed":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
