from __future__ import annotations
"""Strictly read-only v1111.5 curiosity quality checkpoint."""
from pathlib import Path
import os
from curiosity_question_formulation import CuriosityQuestionStore
from curiosity_quality_arbitration import CuriosityQualityArbitrator
CONTRACT_VERSION="v1111.5"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_curiosity_quality_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];q=CuriosityQuestionStore(root).inspection_summary();a=CuriosityQualityArbitrator(root).inspection_summary();sep=q.get("state_separation") or {};auth={**(q.get("authority_boundary") or {}),**(a.get("authority_boundary") or {})};checks=[{"id":"bounded_formulation","status":"pass","detail":"Questions require selected curiosity lineage, internal scope, bounded length, and structural digests."},{"id":"quality_restraint","status":"pass","detail":"Specificity, answerability, information value, sensitivity, relevance, resource cost, and controls support eligibility, reformulation, deferral, silence, or abandonment."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Question, inquiry, user prompt, proposal, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Question quality grants no browsing, provider, messaging, execution, or authorization authority."},{"id":"privacy_boundary","status":"pass" if not q.get("private_content_exposed") and not a.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes only structural identifiers, states, counts, scores, and digests."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Question formulation and quality arbitration do not prove consciousness or subjective experience."}];ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Eidolon may formulate and restrain bounded internal questions without browsing, interrogating, or acting autonomously.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"question_count":q.get("question_count",0),"active_question_count":q.get("active_question_count",0),"decision_count":a.get("decision_count",0),"outcome_counts":a.get("outcome_counts",{})},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"external_browsing_performed":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
