from __future__ import annotations
"""v1283.3-v1283.5 bridges proven development-memory lineages into bounded relevance records."""
from typing import Any,Mapping,Sequence
from development_memory_relevance_foundations import *
CONTRACT_VERSION="v1283.5"
_TYPE_MAP={"operator_goal":"requirement","pending_work":"requirement","open_question":"requirement","design_decision":"decision","limitation_risk":"failure","completed_work":"previous_approach"}
def record_from_project_understanding(item:Mapping[str,Any])->dict[str,Any]:
 typ=_TYPE_MAP.get(str(item.get("item_type") or ""),"previous_approach");tags=list(item.get("relevance_tags") or item.get("component_codes") or [])+[str(item.get("item_type") or typ)];return build_development_memory_record(memory_code=f"project_{item.get('item_code') or 'item'}",memory_type=typ,relevance_tags=tags,project_code=str(item.get("project_code") or ""),semantic_key=str(item.get("item_code") or ""),confidence={"low":30,"medium":50,"high":70,"verified":90}.get(str(item.get("confidence") or "medium"),50),freshness="current" if item.get("classification") in {"still_valid","present"} else "historical",verification_state="verified" if item.get("confidence")=="verified" else "unverified",contradicted=item.get("classification") in {"contradicted","superseded"})
def record_from_development_outcome_lesson(lesson:Mapping[str,Any])->dict[str,Any]:
 return build_development_memory_record(memory_code=f"lesson_{lesson.get('lesson_code') or lesson.get('lesson_id') or 'item'}",memory_type="lesson",relevance_tags=list(lesson.get("relevance_tags") or lesson.get("context_codes") or []),project_code=str(lesson.get("project_code") or ""),semantic_key=str(lesson.get("lesson_code") or lesson.get("lesson_id") or ""),confidence=int(lesson.get("confidence_score") or 60),freshness=str(lesson.get("freshness") or "recent"),verification_state="verified" if lesson.get("verified") is True else "unverified",contradicted=lesson.get("contradicted") is True)
def build_development_memory_projection(*,task_code:str,task_tags:Sequence[str],project_items:Sequence[Mapping[str,Any]]=(),lessons:Sequence[Mapping[str,Any]]=(),other_records:Sequence[Mapping[str,Any]]=(),project_code:str="")->dict[str,Any]:
 rows=[record_from_project_understanding(x) for x in project_items]+[record_from_development_outcome_lesson(x) for x in lessons]+[dict(x) for x in other_records];r=retrieve_relevant_development_memories(task_code=task_code,task_tags=task_tags,candidates=rows,project_code=project_code);r["project_understanding_bridge_count"]=len(project_items);r["lesson_bridge_count"]=len(lessons);r["memory_sources_are_evidence_only"]=True;return r
__all__=["CONTRACT_VERSION","record_from_project_understanding","record_from_development_outcome_lesson","build_development_memory_projection"]
