from __future__ import annotations

"""Provider-free, read-only discovery of bounded source improvement families.

v1490.0-v1490.2 deliberately stops at structural discovery.  It inventories
source, records content-free evidence, describes zero or more candidate
families, and rejects unsafe/weak families.  It does not rank, select, persist,
prepare, approve, implement, install, promote, or contact a provider.
"""

import ast
import builtins
import copy
from collections import Counter, defaultdict
import hashlib
import json
from pathlib import Path
import re
import time
from typing import Any, Iterable, Mapping, Sequence

from symbol_level_refactoring import MAX_EXTERNAL_DEPENDENCIES


DISCOVERY_SCHEMA_VERSION = "eidolon.dynamic_improvement_discovery.v1490.2"
MAX_ADJACENCY_GAP = 48
MAX_FAMILY_SYMBOLS = 8
MAX_FAMILY_SPAN_LINES = 280
MAX_ESTIMATED_DEPENDENCIES = 36
MAX_PUBLIC_CANDIDATES = 24
MAX_PUBLIC_REJECTIONS = 48

_GENERIC_FAMILY_TOKENS = {
    "api", "build", "builder", "check", "create", "data", "default", "eidolon",
    "get", "helper", "helpers", "maintenance", "make", "print", "read", "render",
    "report", "review", "self", "set", "stage", "summary", "system", "text", "write",
}
_PROTECTED_AUTHORITY_TOKENS = {
    "approval", "approve", "authorization", "authorize", "authority", "credential",
    "execute", "execution", "install", "installation", "model", "permission",
    "promote", "promotion", "provider", "release", "rollback", "secret", "signature",
    "signing", "publish",
}
_PROTECTED_COMPOUND_IDENTIFIERS = {
    ("source", "apply"), ("live", "apply"), ("release", "apply"),
    ("model", "install"), ("approval", "execute"), ("provider", "switch"),
    ("rollback", "apply"),
}
_DEPENDENCY_FACTORY_RE = re.compile(r"(?:^|_)(?:dependency|dependencies|deps)(?:_|$)", re.I)
_GENERATED_WRAPPER_RE = re.compile(r"(?:^|_)(?:generated|autogenerated|factory_wrapper)(?:_|$)", re.I)
_IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
_VERSION_TOKEN_RE = re.compile(r"^v?\d+(?:_\d+)*$")
_SIMPLE_IMPORT_RE = re.compile(r"(?m)^[ \t]*import[ \t]+([^\n#]+)")
_FROM_IMPORT_RE = re.compile(r"(?ms)^[ \t]*from[ \t]+([A-Za-z_][A-Za-z0-9_\.]*)[ \t]+import[ \t]+(\([^)]*\)|[^\n#]+)")
_ATTRIBUTE_CHAIN_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+\b")


def _digest(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    ).hexdigest()



_DISCOVERY_CACHE: dict[str, dict[str, Any]] = {}
_DISCOVERY_CACHE_LIMIT = 4
_LAST_SOURCE_SHAPE: dict[str, str] = {}
_MODULE_ANALYSIS_CACHE: dict[tuple[str, str], dict[str, Any]] = {}
_TEST_ANALYSIS_CACHE: dict[tuple[str, str], dict[str, Any]] = {}
_FILE_CACHE_LIMIT = 8192


def _raw_file_digest(path: Path) -> str:
    """Hash current raw bytes. Metadata alone is never sufficient cache evidence."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _source_shape_fingerprint(root: Path) -> str:
    # Cache admission must be content-bound.  Windows callers can replace a file
    # with same-length bytes and restore its mtime, so path/size/mtime is not a
    # trustworthy source identity.  The warm path intentionally re-reads bytes
    # to prove the cached evidence still describes the current tree.
    rows: list[tuple[str, str]] = []
    agent_root = root / "conscious_agent"
    for path in sorted(agent_root.rglob("*.py")) if agent_root.is_dir() else []:
        relative = path.relative_to(root)
        if any(part in {"__pycache__", "data", ".git", ".venv", "venv"} for part in relative.parts):
            continue
        rows.append((relative.as_posix(), _raw_file_digest(path)))
    tools = root / "tools"
    if tools.is_dir():
        for path in sorted({*tools.glob("*_tests.py"), *tools.glob("test_*.py")}):
            rows.append((path.relative_to(root).as_posix(), _raw_file_digest(path)))
    return _digest(rows)

def _safe_relative(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _identifier_tokens(name: str) -> list[str]:
    normalized = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", str(name or ""))
    return [token.casefold() for token in re.findall(r"[A-Za-z]+|\d+", normalized.replace("__", "_"))]


def _snake_tokens(name: str) -> list[str]:
    parts = _identifier_tokens(name)
    return [
        token
        for token in parts
        if len(token) > 2 and token not in _GENERIC_FAMILY_TOKENS and not _VERSION_TOKEN_RE.fullmatch(token)
    ]


def _identifier_is_protected(name: str) -> bool:
    tokens = [token for token in _identifier_tokens(name) if not _VERSION_TOKEN_RE.fullmatch(token)]
    if any(token in _PROTECTED_AUTHORITY_TOKENS for token in tokens):
        return True
    return any(tuple(tokens[index:index + 2]) in _PROTECTED_COMPOUND_IDENTIFIERS for index in range(max(0, len(tokens) - 1)))


def _callee_name(node: ast.AST | None) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = _callee_name(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    return ""


def _strip_docstring(body: Sequence[ast.stmt]) -> list[ast.stmt]:
    rows = list(body)
    if rows and isinstance(rows[0], ast.Expr) and isinstance(rows[0].value, ast.Constant) and isinstance(rows[0].value.value, str):
        rows = rows[1:]
    return rows


def _is_retained_extraction_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    body = _strip_docstring(node.body)
    if len(body) != 1:
        return False
    statement = body[0]
    call: ast.Call | None = None
    if isinstance(statement, ast.Return) and isinstance(statement.value, ast.Call):
        call = statement.value
    elif isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Call):
        call = statement.value
    if call is None:
        return False
    callee = _callee_name(call.func).casefold()
    return callee.endswith("_implementation") or ".implementation" in callee


def _is_dependency_factory(name: str) -> bool:
    folded = name.casefold()
    return bool(_DEPENDENCY_FACTORY_RE.search(folded)) or folded.endswith("dependencies")


def _is_generated_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    if _GENERATED_WRAPPER_RE.search(node.name):
        return True
    body = _strip_docstring(node.body)
    if len(body) != 1:
        return False
    statement = body[0]
    call = statement.value if isinstance(statement, (ast.Return, ast.Expr)) else None
    if not isinstance(call, ast.Call):
        return False
    callee = _callee_name(call.func).casefold()
    return callee.startswith("_build_") and callee.endswith("_stage")


def _local_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names = {arg.arg for arg in (*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs)}
    if node.args.vararg:
        names.add(node.args.vararg.arg)
    if node.args.kwarg:
        names.add(node.args.kwarg.arg)
    for child in ast.walk(node):
        if child is node:
            continue
        if isinstance(child, ast.Name) and isinstance(child.ctx, (ast.Store, ast.Del)):
            names.add(child.id)
        elif isinstance(child, ast.ExceptHandler) and child.name:
            names.add(str(child.name))
        elif isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(child.name)
    return names


def _loaded_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    local = _local_names(node)
    return {
        child.id
        for child in ast.walk(node)
        if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load) and child.id not in local
    }


def _called_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    return {
        _callee_name(child.func).split(".")[-1]
        for child in ast.walk(node)
        if isinstance(child, ast.Call) and _callee_name(child.func)
    }


def _protected_boundary(name: str, node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    if _identifier_is_protected(name):
        return True
    return any(_identifier_is_protected(callee) for callee in _called_names(node))


def _module_name_from_path(path: str) -> str:
    value = str(path or "").replace("\\", "/")
    if value.endswith("/__init__.py"):
        value = value[:-12]
    elif value.endswith(".py"):
        value = value[:-3]
    return value.replace("/", ".").strip(".")


def _attribute_chain(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = _attribute_chain(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    return ""


def _test_paths(source_root: Path) -> list[Path]:
    paths: list[Path] = []
    tools = source_root / "tools"
    if tools.is_dir():
        paths.extend(path for path in tools.glob("*_tests.py") if path.is_file())
        paths.extend(path for path in tools.glob("test_*.py") if path.is_file())
    paths.extend(path for path in source_root.glob("test_*.py") if path.is_file())
    return sorted(dict.fromkeys(paths), key=lambda path: path.as_posix().casefold())


def _parse_import_alias_list(value: str) -> list[tuple[str, str | None]]:
    cleaned = value.strip().strip("()").replace("\n", " ")
    rows: list[tuple[str, str | None]] = []
    for piece in cleaned.split(","):
        token = piece.strip()
        if not token or token == "*":
            continue
        match = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_\.]*)(?:\s+as\s+([A-Za-z_][A-Za-z0-9_]*))?", token)
        if match:
            rows.append((match.group(1), match.group(2)))
    return rows


def _analyze_test_file(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    raw_digest = hashlib.sha256(raw).hexdigest()
    cache_key = (str(path.resolve()), raw_digest)
    cached = _TEST_ANALYSIS_CACHE.get(cache_key)
    if cached is not None:
        return cached
    text = raw.decode("utf-8", errors="replace")
    imports: list[tuple[str, str | None]] = []
    from_imports: list[tuple[str, str, str | None]] = []
    spans: list[tuple[int, int]] = []
    for match in _SIMPLE_IMPORT_RE.finditer(text):
        spans.append(match.span())
        imports.extend(_parse_import_alias_list(match.group(1)))
    for match in _FROM_IMPORT_RE.finditer(text):
        spans.append(match.span())
        module = match.group(1)
        from_imports.extend((module, name, alias) for name, alias in _parse_import_alias_list(match.group(2)))
    # Imports establish attribution but are not themselves counted as coverage.
    body_parts: list[str] = []
    cursor = 0
    for begin, end in sorted(spans):
        if begin < cursor:
            continue
        body_parts.append(text[cursor:begin])
        body_parts.append(" " * (end - begin))
        cursor = end
    body_parts.append(text[cursor:])
    body = "".join(body_parts)
    loaded_names = Counter(_IDENTIFIER_RE.findall(body))
    attribute_chains = Counter(_ATTRIBUTE_CHAIN_RE.findall(body))
    # Cache only structural identifiers/counts. Never retain source bytes, text, or AST nodes.
    analysis = {
        "imports": tuple(imports),
        "from_imports": tuple(from_imports),
        "loaded_names": dict(loaded_names),
        "attribute_chains": dict(attribute_chains),
    }
    if len(_TEST_ANALYSIS_CACHE) >= _FILE_CACHE_LIMIT:
        _TEST_ANALYSIS_CACHE.clear()
    _TEST_ANALYSIS_CACHE[cache_key] = analysis
    return analysis

def _test_reference_index(source_root: Path, module_symbols: Mapping[str, set[str]]) -> dict[tuple[str, str], dict[str, int]]:
    """Conservatively attribute test references to an imported source module and symbol.

    Bare same-name identifiers in unrelated tests are intentionally not evidence.
    """
    known_modules = set(module_symbols)
    leaf_modules: defaultdict[str, set[str]] = defaultdict(set)
    for module_name in known_modules:
        leaf_modules[module_name.rsplit(".", 1)[-1]].add(module_name)
    counts: Counter[tuple[str, str]] = Counter()
    files: defaultdict[tuple[str, str], set[str]] = defaultdict(set)
    for path in _test_paths(source_root):
        try:
            analysis = _analyze_test_file(path)
        except (OSError, SyntaxError, ValueError, UnicodeError):
            continue
        direct_symbols: dict[str, tuple[str, str]] = {}
        module_aliases: dict[str, str] = {}
        explicitly_imported_modules: set[str] = set()
        for imported_name, asname in analysis.get("imports") or ():
            if imported_name in known_modules:
                explicitly_imported_modules.add(imported_name)
                if asname:
                    module_aliases[str(asname)] = str(imported_name)
        for base, imported_name, asname in analysis.get("from_imports") or ():
            if base in known_modules and imported_name != "*":
                if imported_name in module_symbols.get(base, set()):
                    direct_symbols[str(asname or imported_name)] = (str(base), str(imported_name))
            possible = f"{base}.{imported_name}"
            if possible in known_modules:
                module_aliases[str(asname or imported_name)] = possible
                explicitly_imported_modules.add(possible)
            # Support the project's common sys.path style: from self_maintenance import foo.
            if base not in known_modules and base in leaf_modules and len(leaf_modules[base]) == 1:
                resolved = next(iter(leaf_modules[base]))
                if imported_name in module_symbols.get(resolved, set()):
                    direct_symbols[str(asname or imported_name)] = (resolved, str(imported_name))
        relative = _safe_relative(path, source_root)
        seen: set[tuple[str, str]] = set()
        for alias, count in dict(analysis.get("loaded_names") or {}).items():
            key = direct_symbols.get(str(alias))
            if key is not None:
                counts[key] += int(count)
                seen.add(key)
        for chain, count in dict(analysis.get("attribute_chains") or {}).items():
            parts = str(chain).split(".")
            if len(parts) < 2:
                continue
            key: tuple[str, str] | None = None
            alias_module = module_aliases.get(parts[0])
            if alias_module and len(parts) == 2 and parts[-1] in module_symbols.get(alias_module, set()):
                key = (alias_module, parts[-1])
            else:
                prefix = ".".join(parts[:-1])
                if prefix in explicitly_imported_modules and parts[-1] in module_symbols.get(prefix, set()):
                    key = (prefix, parts[-1])
            if key is not None:
                counts[key] += int(count)
                seen.add(key)
        for key in seen:
            files[key].add(relative)
    return {
        key: {"reference_count": int(count), "file_count": len(files[key])}
        for key, count in counts.items()
    }

def _top_level_names(tree: ast.Module) -> set[str]:
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(node, ast.Import):
            names.update(alias.asname or alias.name.split(".", 1)[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            names.update(alias.asname or alias.name for alias in node.names if alias.name != "*")
    return names


def _module_analysis(path: Path, source_root: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    raw_digest = hashlib.sha256(raw).hexdigest()
    cache_key = (str(path.resolve()), raw_digest)
    cached = _MODULE_ANALYSIS_CACHE.get(cache_key)
    if cached is not None:
        return cached
    text = raw.decode("utf-8", errors="replace")
    tree = ast.parse(text, filename=str(path))
    source_lines = text.splitlines(keepends=True)
    top_names = _top_level_names(tree)
    funcs = [node for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]
    classes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
    symbols: list[dict[str, Any]] = []
    dependency_symbols: dict[str, dict[str, Any]] = {}
    previous_end = 0
    for index, node in enumerate(funcs):
        segment = "".join(source_lines[int(node.lineno) - 1:int(node.end_lineno or node.lineno)])
        loaded_names = _loaded_names(node)
        called_names = _called_names(node)
        protected = _protected_boundary(node.name, node)
        symbol = {
            "name": node.name,
            "kind": "async_function" if isinstance(node, ast.AsyncFunctionDef) else "function",
            "line": int(node.lineno),
            "end_line": int(node.end_lineno or node.lineno),
            "span_lines": int((node.end_lineno or node.lineno) - node.lineno + 1),
            "adjacent_gap_from_previous": int(node.lineno - previous_end - 1) if previous_end else None,
            "source_digest": hashlib.sha256(segment.encode("utf-8")).hexdigest(),
            "test_reference_count": 0,
            "test_reference_file_count": 0,
            "retained_extraction_wrapper": _is_retained_extraction_wrapper(node),
            "dependency_factory": _is_dependency_factory(node.name),
            "generated_wrapper": _is_generated_wrapper(node),
            "protected_authority_boundary": protected,
            "family_tokens": _snake_tokens(node.name),
            "source_order": index,
        }
        symbols.append(symbol)
        dependency_symbols[node.name] = {
            "loaded_names": frozenset(loaded_names),
            "called_names": frozenset(called_names),
            "protected_authority_boundary": protected,
        }
        previous_end = int(node.end_lineno or node.lineno)
    relative = _safe_relative(path, source_root)
    analysis = {
        "inventory": {
            "module": relative,
            "module_size_bytes": len(raw),
            "line_count": len(text.splitlines()),
            "top_level_symbol_count": len(funcs) + len(classes),
            "top_level_function_count": len(funcs),
            "top_level_class_count": len(classes),
            # Raw-byte digest is authoritative for source immutability on LF and CRLF trees.
            "module_digest": hashlib.sha256(raw).hexdigest(),
            "symbols": symbols,
            "content_free": True,
        },
        "dependency_index": {
            "symbols": dependency_symbols,
            "top_names": frozenset(top_names),
        },
    }
    if len(_MODULE_ANALYSIS_CACHE) >= _FILE_CACHE_LIMIT:
        _MODULE_ANALYSIS_CACHE.clear()
    _MODULE_ANALYSIS_CACHE[cache_key] = analysis
    return analysis


def _module_inventory(path: Path, source_root: Path) -> dict[str, Any]:
    return copy.deepcopy(_module_analysis(path, source_root)["inventory"])


def verify_inventory_source_unchanged(source_root: str | Path, inventory: Mapping[str, Any]) -> bool:
    """Verify an existing inventory against raw source bytes without newline normalization."""
    root = Path(source_root).expanduser().resolve()
    expected_modules = list(inventory.get("modules") or [])
    expected_paths = {str(row.get("module") or "") for row in expected_modules}
    current_paths = {
        _safe_relative(path, root)
        for path in (root / "conscious_agent").rglob("*.py")
        if path.is_file() and not any(part in {"__pycache__", "data", ".git", ".venv", "venv"} for part in path.relative_to(root).parts)
    }
    if current_paths != expected_paths:
        return False
    for module in expected_modules:
        path = root / str(module.get("module") or "")
        try:
            raw_digest = hashlib.sha256(path.read_bytes()).hexdigest()
        except OSError:
            return False
        if raw_digest != str(module.get("module_digest") or ""):
            return False
    return True

def build_python_ast_inventory(source_root: str | Path) -> dict[str, Any]:
    """Build a deterministic, read-only AST inventory of source modules and symbols."""
    root = Path(source_root).expanduser().resolve()
    agent_root = root / "conscious_agent"
    if not agent_root.is_dir():
        raise ValueError("dynamic_discovery_conscious_agent_root_missing")
    modules: list[dict[str, Any]] = []
    parse_failures: list[dict[str, Any]] = []
    for path in sorted(agent_root.rglob("*.py"), key=lambda p: p.as_posix().casefold()):
        relative_parts = path.relative_to(root).parts
        if any(part in {"__pycache__", "data", ".git", ".venv", "venv"} for part in relative_parts):
            continue
        try:
            modules.append(_module_inventory(path, root))
        except (OSError, SyntaxError, ValueError) as exc:
            parse_failures.append({
                "module": _safe_relative(path, root),
                "error_class": type(exc).__name__,
                "error_digest": _digest({"module": _safe_relative(path, root), "error_class": type(exc).__name__}),
            })
    if not modules:
        raise ValueError("dynamic_discovery_python_inventory_empty")
    module_symbols = {
        _module_name_from_path(str(module["module"])): {str(symbol["name"]) for symbol in module["symbols"]}
        for module in modules
    }
    test_refs = _test_reference_index(root, module_symbols)
    for module in modules:
        module_name = _module_name_from_path(str(module["module"]))
        for symbol in module["symbols"]:
            refs = test_refs.get((module_name, str(symbol["name"]))) or {}
            symbol["test_reference_count"] = int(refs.get("reference_count") or 0)
            symbol["test_reference_file_count"] = int(refs.get("file_count") or 0)
    summary = {
        "schema_version": DISCOVERY_SCHEMA_VERSION,
        "module_count": len(modules),
        "symbol_count": sum(int(row["top_level_symbol_count"]) for row in modules),
        "function_count": sum(int(row["top_level_function_count"]) for row in modules),
        "parse_failure_count": len(parse_failures),
        "modules": modules,
        "parse_failures": parse_failures,
        "provider_contacted": False,
        "source_modified": False,
        "runtime_modified": False,
        "content_free": True,
    }
    summary["inventory_digest"] = _digest({
        "schema_version": DISCOVERY_SCHEMA_VERSION,
        "modules": [
            {
                "module": row["module"],
                "module_digest": row["module_digest"],
                "symbol_spans": [(s["name"], s["line"], s["end_line"]) for s in row["symbols"]],
            }
            for row in modules
        ],
        "parse_failures": parse_failures,
    })
    return summary


def _module_dependency_index(root: Path, module_path: str) -> dict[str, Any]:
    path = root / module_path
    return dict(_module_analysis(path, root)["dependency_index"])


def _family_dependency_evidence(
    root: Path,
    module_path: str,
    selected_names: Sequence[str],
    *,
    dependency_index: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    index = dict(dependency_index or _module_dependency_index(root, module_path))
    symbol_index = dict(index.get("symbols") or {})
    top_names = set(index.get("top_names") or set())
    selected = set(selected_names)
    closure: set[str] = set()
    frontier = list(selected)
    visited: set[str] = set()
    external: set[str] = set()
    injected: set[str] = set()
    portable_imports = {"json", "Path", "Any"}
    protected = False
    while frontier:
        name = frontier.pop()
        if name in visited:
            continue
        visited.add(name)
        evidence = dict(symbol_index.get(name) or {})
        if not evidence:
            continue
        if name in selected and bool(evidence.get("protected_authority_boundary")):
            protected = True
        loaded = set(evidence.get("loaded_names") or ())
        injected.update(
            dependency
            for dependency in loaded
            if dependency not in selected
            and dependency not in portable_imports
            and dependency not in dir(builtins)
        )
        for dependency in loaded:
            if dependency in symbol_index and dependency not in selected:
                if dependency not in closure:
                    closure.add(dependency)
                    frontier.append(dependency)
            elif dependency not in top_names and dependency not in dir(builtins):
                external.add(dependency)
    return {
        "local_dependency_closure": sorted(closure),
        "local_dependency_closure_count": len(closure),
        "external_dependency_names": sorted(external),
        "external_dependency_count": len(external),
        "injected_dependency_names": sorted(injected),
        "injected_dependency_count": len(injected),
        "protected_authority_boundary": protected,
    }

def _destination_for_family(module_path: str, common_tokens: Sequence[str]) -> str:
    stem = Path(module_path).stem
    suffix = "_".join(common_tokens[:3]) if common_tokens else "extracted_family"
    if stem.endswith(f"_{suffix}") or stem == suffix:
        suffix = f"{suffix}_helpers"
    return f"conscious_agent/{stem}_{suffix}.py"


def _lineage_sets(completed_lineages: Iterable[Mapping[str, Any]] | None) -> tuple[set[str], set[str], set[str]]:
    destinations: set[str] = set()
    symbols: set[str] = set()
    digests: set[str] = set()
    for raw in completed_lineages or ():
        row = dict(raw or {})
        for key in ("destination_module", "new_module"):
            value = str(row.get(key) or "").strip().replace("\\", "/")
            if value:
                destinations.add(value)
        for value in row.get("changed_files") or []:
            path = str(value or "").strip().replace("\\", "/")
            if path.startswith("conscious_agent/") and path.endswith(".py"):
                destinations.add(path)
        for value in row.get("source_symbols") or row.get("selected_symbols") or []:
            if value:
                symbols.add(str(value))
        for key in ("candidate_id", "evidence_digest", "implementation_result_digest", "proposal_digest"):
            value = str(row.get(key) or "")
            if value:
                digests.add(value)
    return destinations, symbols, digests


def _candidate_from_family(
    root: Path,
    module: Mapping[str, Any],
    family: Sequence[Mapping[str, Any]],
    *,
    completed_destinations: set[str],
    completed_symbols: set[str],
    completed_digests: set[str],
    dependency_index: Mapping[str, Any],
) -> dict[str, Any]:
    names = [str(row["name"]) for row in family]
    token_sets = [set(row.get("family_tokens") or []) for row in family]
    common = set.intersection(*token_sets) if token_sets else set()
    first_tokens = list(family[0].get("family_tokens") or []) if family else []
    common_ordered = [token for token in first_tokens if token in common]
    dependency_evidence = _family_dependency_evidence(root, str(module["module"]), names, dependency_index=dependency_index)
    local_closure = set(dependency_evidence["local_dependency_closure"])
    external_dependencies = set(dependency_evidence["external_dependency_names"])
    injected_dependencies = set(dependency_evidence["injected_dependency_names"])
    estimated_dependency_count = len(injected_dependencies)
    destination = _destination_for_family(str(module["module"]), common_ordered)
    source_span = int(family[-1]["end_line"]) - int(family[0]["line"]) + 1
    test_reference_count = sum(int(row.get("test_reference_count") or 0) for row in family)
    test_reference_file_count = max((int(row.get("test_reference_file_count") or 0) for row in family), default=0)
    evidence_core = {
        "module": module["module"],
        "module_digest": module["module_digest"],
        "source_symbols": names,
        "symbol_spans": [(row["name"], row["line"], row["end_line"]) for row in family],
        "symbol_digests": [row["source_digest"] for row in family],
        "adjacency_gaps": [row["adjacent_gap_from_previous"] for row in family[1:]],
        "dependency_closure": sorted(local_closure),
        "external_dependency_count": len(external_dependencies),
        "test_reference_count": test_reference_count,
        "test_reference_file_count": test_reference_file_count,
        "destination_module": destination,
    }
    evidence_digest = _digest(evidence_core)
    rejection_codes: list[str] = []
    if not common_ordered:
        rejection_codes.append("ambiguous_family_no_shared_descriptive_token")
    if len(family) > MAX_FAMILY_SYMBOLS:
        rejection_codes.append("family_too_broad_symbol_count")
    if source_span > MAX_FAMILY_SPAN_LINES:
        rejection_codes.append("family_too_broad_line_span")
    if estimated_dependency_count > min(MAX_ESTIMATED_DEPENDENCIES, MAX_EXTERNAL_DEPENDENCIES):
        rejection_codes.append("excessive_dependency_closure")
    if dependency_evidence["protected_authority_boundary"] or any(bool(row.get("protected_authority_boundary")) for row in family):
        rejection_codes.append("protected_authority_boundary")
    if any(bool(row.get("retained_extraction_wrapper")) for row in family):
        rejection_codes.append("retained_extraction_wrapper")
    if any(bool(row.get("dependency_factory")) for row in family):
        rejection_codes.append("dependency_factory")
    if any(bool(row.get("generated_wrapper")) for row in family):
        rejection_codes.append("generated_wrapper")
    if (root / destination).exists():
        rejection_codes.append("destination_module_already_exists")
    if destination in completed_destinations or any(name in completed_symbols for name in names):
        rejection_codes.append("completed_proposal_lineage")
    if evidence_digest in completed_digests:
        rejection_codes.append("completed_proposal_evidence_digest")
    if test_reference_file_count <= 0:
        rejection_codes.append("insufficient_existing_test_reference")

    eligible = not rejection_codes
    candidate_id = f"discovery-{evidence_digest[:20]}"
    return {
        "candidate_id": candidate_id,
        "evidence_digest": evidence_digest,
        "source_module": module["module"],
        "source_symbols": names,
        "symbol_spans": evidence_core["symbol_spans"],
        "adjacency_gaps": evidence_core["adjacency_gaps"],
        "proposed_destination_module": destination,
        "estimated_dependency_count": estimated_dependency_count,
        "local_dependency_closure_count": len(local_closure),
        "external_dependency_count": len(external_dependencies),
        "injected_dependency_count": len(injected_dependencies),
        "existing_test_reference_count": test_reference_count,
        "existing_test_reference_file_count": test_reference_file_count,
        "reversibility_classification": "bounded_new_module_retained_wrapper_candidate" if eligible else "not_eligible_for_planning",
        "eligible_for_later_planning": eligible,
        "eligibility_reason": (
            "bounded_adjacent_family_with_existing_test_reference"
            if eligible else ";".join(sorted(set(rejection_codes)))
        ),
        "rejection_codes": sorted(set(rejection_codes)),
        "ranking_score": None,
        "selected": False,
        "provider_contacted": False,
        "source_modified": False,
        "content_free": True,
    }


def _discover_module_families(
    root: Path,
    module: Mapping[str, Any],
    *,
    completed_destinations: set[str],
    completed_symbols: set[str],
    completed_digests: set[str],
) -> list[dict[str, Any]]:
    functions = list(module.get("symbols") or [])
    rows: list[dict[str, Any]] = []
    dependency_index: dict[str, Any] | None = None
    i = 0
    while i < len(functions) - 1:
        first = functions[i]
        if first.get("retained_extraction_wrapper") or first.get("dependency_factory") or first.get("generated_wrapper"):
            i += 1
            continue
        family = [first]
        common = set(first.get("family_tokens") or [])
        j = i + 1
        while j < len(functions) and len(family) < MAX_FAMILY_SYMBOLS + 1:
            current = functions[j]
            previous = family[-1]
            gap = int(current["line"]) - int(previous["end_line"]) - 1
            next_common = common & set(current.get("family_tokens") or [])
            if gap > MAX_ADJACENCY_GAP or not next_common:
                break
            family.append(current)
            common = next_common
            j += 1
        if len(family) >= 2:
            if dependency_index is None:
                dependency_index = _module_dependency_index(root, str(module["module"]))
            rows.append(_candidate_from_family(
                root,
                module,
                family,
                completed_destinations=completed_destinations,
                completed_symbols=completed_symbols,
                completed_digests=completed_digests,
                dependency_index=dependency_index,
            ))
            i = j
        else:
            i += 1
    return rows


def clear_dynamic_discovery_caches() -> None:
    """Clear process-local read-only discovery indexes; primarily useful for cold benchmarks."""
    _DISCOVERY_CACHE.clear()
    _LAST_SOURCE_SHAPE.clear()
    _MODULE_ANALYSIS_CACHE.clear()
    _TEST_ANALYSIS_CACHE.clear()


def build_dynamic_improvement_discovery(
    source_root: str | Path,
    *,
    completed_lineages: Iterable[Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    """Describe credible structural opportunities without selecting or mutating anything."""
    started = time.perf_counter()
    root = Path(source_root).expanduser().resolve()
    lineage_rows = [dict(row or {}) for row in completed_lineages or ()]
    source_shape = _source_shape_fingerprint(root)
    root_key = str(root)
    prior_shape = _LAST_SOURCE_SHAPE.get(root_key)
    cache_key = _digest({
        "schema_version": DISCOVERY_SCHEMA_VERSION,
        "source_shape": source_shape,
        "completed_lineages": lineage_rows,
    })
    cached = _DISCOVERY_CACHE.get(cache_key) if prior_shape == source_shape else None
    _LAST_SOURCE_SHAPE[root_key] = source_shape
    if cached is not None:
        restored = copy.deepcopy(cached)
        restored["cache_hit"] = True
        restored["discovery_elapsed_ms"] = round((time.perf_counter() - started) * 1000.0, 3)
        return restored
    inventory = build_python_ast_inventory(root)
    completed_destinations, completed_symbols, completed_digests = _lineage_sets(lineage_rows)
    discovered: list[dict[str, Any]] = []
    for module in inventory["modules"]:
        discovered.extend(_discover_module_families(
            root,
            module,
            completed_destinations=completed_destinations,
            completed_symbols=completed_symbols,
            completed_digests=completed_digests,
        ))
    discovered.sort(key=lambda row: (str(row["source_module"]), int(row["symbol_spans"][0][1]), str(row["candidate_id"])))
    eligible = [row for row in discovered if row["eligible_for_later_planning"]]
    rejected = [row for row in discovered if not row["eligible_for_later_planning"]]
    focus_module = "conscious_agent/self_maintenance.py"
    focus_candidates = [row for row in eligible if row["source_module"] == focus_module]
    focus_rejections = [row for row in rejected if row["source_module"] == focus_module]
    focus_inventory = next((row for row in inventory["modules"] if row["module"] == focus_module), None)
    all_symbols = [symbol for module in inventory["modules"] for symbol in module.get("symbols") or []]
    symbol_exclusion_counts = {
        "retained_extraction_wrapper": sum(bool(item.get("retained_extraction_wrapper")) for item in all_symbols),
        "dependency_factory": sum(bool(item.get("dependency_factory")) for item in all_symbols),
        "generated_wrapper": sum(bool(item.get("generated_wrapper")) for item in all_symbols),
        "protected_authority_name": sum(bool(item.get("protected_authority_boundary")) for item in all_symbols),
    }
    source_unchanged = verify_inventory_source_unchanged(root, inventory)
    result = {
        "schema_version": DISCOVERY_SCHEMA_VERSION,
        "state": "discovery_candidates_available" if eligible else "no_qualifying_candidate",
        "inventory_digest": inventory["inventory_digest"],
        "module_count": inventory["module_count"],
        "symbol_count": inventory["symbol_count"],
        "parse_failure_count": inventory["parse_failure_count"],
        "eligible_candidate_count": len(eligible),
        "rejected_candidate_count": len(rejected),
        "candidate_count_returned": min(len(eligible), MAX_PUBLIC_CANDIDATES),
        "rejection_count_returned": min(len(rejected), MAX_PUBLIC_REJECTIONS),
        "candidates_truncated": len(eligible) > MAX_PUBLIC_CANDIDATES,
        "rejections_truncated": len(rejected) > MAX_PUBLIC_REJECTIONS,
        "candidates": eligible[:MAX_PUBLIC_CANDIDATES],
        "rejected_candidates": rejected[:MAX_PUBLIC_REJECTIONS],
        "focus_module": focus_module,
        "focus_module_summary": {
            "module": focus_module,
            "module_size_bytes": int((focus_inventory or {}).get("module_size_bytes") or 0),
            "line_count": int((focus_inventory or {}).get("line_count") or 0),
            "top_level_symbol_count": int((focus_inventory or {}).get("top_level_symbol_count") or 0),
            "retained_extraction_wrapper_count": sum(bool(item.get("retained_extraction_wrapper")) for item in (focus_inventory or {}).get("symbols") or []),
            "dependency_factory_count": sum(bool(item.get("dependency_factory")) for item in (focus_inventory or {}).get("symbols") or []),
        },
        "focus_candidates": focus_candidates[:8],
        "focus_rejections": focus_rejections[:16],
        "symbol_exclusion_counts": symbol_exclusion_counts,
        "completed_lineage_count": len(lineage_rows),
        "selection_made": False,
        "ranking_performed": False,
        "workspace_prepared": False,
        "approval_requested": False,
        "provider_contacted": False,
        "source_modified": False,
        "runtime_modified": False,
        "private_runtime_scanned": False,
        "source_unchanged": source_unchanged,
        "cache_hit": False,
        "discovery_elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
        "content_free": True,
    }
    result["discovery_digest"] = _digest({
        "schema_version": DISCOVERY_SCHEMA_VERSION,
        "inventory_digest": result["inventory_digest"],
        "candidates": [(row["candidate_id"], row["evidence_digest"]) for row in eligible],
        "rejected": [(row["candidate_id"], tuple(row["rejection_codes"])) for row in rejected],
        "completed_destinations": sorted(completed_destinations),
        "completed_symbols": sorted(completed_symbols),
    })
    if len(_DISCOVERY_CACHE) >= _DISCOVERY_CACHE_LIMIT:
        _DISCOVERY_CACHE.pop(next(iter(_DISCOVERY_CACHE)))
    _DISCOVERY_CACHE[cache_key] = copy.deepcopy(result)
    return result


def public_dynamic_discovery_projection(discovery: Mapping[str, Any]) -> dict[str, Any]:
    """Return a bounded source-metadata projection without source text or runtime data."""
    row = dict(discovery or {})
    return {
        "schema_version": row.get("schema_version"),
        "state": row.get("state"),
        "inventory_digest": row.get("inventory_digest"),
        "discovery_digest": row.get("discovery_digest"),
        "module_count": int(row.get("module_count") or 0),
        "symbol_count": int(row.get("symbol_count") or 0),
        "parse_failure_count": int(row.get("parse_failure_count") or 0),
        "eligible_candidate_count": int(row.get("eligible_candidate_count") or 0),
        "rejected_candidate_count": int(row.get("rejected_candidate_count") or 0),
        "candidates": [
            {
                "candidate_id": item.get("candidate_id"),
                "evidence_digest": item.get("evidence_digest"),
                "source_module": item.get("source_module"),
                "source_symbols": list(item.get("source_symbols") or []),
                "symbol_spans": list(item.get("symbol_spans") or []),
                "proposed_destination_module": item.get("proposed_destination_module"),
                "estimated_dependency_count": int(item.get("estimated_dependency_count") or 0),
                "existing_test_reference_count": int(item.get("existing_test_reference_count") or 0),
                "existing_test_reference_file_count": int(item.get("existing_test_reference_file_count") or 0),
                "reversibility_classification": item.get("reversibility_classification"),
                "eligible_for_later_planning": bool(item.get("eligible_for_later_planning")),
                "eligibility_reason": item.get("eligibility_reason"),
                "selected": False,
            }
            for item in row.get("candidates") or []
        ],
        "focus_module": row.get("focus_module"),
        "focus_module_summary": dict(row.get("focus_module_summary") or {}),
        "symbol_exclusion_counts": dict(row.get("symbol_exclusion_counts") or {}),
        "completed_lineage_count": int(row.get("completed_lineage_count") or 0),
        "focus_candidates": [
            {
                "candidate_id": item.get("candidate_id"),
                "evidence_digest": item.get("evidence_digest"),
                "source_module": item.get("source_module"),
                "source_symbols": list(item.get("source_symbols") or []),
                "symbol_spans": list(item.get("symbol_spans") or []),
                "proposed_destination_module": item.get("proposed_destination_module"),
                "estimated_dependency_count": int(item.get("estimated_dependency_count") or 0),
                "existing_test_reference_count": int(item.get("existing_test_reference_count") or 0),
                "existing_test_reference_file_count": int(item.get("existing_test_reference_file_count") or 0),
                "reversibility_classification": item.get("reversibility_classification"),
                "eligible_for_later_planning": bool(item.get("eligible_for_later_planning")),
                "eligibility_reason": item.get("eligibility_reason"),
                "selected": False,
            }
            for item in row.get("focus_candidates") or []
        ],
        "selection_made": False,
        "ranking_performed": False,
        "workspace_prepared": False,
        "approval_requested": False,
        "provider_contacted": False,
        "source_modified": False,
        "runtime_modified": False,
        "private_runtime_scanned": False,
        "source_unchanged": bool(row.get("source_unchanged")),
        "cache_hit": bool(row.get("cache_hit")),
        "discovery_elapsed_ms": float(row.get("discovery_elapsed_ms") or 0.0),
        "content_free": True,
    }
