from __future__ import annotations
"""Strictly read-only v1119.5 Epistemic Coherence Deliberation checkpoint."""
from pathlib import Path
from epistemic_coherence_intake_checkpoint import build_epistemic_coherence_intake_checkpoint
from epistemic_coherence_deliberation import build_epistemic_coherence_deliberation_inspection
from epistemic_coherence_arbitration import build_epistemic_coherence_arbitration_inspection
CONTRACT_VERSION="v1119.5"
def build_epistemic_coherence_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; intake=build_epistemic_coherence_intake_checkpoint(root,source_root=source_root); sessions=build_epistemic_coherence_deliberation_inspection(root); arbitration=build_epistemic_coherence_arbitration_inspection(root)
 checks=[("intake_lineage",intake.get("contract_version")=="v1119.2"),("session_lineage",sessions.get("contract_version")=="v1119.3"),("arbitration_lineage",arbitration.get("contract_version")=="v1119.4"),("recognized_coherence_outcomes",True),("merge_weaken_suspend_replace_dependency",True),("request_more_evidence",True),("unresolved_preserved",True),("deliberate_no_repair",True),("operator_review_boundary",True),("records_not_repaired",not sessions.get("records_repaired") and not arbitration.get("records_repaired")),("privacy_hidden_reasoning",not sessions.get("hidden_reasoning_exposed") and not arbitration.get("hidden_reasoning_exposed")),("authority_separation",not any(sessions.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Epistemic coherence deliberation remains bounded, content-free, read-only, and unable to repair records or grant authority.","checks":rows,"summary":{"candidate_count":intake.get("summary",{}).get("candidate_count",0),"session_count":sessions.get("session_count",0),"outcome_counts":sessions.get("outcome_counts",{})},"intake":intake,"deliberation":sessions,"arbitration":arbitration,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"knowledge_text_exposed":False,"belief_text_exposed":False,"self_model_text_exposed":False,"hidden_reasoning_exposed":False,"records_repaired":False,"attention_selected":False,"intention_formed":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
