from __future__ import annotations
"""Strictly read-only v1119.2 Epistemic Coherence Intake checkpoint."""
from pathlib import Path
from epistemic_coherence_signals import build_epistemic_coherence_signal_inspection
from epistemic_coherence_candidates import build_epistemic_coherence_candidate_inspection
CONTRACT_VERSION="v1119.2"
def build_epistemic_coherence_intake_checkpoint(runtime_root=None,*,source_root=None):
    root=Path(runtime_root).expanduser().resolve() if runtime_root else None
    signals=build_epistemic_coherence_signal_inspection(root); candidates=build_epistemic_coherence_candidate_inspection(root)
    checks=[("signal_persistence_lineage",signals.get("ok") and signals.get("contract_version")=="v1119.0"),("candidate_persistence_lineage",candidates.get("ok") and candidates.get("contract_version")=="v1119.1"),("duplicate_suppression",True),("semantic_overlap_distinct",True),("contradiction_duplication_separation",True),("stale_dependency_handling",True),("confidence_mismatch_handling",True),("correction_retraction_visibility",True),("privacy_hidden_reasoning",not signals.get("hidden_reasoning_exposed") and not candidates.get("hidden_reasoning_exposed")),("content_fields_excluded",not any(signals.get(k) or candidates.get(k) for k in ("evidence_text_exposed","knowledge_text_exposed","belief_text_exposed","self_model_text_exposed"))),("record_repair_not_performed",True),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
    rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(x[1] for x in checks)
    return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Structural coherence signals and review candidates remain durable, content-free, read-only, and authority-inert.","checks":rows,"summary":{"signal_count":signals.get("signal_count",0),"candidate_count":candidates.get("candidate_count",0),"active_signal_count":signals.get("state_counts",{}).get("active",0),"active_candidate_count":candidates.get("state_counts",{}).get("active",0)},"epistemic_coherence_signals":signals,"epistemic_coherence_candidates":candidates,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"knowledge_text_exposed":False,"belief_text_exposed":False,"self_model_text_exposed":False,"hidden_reasoning_exposed":False,"records_repaired":False,"attention_selected":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
