from __future__ import annotations
"""Strictly read-only v1130.2 Genuine Inquiry Intake checkpoint."""
import hashlib, os
from pathlib import Path
from genuine_inquiry_eligibility_signals import build_genuine_inquiry_eligibility_inspection, SOURCES, PURPOSES
from genuine_inquiry_candidates import build_genuine_inquiry_candidate_inspection, STATES
CONTRACT_VERSION='v1130.2'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_genuine_inquiry_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); signals=build_genuine_inquiry_eligibility_inspection(runtime); candidates=build_genuine_inquiry_candidate_inspection(runtime)
 checks=[('signal_contract',signals.get('contract_version')=='v1130.0'),('candidate_contract',candidates.get('contract_version')=='v1130.1'),('source_categories',SOURCES=={'curiosity','uncertainty','contradiction','unfinished_thought','knowledge_gap'}),('purpose_categories',len(PURPOSES)==6),('candidate_states',{'active','suppressed','deferred','awaiting_prerequisite','requires_operator_review','merged','superseded','stale','obsolete','retracted','retired'}==STATES),('exact_origin_lineage',all(x.get('origin_ids') for x in signals.get('recent_signals',[]))),('curiosity_distinct_from_authority',all(x.get('curiosity_strength') is not None and not x.get('browse_request_id') for x in signals.get('recent_signals',[]))),('uncertainty_and_gap_distinct',all(x.get('uncertainty') is not None and x.get('knowledge_gap') is not None for x in signals.get('recent_signals',[]))),('contradiction_and_unfinished_distinct',all(x.get('contradiction_strength') is not None and x.get('unfinished_thought_strength') is not None for x in signals.get('recent_signals',[]))),('false_pressure_suppression',all(not (x.get('state')=='active' and (x.get('novelty_only') or x.get('false_urgency'))) for x in signals.get('recent_signals',[]))),('bounded_scope',all(x.get('bounded_scope_digest') is not None for x in candidates.get('recent_candidates',[]))),('recovery_and_cost',all(x.get('recovery_compatible') is not None and x.get('cognitive_cost') is not None for x in candidates.get('recent_candidates',[]))),('overlap_lineage',all(x.get('semantic_overlap_key') is not None for x in candidates.get('recent_candidates',[]))),('lifecycle_coverage',all(x.get('state') in STATES for x in candidates.get('recent_candidates',[]))),('privacy_boundary',not signals.get('raw_content_exposed') and not signals.get('question_text_exposed') and not signals.get('hidden_reasoning_exposed')),('no_browser_or_provider',not signals.get('browser_contacted') and not candidates.get('browser_contacted') and not signals.get('provider_contacted') and not candidates.get('provider_contacted')),('no_message_or_notification',not signals.get('message_sent') and not candidates.get('message_sent') and not signals.get('notification_created') and not candidates.get('notification_created')),('authority_separation',not any(signals.get('authority_boundary',{}).values()) and not any(candidates.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'signals':signals,'candidates':candidates,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'question_text_exposed':False,'reflection_text_exposed':False,'evidence_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'browser_contacted':False,'provider_contacted':False,'message_sent':False,'notification_created':False,'initiative_created':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
