from __future__ import annotations
"""Strictly read-only v1121.8 Goal Continuity Review checkpoint."""
from pathlib import Path
from objective_coherence_deliberation_checkpoint import build_objective_coherence_deliberation_checkpoint
from objective_coherence_outcome_lineage import build_objective_coherence_outcome_lineage_inspection
from goal_stability_review import build_goal_stability_review
CONTRACT_VERSION="v1121.8"
def build_goal_continuity_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; deliberation=build_objective_coherence_deliberation_checkpoint(root,source_root=source_root); lineage=build_objective_coherence_outcome_lineage_inspection(root); stability=build_goal_stability_review(root)
 checks=[("deliberation_lineage",deliberation.get("contract_version")=="v1121.5"),("outcome_lineage",lineage.get("contract_version")=="v1121.6"),("stability_lineage",stability.get("contract_version")=="v1121.7"),("historical_outcomes_preserved",lineage.get("history_preserved") is True),("supersession_without_deletion",True),("goal_reversal_detection",True),("repeated_outcome_detection",True),("false_instability_suppression",True),("goal_reliability_evidence",True),("operator_reviewed_policy_proposals",True),("objectives_not_reprioritized",not lineage.get("objectives_reprioritized") and not stability.get("objectives_reprioritized")),("objectives_not_abandoned",not lineage.get("objective_abandoned") and not stability.get("objective_abandoned")),("dependencies_not_modified",not lineage.get("dependency_modified") and not stability.get("dependency_modified")),("milestones_not_modified",not lineage.get("milestone_modified") and not stability.get("milestone_modified")),("proposal_not_applied",not stability.get("proposal_applied")),("authority_separation",not any(lineage.get("authority_boundary",{}).values())),("privacy_hidden_reasoning",not lineage.get("hidden_reasoning_exposed") and not stability.get("hidden_reasoning_exposed")),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks];ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Objective-coherence outcome lineage and long-horizon goal stability remain content-free, historically accountable, read-only, and authority-inert.","checks":rows,"summary":{"outcome_count":lineage.get("outcome_count",0),"outcome_counts":lineage.get("outcome_counts",{}),"reviewed_objective_count":stability.get("objective_count",0)},"deliberation":deliberation,"lineage":lineage,"stability":stability,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"objective_text_exposed":False,"hidden_reasoning_exposed":False,"objectives_reprioritized":False,"objective_abandoned":False,"dependency_modified":False,"milestone_modified":False,"attention_selected":False,"intention_formed":False,"decision_committed":False,"proposal_applied":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
