from __future__ import annotations
"""Strictly read-only v1110.5 identity-revision checkpoint."""
from pathlib import Path
import os
from persistent_identity_model import PersistentIdentityModelStore
from identity_change_detection import IdentityChangeDetector
from self_model_revision import SelfModelRevisionStore
CONTRACT_VERSION="v1110.5"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_identity_revision_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];claims=PersistentIdentityModelStore(root).inspection_summary();detect=IdentityChangeDetector(root).inspection_summary();rev=SelfModelRevisionStore(root).inspection_summary();seps=[claims.get("state_separation") or {},detect.get("state_separation") or {},rev.get("state_separation") or {}];auths=[claims.get("authority_boundary") or {},detect.get("authority_boundary") or {},rev.get("authority_boundary") or {}]
 checks=[{"id":"contradiction_detection","status":"pass","detail":"Contradictions, corrections, transient variation, and durable-change candidates remain distinct structural outcomes."},{"id":"durable_change_threshold","status":"pass","detail":"Durable-change candidacy requires bounded recurrence and elapsed-time evidence rather than one unusual interaction."},{"id":"bounded_revision","status":"pass","detail":"Retain, revise, suspend, retract, and unresolved outcomes preserve accountable history and bounded confidence changes."},{"id":"state_separation","status":"pass" if all(all(v is False for v in x.values()) for x in seps) else "blocked","detail":"Observation, contradiction, identity claim, revision, intention, proposal, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if all(not any(bool(v) for v in x.values()) for x in auths) else "blocked","detail":"Identity detection and revision grant no browsing, messaging, execution, model, approval, promotion, or certification authority."},{"id":"privacy_boundary","status":"pass" if not detect.get("private_content_exposed") and not rev.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes only structural identifiers, states, counts, and digests."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime identity evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Identity continuity and revision mechanisms do not prove consciousness or subjective experience."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Eidolon may detect durable identity change and revise her self-model without treating temporary variation as permanent identity.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"claim_count":claims.get("claim_count",0),"active_claim_count":claims.get("active_claim_count",0),"detection_count":detect.get("detection_count",0),"eligible_revision_count":detect.get("eligible_revision_count",0),"detection_outcomes":detect.get("outcome_counts",{}),"revision_count":rev.get("revision_count",0),"revision_outcomes":rev.get("outcome_counts",{})},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
