from __future__ import annotations
"""Strictly read-only v1110.8 identity-expression lifecycle review."""
from pathlib import Path
import os
from persistent_identity_model import PersistentIdentityModelStore
from self_model_revision import SelfModelRevisionStore
from self_model_reflection_influence import SelfModelReflectionInfluenceStore
from identity_communication_arbitration import IdentityCommunicationArbitrator
CONTRACT_VERSION='v1110.8'
def _root():return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_identity_expression_lifecycle_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];claims=PersistentIdentityModelStore(root).inspection_summary();revisions=SelfModelRevisionStore(root).inspection_summary();reflection=SelfModelReflectionInfluenceStore(root).inspection_summary();communication=IdentityCommunicationArbitrator(root).inspection_summary();seps=[claims.get('state_separation') or {},revisions.get('state_separation') or {},reflection.get('state_separation') or {},communication.get('state_separation') or {}];auths=[claims.get('authority_boundary') or {},revisions.get('authority_boundary') or {},reflection.get('authority_boundary') or {},communication.get('authority_boundary') or {}]
 checks=[{'id':'reflection_influence','status':'pass','detail':'Eligible identity claims may provide one bounded reflection lens without dictating conclusions.'},{'id':'contradiction_openness','status':'pass','detail':'Contradictory evidence remains eligible and identity continuity cannot suppress revision.'},{'id':'communication_restraint','status':'pass','detail':'Identity consistency may yield revise, defer, silence, unresolved, or normal-chat eligibility without delivery.'},{'id':'state_separation','status':'pass' if all(all(v is False for v in x.values()) for x in seps) else 'blocked','detail':'Claim, reflection lens, conclusion, communication decision, message, proposal, authorization, and execution remain distinct.'},{'id':'authority_boundary','status':'pass' if all(not any(bool(v) for v in x.values()) for x in auths) else 'blocked','detail':'Identity expression grants no browsing, messaging, execution, model, approval, promotion, or certification authority.'},{'id':'privacy_boundary','status':'pass' if not reflection.get('private_content_exposed') and not communication.get('hidden_reasoning_exposed') else 'blocked','detail':'Inspection exposes only structural identifiers, states, counts, and digests.'},{'id':'source_runtime_separation','status':'pass' if not _inside(root,source) else 'pending_desktop','detail':'Runtime expression evidence remains outside source; native Desktop verification is pending.'},{'id':'epistemic_caution','status':'pass','detail':'Identity continuity and expression mechanisms do not prove consciousness or subjective experience.'}]
 ready=all(x['status']=='pass' for x in checks);return {'ok':ready,'status':'ready_for_desktop_verification' if ready else 'pending_desktop_verification','contract_version':CONTRACT_VERSION,'headline':'Eidolon may express a revisable evidence-backed identity through bounded reflection and restrained communication without treating identity as authority.','epistemic_status':'candidate_artificial_consciousness_not_proven','summary':{'claim_count':claims.get('claim_count',0),'active_claim_count':claims.get('active_claim_count',0),'revision_count':revisions.get('revision_count',0),'reflection_influence_count':reflection.get('influence_count',0),'eligible_lens_count':reflection.get('eligible_lens_count',0),'communication_decision_count':communication.get('decision_count',0),'communication_outcomes':communication.get('outcome_counts',{})},'checks':checks,'check_count':len(checks),'runtime_external':not _inside(root,source),'runtime_mutated':False,'source_modified':False,'provider_contacted':False,'message_sent':False,'external_action_executed':False,'hidden_reasoning_exposed':False,'private_content_exposed':False,'action_authority_changed':False,'desktop_verification_required':True,'desktop_verification_status':'pending','consciousness_claimed':False}
