from __future__ import annotations
"""Strictly read-only v1108.5 initiative communication checkpoint."""
from pathlib import Path
import os
from initiative_conversation_proposal import InitiativeConversationProposalStore
from initiative_communication_restraint import InitiativeCommunicationRestraint
CONTRACT_VERSION='v1108.5'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _inside(child,parent):
 try: child.resolve().relative_to(parent.resolve()); return True
 except ValueError: return False
def build_initiative_communication_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root(); source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1]; proposals=InitiativeConversationProposalStore(root).inspection_summary(); restraint=InitiativeCommunicationRestraint(root).inspection_summary(); sep=proposals.get('state_separation') or {}; auth=restraint.get('authority_boundary') or {}
 checks=[{'id':'proposal_lineage','status':'pass','detail':'Conversation proposal candidates preserve selected initiative and intention lineage.'},{'id':'non_sending_boundary','status':'pass' if not proposals.get('message_sent') else 'blocked','detail':'Proposal formation never sends or delivers a message.'},{'id':'restraint_and_timing','status':'pass','detail':'Presence, receptivity, context, quiet, pause, sleep, cooldown, topic, sensitivity, and uncertainty boundaries are deterministic.'},{'id':'deliberate_silence','status':'pass','detail':'Deferral, abandonment, and deliberate silence remain valid outcomes.'},{'id':'state_separation','status':'pass' if all(v is False for v in sep.values()) else 'blocked','detail':'Initiative, proposal, message, authorization, and execution remain distinct.'},{'id':'authority_boundary','status':'pass' if not any(bool(v) for v in auth.values()) else 'blocked','detail':'No send, notification, browsing, execution, model, approval, promotion, or certification authority exists.'},{'id':'privacy_boundary','status':'pass' if not proposals.get('private_content_exposed') and not restraint.get('hidden_reasoning_exposed') else 'blocked','detail':'Inspection exposes structural identifiers, counts, states, and digests only.'},{'id':'source_runtime_separation','status':'pass' if not _inside(root,source) else 'pending_desktop','detail':'Runtime evidence remains outside source; native Desktop verification is pending.'},{'id':'epistemic_caution','status':'pass','detail':'Observable initiative mechanisms do not prove consciousness.'}]
 ready=all(x['status']=='pass' for x in checks); return {'ok':ready,'status':'ready_for_desktop_verification' if ready else 'pending_desktop_verification','contract_version':CONTRACT_VERSION,'headline':'Selected initiative may become a restrained normal-chat proposal without sending or acting.','epistemic_status':'candidate_artificial_consciousness_not_proven','summary':{'proposal_count':proposals.get('proposal_count',0),'active_proposal_count':proposals.get('active_proposal_count',0),'eligible_proposal_count':proposals.get('eligible_proposal_count',0),'decision_count':restraint.get('decision_count',0),'outcome_counts':restraint.get('outcome_counts',{})},'checks':checks,'check_count':len(checks),'runtime_external':not _inside(root,source),'runtime_mutated':False,'source_modified':False,'provider_contacted':False,'message_sent':False,'notification_sent':False,'external_action_executed':False,'hidden_reasoning_exposed':False,'private_content_exposed':False,'action_authority_changed':False,'desktop_verification_required':True,'desktop_verification_status':'pending','consciousness_claimed':False}
