from __future__ import annotations
"""Strictly read-only v1133.2 Internally Generated Goal intake checkpoint."""
import hashlib, os
from pathlib import Path
from internally_generated_goal_signals import build_internally_generated_goal_signal_inspection, SOURCE_CATEGORIES, PURPOSE_CATEGORIES
from internally_generated_goal_candidates import build_internally_generated_goal_candidate_inspection, STATES
CONTRACT_VERSION="v1133.2"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob("*") if x.is_file() and "__pycache__" not in x.parts and x.suffix!=".pyc"):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_internally_generated_goal_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); signals=build_internally_generated_goal_signal_inspection(runtime); candidates=build_internally_generated_goal_candidate_inspection(runtime)
 checks=[("signal_contract",signals.get("contract_version")=="v1133.0"),("candidate_contract",candidates.get("contract_version")=="v1133.1"),("source_coverage",{"motivation","inquiry_outcome","world_model_outcome","unfinished_thought"}.issubset(SOURCE_CATEGORIES)),("purpose_coverage",{"project_progress","self_understanding","deliberate_no_goal_review"}.issubset(PURPOSE_CATEGORIES)),("candidate_states",len(STATES)==11),("origin_lineage",all(x.get("origin_ids") for x in signals.get("recent_signals",[]))),("evidence_lineage",all(x.get("evidence_ids") for x in signals.get("recent_signals",[]))),("usefulness_not_urgency",all(x.get("expected_value") is not None and x.get("urgency") is not None for x in signals.get("recent_signals",[]))),("cost_visible",all(x.get("estimated_cost") is not None for x in candidates.get("recent_candidates",[]))),("time_horizon",all(x.get("time_horizons") is not None for x in candidates.get("recent_candidates",[]))),("dependencies",all(x.get("dependency_ids") is not None for x in candidates.get("recent_candidates",[]))),("false_pressure",all(x.get("false_pressure_suppressed") is not None for x in candidates.get("recent_candidates",[]))),("overlap_visible",all(x.get("semantic_overlap_key") is not None for x in candidates.get("recent_candidates",[]))),("privacy_boundary",not signals.get("raw_content_exposed") and not candidates.get("goal_text_exposed") and not signals.get("hidden_reasoning_exposed")),("no_provider",not signals.get("provider_contacted") and not candidates.get("provider_contacted")),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("read_only",rb==_sig(runtime) and sb==_sig(source))]
 return {"ok":all(v for _,v in checks),"contract_version":CONTRACT_VERSION,"checks":[{"id":k,"status":"pass" if v else "fail"} for k,v in checks],"signals":signals,"candidates":candidates,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"goal_text_exposed":False,"memory_text_exposed":False,"motivation_text_exposed":False,"prompt_exposed":False,"provider_payload_exposed":False,"hidden_reasoning_exposed":False,"provider_contacted":False,"message_sent":False,"notification_created":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification":"pending"}
