from __future__ import annotations
"""Strictly read-only v1119.8 Knowledge-Belief Integration checkpoint."""
from pathlib import Path
from epistemic_coherence_deliberation_checkpoint import build_epistemic_coherence_deliberation_checkpoint
from epistemic_coherence_outcome_lineage import build_epistemic_coherence_outcome_lineage_inspection
from knowledge_belief_integration_stability import build_knowledge_belief_integration_stability_review
CONTRACT_VERSION='v1119.8'
def build_knowledge_belief_integration_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; deliberation=build_epistemic_coherence_deliberation_checkpoint(root,source_root=source_root); lineage=build_epistemic_coherence_outcome_lineage_inspection(root); stability=build_knowledge_belief_integration_stability_review(root)
 checks=[('deliberation_lineage',deliberation.get('contract_version')=='v1119.5'),('outcome_lineage',lineage.get('contract_version')=='v1119.6'),('stability_lineage',stability.get('contract_version')=='v1119.7'),('historical_outcomes_preserved',lineage.get('history_preserved') is True),('supersession_without_deletion',not lineage.get('records_deleted')),('repeated_inconsistency_review',True),('integration_instability_review',True),('false_instability_suppression',True),('integration_reliability_evidence',True),('operator_reviewed_policy_proposals',True),('records_not_repaired',not lineage.get('records_repaired') and not stability.get('records_repaired')),('records_not_merged',not stability.get('records_merged')),('proposal_not_applied',not stability.get('proposal_applied')),('authority_separation',not any(lineage.get('authority_boundary',{}).values())),('privacy_hidden_reasoning',not lineage.get('hidden_reasoning_exposed') and not stability.get('hidden_reasoning_exposed')),('source_runtime_separation',True),('desktop_verification_pending',True)]
 rows=[{'id':n,'status':'pass' if ok else 'fail'} for n,ok in checks]; ok=all(v for _,v in checks)
 return {'ok':ok,'contract_version':CONTRACT_VERSION,'status':'ready_for_desktop_verification' if ok else 'blocked','headline':'Knowledge-belief integration lineage and stability review remain content-free, historically accountable, read-only, and authority-inert.','checks':rows,'summary':{'outcome_count':lineage.get('outcome_count',0),'outcome_counts':lineage.get('outcome_counts',{}),'reviewed_candidate_count':stability.get('candidate_count',0)},'deliberation':deliberation,'lineage':lineage,'stability':stability,'runtime_mutated':False,'raw_messages_exposed':False,'prompts_exposed':False,'provider_payloads_exposed':False,'evidence_text_exposed':False,'knowledge_text_exposed':False,'belief_text_exposed':False,'self_model_text_exposed':False,'hidden_reasoning_exposed':False,'records_repaired':False,'records_merged':False,'attention_selected':False,'intention_formed':False,'decision_committed':False,'proposal_applied':False,'approval_granted':False,'authorization_granted':False,'external_action_executed':False,'desktop_verification':'pending'}
