from __future__ import annotations
"""Strictly read-only v1109.8 long-horizon objective lifecycle review."""
from pathlib import Path
import os
from long_horizon_objective import LongHorizonObjectiveStore
from objective_milestone_decomposition import ObjectiveMilestoneStore
from objective_progress_evidence import ObjectiveProgressLedger
from objective_conflict_reconciliation import ObjectiveConflictStore
from objective_completion_abandonment import ObjectiveLifecycleStore
CONTRACT_VERSION="v1109.8"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_long_horizon_objective_lifecycle_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];o=LongHorizonObjectiveStore(root).inspection_summary();m=ObjectiveMilestoneStore(root).inspection_summary();p=ObjectiveProgressLedger(root).inspection_summary();c=ObjectiveConflictStore(root).inspection_summary();l=ObjectiveLifecycleStore(root).inspection_summary();sep={**c.get("state_separation",{}),**l.get("state_separation",{})};auth={**c.get("authority_boundary",{}),**l.get("authority_boundary",{})}
 checks=[{"id":"conflict_accountability","status":"pass","detail":"Conflict decisions preserve objective history and explicit unresolved outcomes."},{"id":"priority_no_authority","status":"pass","detail":"Priority outcomes grant no proposal, authorization, or execution authority."},{"id":"completion_evidence","status":"pass","detail":"Completion requires supported criteria evidence."},{"id":"abandonment_history","status":"pass","detail":"Abandonment and obsolescence preserve reasons, remaining milestones, and reconsideration eligibility."},{"id":"terminal_history","status":"pass","detail":"Completed, abandoned, replaced, and retired objectives remain historical records."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Objectives, reviews, completion claims, proposals, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Lifecycle review grants no external or release authority."},{"id":"privacy_boundary","status":"pass" if not c.get("private_content_exposed") and not l.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, states, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Objective lifecycle mechanisms do not prove consciousness."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Long-horizon objectives retain accountable conflict, completion, abandonment, and retirement histories.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"objective_count":o.get("objective_count",0),"milestone_count":m.get("milestone_count",0),"progress_claim_count":p.get("claim_count",0),"conflict_decision_count":c.get("decision_count",0),"lifecycle_review_count":l.get("review_count",0),"completed_count":l.get("completed_count",0),"abandoned_count":l.get("abandoned_count",0),"unresolved_count":l.get("unresolved_count",0)},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
