from __future__ import annotations
"""Strictly read-only v1109.2 long-horizon objective continuity checkpoint."""
from pathlib import Path
import os
from long_horizon_objective import LongHorizonObjectiveStore
from objective_review_arbitration import ObjectiveReviewArbitrator
CONTRACT_VERSION="v1109.2"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_long_horizon_objective_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];objectives=LongHorizonObjectiveStore(root).inspection_summary();reviews=ObjectiveReviewArbitrator(root).inspection_summary();sep=objectives.get("state_separation") or {};auth=objectives.get("authority_boundary") or {}
 checks=[{"id":"objective_persistence","status":"pass","detail":"Objectives persist with intention, agenda, reflection, success-criteria, dependency, blocker, and update lineage."},{"id":"bounded_review","status":"pass","detail":"At most one eligible objective or deliberate no-selection is recorded."},{"id":"fairness_repetition","status":"pass","detail":"Review scoring includes stagnation support and repetition penalties."},{"id":"control_boundaries","status":"pass","detail":"Quiet, sleep, pause, mode, and resource boundaries constrain review."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Attention, intention, objective, proposal, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Objectives grant no browse, send, execution, model, approval, promotion, or certification authority."},{"id":"privacy_boundary","status":"pass" if not objectives.get("private_content_exposed") and not reviews.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, states, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Long-horizon follow-through mechanisms do not prove consciousness."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Durable objectives may receive bounded internal review without becoming proposals or actions.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"objective_count":objectives.get("objective_count",0),"active_objective_count":objectives.get("active_objective_count",0),"eligible_objective_count":objectives.get("eligible_objective_count",0),"blocked_objective_count":objectives.get("blocked_objective_count",0),"review_selection_count":reviews.get("selection_count",0),"deliberate_no_selection_count":reviews.get("deliberate_no_selection_count",0)},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
