from __future__ import annotations
"""Strictly read-only v1122.5 Motivational Drive Deliberation checkpoint."""
from pathlib import Path
from motivational_continuity_intake_checkpoint import build_motivational_continuity_intake_checkpoint
from motivational_drive_deliberation import build_motivational_drive_deliberation_inspection
from motivational_drive_arbitration import build_motivational_drive_arbitration_inspection
CONTRACT_VERSION="v1122.5"
def build_motivational_drive_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; intake=build_motivational_continuity_intake_checkpoint(root,source_root=source_root); sessions=build_motivational_drive_deliberation_inspection(root); arbitration=build_motivational_drive_arbitration_inspection(root)
 checks=[("intake_lineage",intake.get("contract_version")=="v1122.2"),("session_lineage",sessions.get("contract_version")=="v1122.3"),("arbitration_lineage",arbitration.get("contract_version")=="v1122.4"),("recognized_outcomes",True),("durable_drive_review_candidate_only",True),("transient_urgency_decay_only",True),("overlap_merge_candidate_only",True),("recovery_deferral_only",True),("deliberate_non_selection",True),("unresolved_preserved",True),("operator_review_boundary",True),("attention_not_selected",not sessions.get("attention_selected") and not arbitration.get("attention_selected")),("initiative_not_created",not sessions.get("initiative_created") and not arbitration.get("initiative_created")),("communication_not_initiated",not sessions.get("message_sent") and not arbitration.get("message_sent")),("privacy_hidden_reasoning",not sessions.get("hidden_reasoning_exposed") and not arbitration.get("hidden_reasoning_exposed")),("authority_separation",not any(sessions.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Motivational-drive deliberation remains bounded, content-free, read-only, and unable to select attention, create initiative, or communicate.","checks":rows,"summary":{"candidate_count":intake.get("summary",{}).get("candidate_count",0),"session_count":sessions.get("session_count",0),"outcome_counts":sessions.get("outcome_counts",{})},"intake":intake,"deliberation":sessions,"arbitration":arbitration,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"motivation_text_exposed":False,"hidden_reasoning_exposed":False,"attention_selected":False,"initiative_created":False,"message_sent":False,"notification_created":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"provider_contacted":False,"browsing_performed":False,"desktop_verification":"pending"}
