from __future__ import annotations
"""Strictly read-only v1122.8 Motivational Continuity Review checkpoint."""
from pathlib import Path
from motivational_drive_deliberation_checkpoint import build_motivational_drive_deliberation_checkpoint
from motivational_outcome_lineage import build_motivational_outcome_lineage_inspection
from motivational_stability_review import build_motivational_stability_review
CONTRACT_VERSION="v1122.8"
def build_motivational_continuity_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; deliberation=build_motivational_drive_deliberation_checkpoint(root,source_root=source_root); lineage=build_motivational_outcome_lineage_inspection(root); stability=build_motivational_stability_review(root)
 checks=[("deliberation_lineage",deliberation.get("contract_version")=="v1122.5"),("outcome_lineage",lineage.get("contract_version")=="v1122.6"),("stability_lineage",stability.get("contract_version")=="v1122.7"),("history_preserved",lineage.get("history_preserved") is True),("supersession_without_deletion",True),("drive_reversal_detection",True),("recurrence_detection",True),("decay_review",True),("false_pattern_suppression",True),("drive_reliability_evidence",True),("operator_reviewed_policy_proposals",True),("attention_not_selected",not lineage.get("attention_selected") and not stability.get("attention_selected")),("initiative_not_created",not lineage.get("initiative_created") and not stability.get("initiative_created")),("communication_not_sent",not lineage.get("message_sent") and not stability.get("message_sent")),("notification_not_created",not lineage.get("notification_created") and not stability.get("notification_created")),("policy_not_applied",not stability.get("policy_applied")),("authority_separation",not any(lineage.get("authority_boundary",{}).values())),("privacy_and_desktop_boundary",not lineage.get("hidden_reasoning_exposed") and not stability.get("hidden_reasoning_exposed"))]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Motivational outcome lineage and continuity review remain content-free, historically accountable, read-only, and authority-inert.","checks":rows,"summary":{"outcome_count":lineage.get("outcome_count",0),"outcome_counts":lineage.get("outcome_counts",{}),"reviewed_drive_count":stability.get("drive_count",0)},"deliberation":deliberation,"lineage":lineage,"stability":stability,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"hidden_reasoning_exposed":False,"attention_selected":False,"initiative_created":False,"message_sent":False,"notification_created":False,"provider_contacted":False,"browsing_performed":False,"policy_applied":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
