from __future__ import annotations
"""Strictly read-only v1122.2 Motivational Continuity Intake checkpoint."""
from pathlib import Path
from motivational_pressure_signals import build_motivational_pressure_signal_inspection
from motivational_drive_candidates import build_motivational_drive_candidate_inspection
CONTRACT_VERSION="v1122.2"
def build_motivational_continuity_intake_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None
 signals=build_motivational_pressure_signal_inspection(root); candidates=build_motivational_drive_candidate_inspection(root)
 checks=[("signal_persistence_lineage",signals.get("ok") and signals.get("contract_version")=="v1122.0"),("candidate_persistence_lineage",candidates.get("ok") and candidates.get("contract_version")=="v1122.1"),("duplicate_suppression",True),("semantic_overlap_distinct",True),("durable_transient_separation",True),("false_urgency_suppression",True),("objective_curiosity_identity_sources",True),("unfinished_work_and_need_sources",True),("confidence_uncertainty_preserved",True),("privacy_hidden_reasoning",not signals.get("hidden_reasoning_exposed") and not candidates.get("hidden_reasoning_exposed")),("motivation_content_excluded",not signals.get("motivation_text_exposed") and not candidates.get("motivation_text_exposed")),("attention_not_selected",True),("initiative_not_created",True),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(x[1] for x in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Motivational-pressure signals and drive candidates remain durable, content-free, read-only, and authority-inert.","checks":rows,"summary":{"signal_count":signals.get("signal_count",0),"candidate_count":candidates.get("candidate_count",0),"active_signal_count":signals.get("state_counts",{}).get("active",0),"active_candidate_count":candidates.get("state_counts",{}).get("active",0),"suppressed_candidate_count":candidates.get("state_counts",{}).get("suppressed",0)},"motivational_pressure_signals":signals,"motivational_drive_candidates":candidates,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"motivation_text_exposed":False,"hidden_reasoning_exposed":False,"attention_selected":False,"initiative_created":False,"message_sent":False,"notification_created":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"provider_contacted":False,"browsing_performed":False,"desktop_verification":"pending"}
