from __future__ import annotations
"""Strictly read-only v1121.5 Goal Coherence Deliberation checkpoint."""
from pathlib import Path
from objective_coherence_intake_checkpoint import build_objective_coherence_intake_checkpoint
from objective_coherence_deliberation import build_objective_coherence_deliberation_inspection
from objective_coherence_arbitration import build_objective_coherence_arbitration_inspection
CONTRACT_VERSION="v1121.5"
def build_objective_coherence_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; intake=build_objective_coherence_intake_checkpoint(root,source_root=source_root); sessions=build_objective_coherence_deliberation_inspection(root); arbitration=build_objective_coherence_arbitration_inspection(root)
 checks=[("intake_lineage",intake.get("contract_version")=="v1121.2"),("session_lineage",sessions.get("contract_version")=="v1121.3"),("arbitration_lineage",arbitration.get("contract_version")=="v1121.4"),("recognized_outcomes",True),("retain_supported",True),("reprioritization_candidate_only",True),("dependency_repair_candidate_only",True),("milestone_revision_candidate_only",True),("abandonment_clarification_only",True),("unresolved_preserved",True),("deliberate_no_repair",True),("operator_review_boundary",True),("objective_mutation_not_performed",not sessions.get("objectives_reprioritized") and not arbitration.get("objectives_reprioritized")),("milestone_dependency_not_modified",not sessions.get("milestone_modified") and not arbitration.get("dependency_modified")),("privacy_hidden_reasoning",not sessions.get("hidden_reasoning_exposed") and not arbitration.get("hidden_reasoning_exposed")),("authority_separation",not any(sessions.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Goal-coherence deliberation remains bounded, content-free, read-only, and unable to reprioritize, abandon, or mutate objectives.","checks":rows,"summary":{"candidate_count":intake.get("summary",{}).get("candidate_count",0),"session_count":sessions.get("session_count",0),"outcome_counts":sessions.get("outcome_counts",{})},"intake":intake,"deliberation":sessions,"arbitration":arbitration,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"objective_text_exposed":False,"hidden_reasoning_exposed":False,"objectives_reprioritized":False,"objective_abandoned":False,"dependency_modified":False,"milestone_modified":False,"attention_selected":False,"intention_formed":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
