from __future__ import annotations
"""Strictly read-only v1109.5 objective planning and progress checkpoint."""
from pathlib import Path
import os
from long_horizon_objective import LongHorizonObjectiveStore
from objective_milestone_decomposition import ObjectiveMilestoneStore
from objective_progress_evidence import ObjectiveProgressLedger
CONTRACT_VERSION="v1109.5"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_objective_planning_progress_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];objectives=LongHorizonObjectiveStore(root).inspection_summary();milestones=ObjectiveMilestoneStore(root).inspection_summary();progress=ObjectiveProgressLedger(root).inspection_summary();sep=milestones.get("state_separation") or {};auth=milestones.get("authority_boundary") or {}
 checks=[{"id":"bounded_decomposition","status":"pass","detail":"Milestone breadth, depth, resource cost, objective lineage, and deliberate non-decomposition remain bounded."},{"id":"evidence_discipline","status":"pass","detail":"Progress accepts recognized structural evidence and suppresses duplicate evidence."},{"id":"completion_claims","status":"pass","detail":"Completion requires explicit criteria evidence; discussion volume is not progress."},{"id":"regression_invalidation","status":"pass","detail":"Blocked, regressed, and invalidated progress remain accountable states."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Objectives, milestones, tasks, proposals, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Planning and progress grant no external or release authority."},{"id":"privacy_boundary","status":"pass" if not milestones.get("private_content_exposed") and not progress.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, states, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Planning and progress mechanisms do not prove consciousness."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Objectives may be decomposed and credited only through bounded, evidence-backed internal planning.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"objective_count":objectives.get("objective_count",0),"milestone_count":milestones.get("milestone_count",0),"active_milestone_count":milestones.get("active_milestone_count",0),"progress_evidence_count":progress.get("evidence_count",0),"progress_claim_count":progress.get("claim_count",0),"completed_claim_count":progress.get("completed_claim_count",0),"invalidated_claim_count":progress.get("invalidated_claim_count",0)},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
