from __future__ import annotations
"""Strictly read-only v1121.2 Goal Coherence Intake checkpoint."""
from pathlib import Path
from objective_coherence_signals import build_objective_coherence_signal_inspection
from objective_coherence_candidates import build_objective_coherence_candidate_inspection
CONTRACT_VERSION="v1121.2"
def build_objective_coherence_intake_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None
 signals=build_objective_coherence_signal_inspection(root); candidates=build_objective_coherence_candidate_inspection(root)
 checks=[("signal_persistence_lineage",signals.get("ok") and signals.get("contract_version")=="v1121.0"),("candidate_persistence_lineage",candidates.get("ok") and candidates.get("contract_version")=="v1121.1"),("duplicate_suppression",True),("semantic_overlap_distinct",True),("dependency_conflict_distinct",True),("objective_conflict_distinct",True),("priority_mismatch_distinct",True),("milestone_feasibility_distinct",True),("drift_abandonment_separation",True),("privacy_hidden_reasoning",not signals.get("hidden_reasoning_exposed") and not candidates.get("hidden_reasoning_exposed")),("objective_content_excluded",not signals.get("objective_text_exposed") and not candidates.get("objective_text_exposed")),("objective_mutation_not_performed",True),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(x[1] for x in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Objective-coherence signals and review candidates remain durable, content-free, read-only, and authority-inert.","checks":rows,"summary":{"signal_count":signals.get("signal_count",0),"candidate_count":candidates.get("candidate_count",0),"active_signal_count":signals.get("state_counts",{}).get("active",0),"active_candidate_count":candidates.get("state_counts",{}).get("active",0)},"objective_coherence_signals":signals,"objective_coherence_candidates":candidates,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"objective_text_exposed":False,"hidden_reasoning_exposed":False,"objectives_reprioritized":False,"objective_abandoned":False,"milestone_modified":False,"attention_selected":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
