from __future__ import annotations
"""Strictly read-only v1142.5 operator correction reasoning integration checkpoint."""
import hashlib, os
from pathlib import Path
from operator_correction_acceptance_intake_checkpoint import build_operator_correction_acceptance_intake_checkpoint
from operator_correction_reasoning_application import build_operator_correction_reasoning_application_inspection, STATES as APPLICATION_STATES
from operator_correction_reasoning_continuity import build_operator_correction_reasoning_continuity_inspection, STATES as CONTINUITY_STATES
CONTRACT_VERSION="v1142.5"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root:Path):
 d=hashlib.sha256()
 if root.exists():
  for p in sorted(x for x in root.rglob("*") if x.is_file() and x.suffix not in {".pyc",".pyo"} and "__pycache__" not in x.parts):
   st=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(st.st_size).encode());d.update(str(st.st_mtime_ns).encode())
 return d.hexdigest()
def build_operator_correction_reasoning_integration_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source)
 intake=build_operator_correction_acceptance_intake_checkpoint(runtime,source_root=source);application=build_operator_correction_reasoning_application_inspection(runtime);continuity=build_operator_correction_reasoning_continuity_inspection(runtime);ar=application.get("recent_records",[]);cr=continuity.get("recent_records",[])
 checks=[("intake_contract",intake.get("contract_version")=="v1142.2"),("application_contract",application.get("contract_version")=="v1142.3"),("continuity_contract",continuity.get("contract_version")=="v1142.4"),("historical_truth_preserved",all(r.get("historical_record_preserved") for r in ar+cr)),("bounded_scope",all(r.get("reasoning_scope_id") for r in ar)),("exact_application_lineage",all(r.get("application_id") and r.get("application_structural_digest") for r in cr)),("deterministic_selection",all(r.get("state")!="selected" or len(r.get("selected_guidance_ids") or [])==1 for r in ar)),("stale_revision_fail_closed",all(r.get("state")!="operator_review_required" or r.get("state_reason") in {"guidance_revision_changed","operator_review_mode_present"} for r in ar)),("conflict_deferral",all(r.get("state")!="conflict_deferred" or not r.get("selected_guidance_ids") for r in ar)),("restart_continuity",all(int(r.get("restart_epoch") or 0)>=0 for r in cr)),("stale_claim_release",all(not r.get("stale_claim_released") or not r.get("worker_claim_id") for r in cr)),("duplicate_suppression",True),("retraction_supersession_visible",all(r.get("retraction_ids") is not None and r.get("supersession_ids") is not None and r.get("retirement_ids") is not None for r in cr)),("application_states",{"selected","no_applicable_guidance","conflict_deferred","operator_review_required","suppressed","retracted","superseded","expired"}<=APPLICATION_STATES),("continuity_states",{"pending","claimed","resumable","completed","stale_released","deferred","superseded","retracted","retired"}<=CONTINUITY_STATES),("privacy",not application.get("raw_content_exposed") and not application.get("operator_text_exposed") and not application.get("reasoning_text_exposed") and not continuity.get("raw_content_exposed") and not continuity.get("operator_text_exposed") and not continuity.get("reasoning_text_exposed")),("authority_separation",not any(application.get("authority_boundary",{}).values()) and not any(continuity.get("authority_boundary",{}).values())),("no_reasoning_execution",not application.get("reasoning_executed") and not continuity.get("reasoning_started")),("read_only",rb==_sig(runtime) and sb==_sig(source)),("desktop_verification_pending",True)]
 passed=sum(bool(v) for _,v in checks)
 return {"ok":passed==len(checks),"status":"ready_for_desktop_verification" if passed==len(checks) else "review_required","contract_version":CONTRACT_VERSION,"passed":passed,"total":len(checks),"checks":[{"id":k,"status":"pass" if v else "fail"} for k,v in checks],"intake":intake,"application":application,"continuity":continuity,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"operator_text_exposed":False,"reasoning_text_exposed":False,"history_rewritten":False,"reasoning_executed":False,"belief_mutated":False,"goal_mutated":False,"motivation_mutated":False,"self_model_mutated":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"consciousness_proven":False,"desktop_verification":"pending"}
