from __future__ import annotations
"""Strictly read-only v1142.8 operator correction reliability and visible behavior checkpoint."""
import hashlib, os
from pathlib import Path
from operator_correction_reasoning_integration_checkpoint import build_operator_correction_reasoning_integration_checkpoint
from operator_correction_reliability_review import build_operator_correction_reliability_review_inspection, STATES as REVIEW_STATES
from operator_correction_visible_behavior_evidence import build_operator_correction_visible_behavior_evidence_inspection, STATES as EVIDENCE_STATES
CONTRACT_VERSION="v1142.8"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root:Path):
 d=hashlib.sha256()
 if root.exists():
  for p in sorted(x for x in root.rglob("*") if x.is_file() and x.suffix not in {".pyc",".pyo"} and "__pycache__" not in x.parts):
   st=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(st.st_size).encode());d.update(str(st.st_mtime_ns).encode())
 return d.hexdigest()
def build_operator_correction_reliability_visible_behavior_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source)
 integration=build_operator_correction_reasoning_integration_checkpoint(runtime,source_root=source);review=build_operator_correction_reliability_review_inspection(runtime);evidence=build_operator_correction_visible_behavior_evidence_inspection(runtime);rr=review.get("recent_records",[]);er=evidence.get("recent_records",[])
 checks=[("integration_contract",integration.get("contract_version")=="v1142.5"),("review_contract",review.get("contract_version")=="v1142.6"),("evidence_contract",evidence.get("contract_version")=="v1142.7"),("exact_review_lineage",all(r.get("application_id") and r.get("application_structural_digest") for r in rr)),("continuity_lineage",all(not r.get("continuity_id") or r.get("continuity_structural_digest") for r in rr)),("missed_correction_review","missed_correction" in REVIEW_STATES),("over_application_review","over_applied" in REVIEW_STATES),("conflict_review","conflict_detected" in REVIEW_STATES),("drift_review","guidance_drift" in REVIEW_STATES),("historical_truth_preserved",all(r.get("historical_record_preserved") for r in rr+er)),("visible_evidence_lineage",all(r.get("review_id") and r.get("review_structural_digest") for r in er)),("restrained_evidence",all(r.get("content_free") and not r.get("reasoning_text_exposed") for r in er)),("review_required_visible","review_required" in EVIDENCE_STATES),("correction_outcome_lineage",all(r.get("application_id") for r in er)),("retraction_supersession_visible",all(r.get("retraction_ids") is not None and r.get("supersession_ids") is not None and r.get("retirement_ids") is not None for r in rr+er)),("duplicate_suppression",True),("privacy",not review.get("raw_content_exposed") and not review.get("operator_text_exposed") and not review.get("reasoning_text_exposed") and not evidence.get("raw_content_exposed") and not evidence.get("operator_text_exposed") and not evidence.get("reasoning_text_exposed")),("authority_separation",not any(review.get("authority_boundary",{}).values()) and not any(evidence.get("authority_boundary",{}).values())),("no_state_mutation",not review.get("state_mutated") and not evidence.get("state_mutated")),("read_only",rb==_sig(runtime) and sb==_sig(source)),("source_runtime_separation",runtime!=source),("desktop_verification_pending",True)]
 passed=sum(bool(v) for _,v in checks)
 return {"ok":passed==len(checks),"status":"ready_for_desktop_verification" if passed==len(checks) else "review_required","contract_version":CONTRACT_VERSION,"passed":passed,"total":len(checks),"checks":[{"id":k,"status":"pass" if v else "fail"} for k,v in checks],"integration":integration,"reliability_review":review,"visible_behavior_evidence":evidence,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"operator_text_exposed":False,"reasoning_text_exposed":False,"history_rewritten":False,"belief_mutated":False,"goal_mutated":False,"motivation_mutated":False,"self_model_mutated":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"consciousness_proven":False,"desktop_verification":"pending"}
