from __future__ import annotations
"""Strictly read-only v1108.2 persistent initiative continuity checkpoint."""
from pathlib import Path
import os
from persistent_initiative import PersistentInitiativeStore
from initiative_arbitration import InitiativeArbitrator
CONTRACT_VERSION="v1108.2"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_persistent_initiative_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];initiative=PersistentInitiativeStore(root).inspection_summary();arbitration=InitiativeArbitrator(root).inspection_summary();sep=initiative.get("state_separation") or {};auth=initiative.get("authority_boundary") or {}
 checks=[{"id":"durable_candidates","status":"pass","detail":"Initiative candidacy persists with intention and agenda lineage."},{"id":"bounded_arbitration","status":"pass","detail":"At most one candidate or deliberate silence is selected deterministically."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Candidacy, selection, message delivery, and action remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Initiative grants no send, browse, execution, model, approval, promotion, or certification authority."},{"id":"privacy_boundary","status":"pass" if not initiative.get("private_subjects_exposed") and not arbitration.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Observable initiative mechanisms do not prove consciousness."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Durable intentions may become bounded communication candidates without sending or acting.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"candidate_count":initiative.get("candidate_count",0),"eligible_candidate_count":initiative.get("eligible_candidate_count",0),"selection_count":arbitration.get("selection_count",0),"deliberate_silence_count":arbitration.get("deliberate_silence_count",0)},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_subjects_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
