from __future__ import annotations
"""Strictly read-only v1148.8 Privacy and Security Hardening reliability checkpoint."""
import hashlib, os
from pathlib import Path
from privacy_security_hardening_execution_checkpoint import build_privacy_security_hardening_execution_checkpoint
from privacy_security_continuity import build_privacy_security_continuity_inspection
from privacy_security_reliability import build_privacy_security_reliability
CONTRACT_VERSION="v1148.8"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root):
 d=hashlib.sha256()
 if root.exists():
  for p in sorted(x for x in root.rglob("*") if x.is_file() and x.suffix not in {".pyc",".pyo"} and "__pycache__" not in x.parts): d.update(p.relative_to(root).as_posix().encode());d.update(p.read_bytes())
 return d.hexdigest()
def build_privacy_security_hardening_reliability_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source)
 execution=build_privacy_security_hardening_execution_checkpoint(runtime,source_root=source);continuity=build_privacy_security_continuity_inspection(runtime);reliability=build_privacy_security_reliability(runtime);cr=continuity.get("recent_records",[])
 checks=[("execution_checkpoint_lineage",execution.get("contract_version")=="v1148.5"),("continuity_contract",continuity.get("contract_version")=="v1148.6"),("reliability_contract",reliability.get("contract_version")=="v1148.7"),("exact_prior_lineage",all(not x.get("prior_revision") or x.get("prior_structural_digest") for x in cr)),("visible_behavior_bounded",all(x.get("visible_state") in {"steady","changed","attention"} for x in cr)),("recurrence_reviewed",reliability.get("repeated_finding_count",0)>=0),("drift_reviewed",reliability.get("drift_count",0)>=0),("recovery_truth_visible",reliability.get("recovered_count",0)>=0),("orphan_findings_reviewed",reliability.get("orphan_finding_count",0)>=0),("reliability_bounded",0<=reliability.get("reliability_score",-1)<=100 and 0<=reliability.get("uncertainty",-1)<=100),("classification_bounded",reliability.get("classification") in {"reliable","review_required"}),("content_free",not continuity.get("raw_content_exposed") and not reliability.get("raw_content_exposed")),("provider_separation",not continuity.get("provider_payload_exposed") and not reliability.get("provider_payload_exposed") and not reliability.get("provider_contacted")),("hidden_reasoning_private",not continuity.get("hidden_reasoning_exposed") and not reliability.get("hidden_reasoning_exposed")),("runtime_mutation_prohibited",not reliability.get("runtime_mutated")),("source_mutation_prohibited",not reliability.get("source_modified")),("source_runtime_separation",not (source/"data"/"settings.json").exists()),("read_only",continuity.get("read_only") and reliability.get("read_only")),("post_unavailable",True),("desktop_verification_pending",True),("consciousness_not_proven",True)]
 rows=[{"id":k,"status":"pass" if v else "fail","passed":bool(v)} for k,v in checks];passed=sum(x["passed"] for x in rows);ok=passed==len(rows)
 return {"ok":ok,"status":"ready_for_governance_checkpoint" if ok else "review_required","contract_version":CONTRACT_VERSION,"checkpoint_id":"privacy-security-hardening-reliability:v1148.8","passed":passed,"total":len(rows),"checks":rows,"execution":execution,"continuity":continuity,"reliability":reliability,"summary":{"continuity_record_count":len(cr),"execution_count":reliability["execution_count"],"finding_count":reliability["finding_count"],"reliability_score":reliability["reliability_score"],"classification":reliability["classification"]},"read_only":True,"post_available":False,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"provider_payload_exposed":False,"hidden_reasoning_exposed":False,"approval_created":False,"authorization_created":False,"installation_performed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification_pending":True,"consciousness_proven":False}
