from __future__ import annotations
"""Strictly read-only v1148.5 Privacy and Security Hardening execution checkpoint."""
import hashlib, os
from pathlib import Path
from privacy_security_hardening_intake_checkpoint import build_privacy_security_hardening_intake_checkpoint
from privacy_security_bounded_execution import build_privacy_security_bounded_execution_inspection, STATES as EXECUTION_STATES
from privacy_security_findings_receipts import build_privacy_security_findings_receipts_inspection, STATES as RECEIPT_STATES
CONTRACT_VERSION="v1148.5"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root:Path):
 d=hashlib.sha256()
 if root.exists():
  for p in sorted(x for x in root.rglob("*") if x.is_file() and x.suffix not in {".pyc",".pyo"} and "__pycache__" not in x.parts):
   st=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(st.st_size).encode());d.update(str(st.st_mtime_ns).encode())
 return d.hexdigest()
def build_privacy_security_hardening_execution_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source)
 intake=build_privacy_security_hardening_intake_checkpoint(source_root=source);e=build_privacy_security_bounded_execution_inspection(runtime);r=build_privacy_security_findings_receipts_inspection(runtime);er=e.get("recent_records",[]);rr=r.get("recent_records",[]);by_id={x.get("execution_id"):x for x in er}
 checks=[("intake_contract",intake.get("contract_version")=="v1148.2"),("execution_contract",e.get("contract_version")=="v1148.3"),("receipt_contract",r.get("contract_version")=="v1148.4"),("exact_scenario_lineage",all(x.get("scenario_id") and x.get("scenario_digest") for x in er)),("operator_confirmation_binding",all(x.get("state") in {"awaiting_confirmation","cancelled","timed_out","suppressed"} or x.get("operator_confirmation_id") for x in er)),("bounded_execution",all(int(x.get("steps_used") or 0)<=5 and int(x.get("attempts_used") or 0)<=1 and int(x.get("runtime_ms") or 0)<=250 for x in er if x.get("state")!="timed_out")),("zero_provider_budget",all(int(x.get("provider_tokens_used") or 0)==0 for x in er)),("exact_execution_receipt_lineage",all(x.get("execution_id") in by_id and x.get("execution_digest")==by_id[x.get("execution_id")].get("structural_digest") for x in rr)),("recovery_truth",all(not x.get("recovery_succeeded") or x.get("recovery_attempted") for x in rr)),("containment_truth",all(x.get("state")!="contained" or x.get("contained") for x in rr)),("recognized_execution_states",{"awaiting_confirmation","passed","contained","review_required","timed_out","cancelled","suppressed"}<=EXECUTION_STATES),("recognized_receipt_states",{"no_finding","contained","recovered","recovery_failed","review_required","retired"}<=RECEIPT_STATES),("content_free",not e.get("raw_content_exposed") and not r.get("raw_content_exposed") and all(not x.get("fixture_content_included") and not x.get("raw_payload_recorded") for x in er) and all(not x.get("raw_evidence_recorded") for x in rr)),("provider_separation",not e.get("provider_payload_exposed") and not r.get("provider_payload_exposed")),("authority_separation",not any(e.get("authority_boundary",{}).values()) and not any(r.get("authority_boundary",{}).values())),("source_unchanged",not e.get("source_modified") and not r.get("source_modified")),("read_only",rb==_sig(runtime) and sb==_sig(source)),("desktop_verification_pending",True),("consciousness_not_proven",True)]
 passed=sum(bool(v) for _,v in checks);ok=passed==len(checks)
 return {"ok":ok,"status":"ready_for_bundle_c" if ok else "review_required","contract_version":CONTRACT_VERSION,"checkpoint_id":"privacy-security-hardening-execution:v1148.5","passed":passed,"total":len(checks),"checks":[{"id":k,"status":"pass" if v else "fail","passed":bool(v)} for k,v in checks],"intake":intake,"executions":e,"findings":r,"summary":{"execution_count":len(er),"finding_count":len(rr),"contained_count":sum(x.get("state")=="contained" for x in rr),"recovered_count":sum(x.get("state")=="recovered" for x in rr),"review_required_count":sum(x.get("state")=="review_required" for x in er+rr)},"read_only":True,"post_available":False,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"provider_payload_exposed":False,"hidden_reasoning_exposed":False,"approval_created":False,"authorization_created":False,"installation_performed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification_pending":True,"consciousness_proven":False}
