from __future__ import annotations
"""Strictly read-only v1134.5 prospective-planning deliberation checkpoint."""
import hashlib, os
from pathlib import Path
from prospective_planning_deliberation_sessions import build_prospective_planning_deliberation_session_inspection
from prospective_planning_arbitration import build_prospective_planning_arbitration_inspection, OUTCOMES
CONTRACT_VERSION='v1134.5'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_prospective_planning_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); sessions=build_prospective_planning_deliberation_session_inspection(runtime); arbitration=build_prospective_planning_arbitration_inspection(runtime)
 checks=[('session_contract',sessions.get('contract_version')=='v1134.3'),('arbitration_contract',arbitration.get('contract_version')=='v1134.4'),('bounded_sessions',all(1<=x.get('deliberation_budget',0)<=6 for x in sessions.get('recent_sessions',[]))),('exact_candidate_lineage',all(x.get('candidate_id') and x.get('signal_ids') for x in sessions.get('recent_sessions',[]))),('goal_and_evidence_lineage',all(x.get('goal_ids') and x.get('evidence_ids') is not None for x in sessions.get('recent_sessions',[]))),('alternatives_and_counterfactuals',all(x.get('alternative_ids') is not None and x.get('counterfactual_ids') is not None for x in sessions.get('recent_sessions',[]))),('risk_reversibility_stop_conditions',all(x.get('risk') is not None and x.get('reversibility') is not None and x.get('stop_condition_ids') is not None for x in sessions.get('recent_sessions',[]))),('plan_recommendation','plan_recommended' in OUTCOMES),('alternative_comparison','alternative_comparison_recommended' in OUTCOMES),('counterfactual_review','counterfactual_review_recommended' in OUTCOMES),('plan_revision','plan_revision_recommended' in OUTCOMES),('deliberate_no_action','deliberate_no_action' in OUTCOMES),('recovery_focus_budget_deferral',{'defer_for_recovery','defer_for_focus','defer_for_cognitive_budget'}<=OUTCOMES),('operator_prerequisite_timing_deferral',{'defer_for_operator_review','await_prerequisite','await_timing_window'}<=OUTCOMES),('risk_and_stop_condition_deferral',{'await_risk_review','await_stop_condition_review'}<=OUTCOMES),('false_urgency_suppression','suppress_false_urgency' in OUTCOMES),('low_value_and_risk_suppression',{'suppress_low_value_plan','suppress_high_risk_plan','suppress_irreversible_plan'}<=OUTCOMES),('no_plan_activation',all(not x.get('plan_id') and not x.get('initiative_id') for x in arbitration.get('recent_outcomes',[]))),('privacy_boundary',not sessions.get('raw_content_exposed') and not arbitration.get('plan_text_exposed') and not sessions.get('hidden_reasoning_exposed')),('no_provider_or_action',not sessions.get('provider_contacted') and not arbitration.get('provider_contacted') and not arbitration.get('external_action_executed')),('authority_separation',not any(sessions.get('authority_boundary',{}).values()) and not any(arbitration.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'sessions':sessions,'arbitration':arbitration,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'goal_text_exposed':False,'plan_text_exposed':False,'counterfactual_text_exposed':False,'evidence_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'provider_contacted':False,'goal_activated':False,'plan_activated':False,'initiative_created':False,'message_sent':False,'notification_created':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
