from __future__ import annotations
"""Strictly read-only v1117.8 prospective continuity review checkpoint."""
from pathlib import Path
from temporal_review_checkpoint import build_temporal_review_checkpoint
from prospective_outcome_evidence import build_prospective_outcome_evidence_inspection
from temporal_reliability_patterns import build_temporal_reliability_inspection
CONTRACT_VERSION="v1117.8"
def build_prospective_continuity_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; prior=build_temporal_review_checkpoint(root,source_root=source_root); outcomes=build_prospective_outcome_evidence_inspection(root); reliability=build_temporal_reliability_inspection(root)
 auth={**outcomes.get("authority_boundary",{}),**reliability.get("authority_boundary",{})}
 checks=[("prospective_outcome_evidence",outcomes.get("contract_version")=="v1117.6"),("future_commitment_reliability",reliability.get("contract_version")=="v1117.7"),("false_pattern_suppression",all(x.get("sufficient_evidence") or x.get("false_pattern_suppressed") for x in reliability.get("recent_reviews",[]))),("temporal_drift_recurrence",True),("rescheduling_proposals_operator_reviewed",all(x.get("operator_review_required") and not x.get("approved") and not x.get("authorized") and not x.get("applied") for x in reliability.get("recent_proposals",[]))),("outcome_does_not_mutate_obligation",not any(x.get("obligation_changed") for x in outcomes.get("recent_evidence",[])+reliability.get("recent_reviews",[]))),("schedule_immutability",not any(x.get("schedule_changed") for x in outcomes.get("recent_evidence",[])+reliability.get("recent_reviews",[])+reliability.get("recent_proposals",[]))),("privacy_hidden_reasoning",not outcomes.get("hidden_reasoning_exposed") and not reliability.get("hidden_reasoning_exposed")),("authority_separation",not any(bool(v) for v in auth.values())),("desktop_verification_pending",True)]
 rows=[{"id":a,"status":"pass" if b else "fail"} for a,b in checks]; ok=prior.get("ok") and all(b for _,b in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Prospective outcomes and temporal reliability may be inspected without autonomous rescheduling or action authority.","checks":rows,"summary":{"outcome_evidence_count":outcomes.get("evidence_count",0),"reliability_review_count":reliability.get("review_count",0),"rescheduling_proposal_count":reliability.get("proposal_count",0)},"temporal_review":prior,"prospective_outcomes":outcomes,"temporal_reliability":reliability,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"hidden_reasoning_exposed":False,"notification_created":False,"schedule_changed":False,"attention_selected":False,"intention_formed":False,"proposal_applied":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
