from __future__ import annotations
"""Strictly read-only v1131.5 perception deliberation checkpoint."""
import hashlib, os
from pathlib import Path
from read_only_perception_deliberation_sessions import build_read_only_perception_deliberation_session_inspection
from read_only_perception_arbitration import build_read_only_perception_arbitration_inspection, OUTCOMES
CONTRACT_VERSION='v1131.5'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_read_only_perception_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); sessions=build_read_only_perception_deliberation_session_inspection(runtime); arbitration=build_read_only_perception_arbitration_inspection(runtime)
 checks=[('session_contract',sessions.get('contract_version')=='v1131.3'),('arbitration_contract',arbitration.get('contract_version')=='v1131.4'),('bounded_sessions',all(1<=x.get('deliberation_budget',0)<=6 for x in sessions.get('recent_sessions',[]))),('exact_candidate_lineage',all(x.get('candidate_id') and x.get('signal_ids') for x in sessions.get('recent_sessions',[]))),('scope_preserved',all(x.get('scope_digest') is not None for x in sessions.get('recent_sessions',[]))),('failure_priority', 'failure_review_prioritized' in OUTCOMES),('changed_file_priority','changed_file_review_prioritized' in OUTCOMES),('deliberate_non_perception','deliberate_no_perception' in OUTCOMES),('recovery_deferral','defer_for_recovery' in OUTCOMES),('focus_and_budget_deferral',{'defer_for_focus','defer_for_cognitive_budget'}<=OUTCOMES),('conversation_sensitivity','defer_for_conversation_sensitivity' in OUTCOMES),('operator_and_prerequisite_deferral',{'defer_for_operator_review','await_prerequisite'}<=OUTCOMES),('false_priority_suppression','suppress_false_priority' in OUTCOMES),('content_free_outcomes',all(not x.get('raw_file_read_id') and not x.get('filesystem_action_id') for x in arbitration.get('recent_outcomes',[]))),('privacy_boundary',not sessions.get('raw_file_content_exposed') and not arbitration.get('raw_event_payload_exposed') and not sessions.get('hidden_reasoning_exposed')),('no_filesystem_mutation',not sessions.get('filesystem_modified') and not arbitration.get('filesystem_modified')),('no_browser_provider_or_action',not sessions.get('browser_contacted') and not arbitration.get('provider_contacted') and not arbitration.get('external_action_executed')),('authority_separation',not any(sessions.get('authority_boundary',{}).values()) and not any(arbitration.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'sessions':sessions,'arbitration':arbitration,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_file_content_exposed':False,'raw_event_payload_exposed':False,'message_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'filesystem_modified':False,'browser_contacted':False,'provider_contacted':False,'message_sent':False,'notification_created':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
