from __future__ import annotations
"""Strictly read-only v1131.2 project and system perception intake checkpoint."""
import hashlib, os
from pathlib import Path
from read_only_perception_signals import build_read_only_perception_signal_inspection, CATEGORIES
from read_only_perception_candidates import build_read_only_perception_candidate_inspection, STATES
CONTRACT_VERSION='v1131.2'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_read_only_perception_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); signals=build_read_only_perception_signal_inspection(runtime); candidates=build_read_only_perception_candidate_inspection(runtime)
 checks=[('signal_contract',signals.get('contract_version')=='v1131.0'),('candidate_contract',candidates.get('contract_version')=='v1131.1'),('category_coverage',CATEGORIES=={'project_state','system_event','completed_work','failure','changed_file'}),('candidate_states',len(STATES)==11),('exact_lineage',all(x.get('origin_ids') for x in signals.get('recent_signals',[]))),('changed_files_content_free',all(x.get('changed_path_digest') is not None for x in signals.get('recent_signals',[]))),('project_and_conversation_continuity',all(x.get('project_id') is not None and x.get('conversation_id') is not None for x in signals.get('recent_signals',[]))),('failure_distinct_from_execution',all(not x.get('action_id') for x in signals.get('recent_signals',[]))),('scope_bounded',all(x.get('scope_digest') is not None for x in candidates.get('recent_candidates',[]))),('recovery_and_cost',all(x.get('recovery_compatible') is not None and x.get('cognitive_cost') is not None for x in candidates.get('recent_candidates',[]))),('sensitivity_visible',all(x.get('sensitivity') is not None for x in candidates.get('recent_candidates',[]))),('overlap_visible',all(x.get('semantic_overlap_key') is not None for x in candidates.get('recent_candidates',[]))),('privacy_boundary',not signals.get('raw_file_content_exposed') and not candidates.get('raw_event_payload_exposed') and not signals.get('hidden_reasoning_exposed')),('no_filesystem_mutation',not signals.get('filesystem_modified') and not candidates.get('filesystem_modified')),('no_browser_or_provider',not signals.get('browser_contacted') and not candidates.get('provider_contacted')),('authority_separation',not any(signals.get('authority_boundary',{}).values()) and not any(candidates.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'signals':signals,'candidates':candidates,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_file_content_exposed':False,'raw_event_payload_exposed':False,'message_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'filesystem_modified':False,'browser_contacted':False,'provider_contacted':False,'message_sent':False,'notification_created':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
