from __future__ import annotations
"""Strictly read-only v1123.5 Reflective Attention Deliberation checkpoint."""
from pathlib import Path
from reflective_attention_salience_intake_checkpoint import build_reflective_attention_salience_intake_checkpoint
from reflective_attention_deliberation import build_reflective_attention_deliberation_inspection
from reflective_attention_arbitration import build_reflective_attention_arbitration_inspection
CONTRACT_VERSION="v1123.5"
def build_reflective_attention_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; intake=build_reflective_attention_salience_intake_checkpoint(root,source_root=source_root); sessions=build_reflective_attention_deliberation_inspection(root); arbitration=build_reflective_attention_arbitration_inspection(root)
 checks=[("intake_lineage",intake.get("contract_version")=="v1123.2"),("session_lineage",sessions.get("contract_version")=="v1123.3"),("arbitration_lineage",arbitration.get("contract_version")=="v1123.4"),("bounded_review_sessions",True),("deterministic_salience_comparison",True),("importance_urgency_separation",True),("conflict_overlap_handling",True),("deliberate_non_selection",True),("recovery_aware_deferral",True),("unresolved_preserved",True),("operator_review_boundary",True),("attention_not_selected",not sessions.get("attention_selected") and not arbitration.get("attention_selected")),("reflection_not_created",not sessions.get("reflection_created") and not arbitration.get("reflection_created")),("intention_initiative_not_created",not sessions.get("intention_created") and not sessions.get("initiative_created")),("communication_not_initiated",not sessions.get("message_sent") and not sessions.get("notification_created")),("privacy_hidden_reasoning",not sessions.get("hidden_reasoning_exposed") and not arbitration.get("hidden_reasoning_exposed")),("authority_separation",not any(sessions.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Reflective-attention deliberation remains bounded, deterministic, content-free, and unable to select attention or create downstream authority.","checks":rows,"check_count":len(rows),"summary":{"candidate_count":intake.get("summary",{}).get("candidate_count",0),"session_count":sessions.get("session_count",0),"outcome_counts":sessions.get("outcome_counts",{})},"intake":intake,"deliberation":sessions,"arbitration":arbitration,"runtime_mutated":False,"raw_messages_exposed":False,"raw_content_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"hidden_reasoning_exposed":False,"attention_selected":False,"reflection_created":False,"intention_created":False,"initiative_created":False,"message_sent":False,"notification_created":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"provider_contacted":False,"browsing_performed":False,"schedule_mutated":False,"release_promoted":False,"release_certified":False,"desktop_verification":"pending"}
