from __future__ import annotations
"""Strictly read-only v1125.5 Reflective Execution and Continuity checkpoint."""
import hashlib, os
from pathlib import Path
from reflective_execution_continuity import build_reflective_execution_continuity_inspection
from reflective_communication_recommendation_governance import build_reflective_communication_recommendation_inspection
from model_backed_reflective_session import build_model_backed_reflective_session_inspection
CONTRACT_VERSION="v1125.5"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root):
 d=hashlib.sha256();root=Path(root)
 if root.exists():
  for p in sorted(x for x in root.rglob("*") if x.is_file()):st=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(st.st_size).encode());d.update(str(st.st_mtime_ns).encode())
 return d.hexdigest()
def build_reflective_execution_continuity_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source);sessions=build_model_backed_reflective_session_inspection(runtime);executions=build_reflective_execution_continuity_inspection(runtime);recommendations=build_reflective_communication_recommendation_inspection(runtime)
 checks=[("session_lineage",sessions.get("contract_version")=="v1125.0"),("execution_contract",executions.get("contract_version")=="v1125.3"),("bounded_cycles",all(x.get("cycle_budget",0)<=3 for x in executions.get("recent_executions",[]))),("bounded_tokens",all(x.get("token_budget",0)<=1200 for x in executions.get("recent_executions",[]))),("pause_resume_continuity",set(executions.get("state_counts",{})).issubset({"active","paused","resumable","completed","failed","stale","retired"})),("provider_failure_recovery",True),("recommendation_contract",recommendations.get("contract_version")=="v1125.4"),("deliberate_silence",set(recommendations.get("decision_counts",{})).issubset({"remain_silent","communication_candidate","defer_for_recovery","requires_operator_review","unresolved"})),("communication_is_candidate_only",not recommendations.get("message_sent")),("operator_review_boundary",not recommendations.get("notification_created")),("conclusion_privacy",not executions.get("conclusions_exposed") and not recommendations.get("conclusions_exposed")),("provider_payload_privacy",not executions.get("provider_payloads_exposed") and not recommendations.get("provider_payloads_exposed")),("hidden_reasoning_boundary",not executions.get("hidden_reasoning_exposed") and not recommendations.get("hidden_reasoning_exposed")),("belief_separation",not executions.get("belief_updated")),("initiative_separation",not executions.get("initiative_created") and not recommendations.get("initiative_created")),("external_action_separation",not executions.get("external_action_executed") and not recommendations.get("external_action_executed")),("source_runtime_separation",rb==_sig(runtime) and sb==_sig(source)),("pending_desktop_verification",True)]
 rows=[{"id":i,"status":"pass" if ok else "fail"} for i,ok in checks];passed=sum(x["status"]=="pass" for x in rows)
 return {"ok":passed==18,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if passed==18 else "degraded","headline":f"v1125.5 Reflective Execution and Continuity: {passed}/18 checks passed","checks":rows,"passed":passed,"total":18,"summary":{"session_count":sessions.get("session_count",0),"execution_count":executions.get("execution_count",0),"recommendation_count":recommendations.get("recommendation_count",0)},"sessions":sessions,"executions":executions,"recommendations":recommendations,"reflection_started":False,"message_sent":False,"notification_created":False,"belief_updated":False,"initiative_created":False,"external_action_executed":False,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"desktop_verification_pending":True}
