from __future__ import annotations
"""Strictly read-only v1128.2 Reflection-Supported Revision Intake checkpoint."""
import hashlib, os
from pathlib import Path
from reflection_supported_revision_signals import build_reflection_supported_revision_signal_inspection, TARGET_TYPES
from reflection_supported_revision_candidates import build_reflection_supported_revision_candidate_inspection
CONTRACT_VERSION='v1128.2'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists():return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(s.st_size).encode());d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_reflection_supported_revision_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root();source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb=_sig(runtime);sb=_sig(source);signals=build_reflection_supported_revision_signal_inspection(runtime);candidates=build_reflection_supported_revision_candidate_inspection(runtime)
 checks=[('signal_contract',signals.get('contract_version')=='v1128.0'),('candidate_contract',candidates.get('contract_version')=='v1128.1'),('target_domains',TARGET_TYPES=={'belief','motivation','goal','self_model'}),('reflection_lineage',all(x.get('reflection_outcome_id') for x in signals.get('recent_signals',[]))),('quality_lineage',all(x.get('quality_outcome_id') for x in signals.get('recent_signals',[]))),('evidence_refs_structural',all(isinstance(x.get('evidence_refs'),list) for x in signals.get('recent_signals',[]))),('uncertainty_explicit',all(x.get('uncertainty') is not None for x in signals.get('recent_signals',[]))),('correction_history_supported',all(x.get('correction_required') is not None for x in signals.get('recent_signals',[]))),('candidate_lineage',all(x.get('signal_ids') for x in candidates.get('recent_candidates',[]))),('prerequisite_handling',all(isinstance(x.get('prerequisite_ids'),list) for x in candidates.get('recent_candidates',[]))),('recovery_compatibility',all(x.get('recovery_compatible') is not None for x in candidates.get('recent_candidates',[]))),('operator_review_boundary',all(x.get('operator_review_required') is not None for x in candidates.get('recent_candidates',[]))),('privacy_boundary',not signals.get('raw_content_exposed') and not signals.get('conclusion_text_exposed') and not signals.get('evidence_text_exposed') and not signals.get('hidden_reasoning_exposed')),('no_target_revision',not signals.get('target_revised') and not candidates.get('target_revised')),('no_provider_contact',not signals.get('authority_boundary',{}).get('can_contact_provider')),('no_communication',not signals.get('authority_boundary',{}).get('can_communicate')),('no_execution_authority',not signals.get('authority_boundary',{}).get('can_execute') and not candidates.get('authority_boundary',{}).get('can_execute')),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'signals':signals,'candidates':candidates,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'conclusion_text_exposed':False,'evidence_text_exposed':False,'hidden_reasoning_exposed':False,'belief_revised':False,'motivation_revised':False,'goal_revised':False,'self_model_revised':False,'provider_contacted':False,'message_sent':False,'external_action_executed':False}
