from __future__ import annotations
"""Strictly read-only v1123.8 Reflective Attention Continuity Review checkpoint."""
from pathlib import Path
from reflective_attention_deliberation_checkpoint import build_reflective_attention_deliberation_checkpoint
from reflective_attention_outcome_lineage import build_reflective_attention_outcome_lineage_inspection
from reflective_attention_continuity_review import build_reflective_attention_continuity_review
CONTRACT_VERSION="v1123.8"
def build_reflective_attention_continuity_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; deliberation=build_reflective_attention_deliberation_checkpoint(root,source_root=source_root); lineage=build_reflective_attention_outcome_lineage_inspection(root); continuity=build_reflective_attention_continuity_review(root)
 checks=[("deliberation_lineage",deliberation.get("contract_version")=="v1123.5"),("outcome_lineage",lineage.get("contract_version")=="v1123.6"),("continuity_lineage",continuity.get("contract_version")=="v1123.7"),("history_preserved",lineage.get("history_preserved") is True),("supersession_without_deletion",True),("interruption_resumption_continuity",True),("repeated_distraction_review",True),("fixation_review",True),("false_pattern_suppression",True),("attention_reliability_evidence",True),("operator_reviewed_policy_proposals",True),("attention_not_selected",not lineage.get("attention_selected") and not continuity.get("attention_selected")),("reflection_not_created",not lineage.get("reflection_created") and not continuity.get("reflection_created")),("initiative_not_created",not lineage.get("initiative_created") and not continuity.get("initiative_created")),("communication_not_sent",not lineage.get("message_sent") and not continuity.get("message_sent")),("notification_not_created",not lineage.get("notification_created") and not continuity.get("notification_created")),("policy_not_applied",not continuity.get("policy_applied")),("authority_separation",not any(lineage.get("authority_boundary",{}).values())),("privacy_and_desktop_boundary",not lineage.get("hidden_reasoning_exposed") and not continuity.get("hidden_reasoning_exposed"))]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Attention outcome lineage and continuity review remain content-free, historically accountable, read-only, and authority-inert.","checks":rows,"summary":{"outcome_count":lineage.get("outcome_count",0),"outcome_counts":lineage.get("outcome_counts",{}),"reviewed_candidate_count":continuity.get("candidate_count",0)},"deliberation":deliberation,"lineage":lineage,"continuity":continuity,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"hidden_reasoning_exposed":False,"attention_selected":False,"reflection_created":False,"intention_created":False,"initiative_created":False,"message_sent":False,"notification_created":False,"provider_contacted":False,"browsing_performed":False,"policy_applied":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"release_promoted":False,"release_certified":False,"desktop_verification":"pending"}
