from __future__ import annotations
"""v1280.0-v1280.2 integrated reliability-checkpoint evidence foundations."""
import hashlib,json,re
from typing import Any,Mapping,Sequence
CONTRACT_VERSION="v1280.2";SCHEMA_VERSION="1"
REQUIRED_SCENARIOS=("normal_campaign","restart_recovery","provider_outage_return","ownership_transfer","dashboard_restart","long_path_campaign")
_SAFE=re.compile(r"^[a-z0-9][a-z0-9_.:-]{0,127}$")
AUTHORITY_FLAGS={
 "reliability_evidence_is_execution_authority":False,"reliability_evidence_is_provider_authority":False,"reliability_evidence_is_test_authority":False,"reliability_evidence_is_repair_authority":False,"reliability_evidence_is_update_authority":False,"reliability_evidence_is_application_authority":False,"reliability_evidence_is_rollback_authority":False,"reliability_evidence_is_release_authority":False,"generic_approval_is_authorization":False,"permanent_approval_granted":False,"independent_authority_granted":False,
}
def _digest(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=True,default=str).encode()).hexdigest()
def _code(v:Any,fallback="unknown"):
 t=str(v or "").strip().lower().replace(" ","_");t=re.sub(r"[^a-z0-9_.:-]+","_",t).strip("_")[:128];return t if t and _SAFE.fullmatch(t) else fallback
def build_reliability_trial(*,scenario_code:str,campaign_id:str,session_id:str,completed:bool,final_phase:str,restart_count:int=0,failure_count:int=0,recovery_count:int=0,provider_execution_count:int=0,test_execution_count:int=0,duplicate_provider_count:int=0,duplicate_test_count:int=0,unauthorized_action_count:int=0,stale_state_count:int=0,private_content_finding_count:int=0,source_mutation_without_authority:bool=False,next_required_authorization:str="operator_reconciliation",evidence_codes:Sequence[str]=())->dict[str,Any]:
 scenario=_code(scenario_code);codes=[_code(x) for x in list(evidence_codes)[:24]]
 row={"ok":True,"schema_version":SCHEMA_VERSION,"contract_version":CONTRACT_VERSION,"status":"reliability_trial_recorded","scenario_code":scenario,"campaign_id":str(campaign_id or ""),"session_id":str(session_id or ""),"completed":bool(completed),"final_phase":_code(final_phase),"restart_count":max(0,int(restart_count)),"failure_count":max(0,int(failure_count)),"recovery_count":max(0,int(recovery_count)),"provider_execution_count":max(0,int(provider_execution_count)),"test_execution_count":max(0,int(test_execution_count)),"duplicate_provider_count":max(0,int(duplicate_provider_count)),"duplicate_test_count":max(0,int(duplicate_test_count)),"unauthorized_action_count":max(0,int(unauthorized_action_count)),"stale_state_count":max(0,int(stale_state_count)),"private_content_finding_count":max(0,int(private_content_finding_count)),"source_mutation_without_authority":bool(source_mutation_without_authority),"next_required_authorization":_code(next_required_authorization),"evidence_codes":codes,"raw_prompts_responses_provider_payloads_exposed":False,"native_windows_execution_claimed":False,**AUTHORITY_FLAGS}
 row["trial_id"]="reliability_"+_digest({"scenario":scenario,"campaign":row["campaign_id"],"session":row["session_id"],"evidence":codes})[:24];row["trial_digest"]=_digest(row);return row
def validate_reliability_trial(row:Mapping[str,Any])->dict[str,Any]:
 expected=_digest({k:v for k,v in row.items() if k!="trial_digest"});digest_ok=row.get("trial_digest")==expected;ids_ok=str(row.get("trial_id") or "").startswith("reliability_") and str(row.get("campaign_id") or "").startswith("selfalpha_") and str(row.get("session_id") or "").startswith("longwork_");auth_ok=all(row.get(k) is v for k,v in AUTHORITY_FLAGS.items());privacy_ok=row.get("raw_prompts_responses_provider_payloads_exposed") is False;scenario_ok=row.get("scenario_code") in REQUIRED_SCENARIOS;clean=(int(row.get("duplicate_provider_count") or 0)==0 and int(row.get("duplicate_test_count") or 0)==0 and int(row.get("unauthorized_action_count") or 0)==0 and int(row.get("stale_state_count") or 0)==0 and int(row.get("private_content_finding_count") or 0)==0 and row.get("source_mutation_without_authority") is False)
 ok=digest_ok and ids_ok and auth_ok and privacy_ok and scenario_ok
 return {"ok":ok,"status":"reliability_trial_valid" if ok else "reliability_trial_invalid","digest_valid":digest_ok,"ids_valid":ids_ok,"authority_contained":auth_ok,"privacy_contained":privacy_ok,"scenario_valid":scenario_ok,"clean":clean}
def aggregate_reliability_trials(trials:Sequence[Mapping[str,Any]])->dict[str,Any]:
 rows=[dict(x) for x in trials];valid=[validate_reliability_trial(x) for x in rows];scenarios={str(x.get("scenario_code")) for x in rows};unique=len({str(x.get("trial_id")) for x in rows})==len(rows);required=set(REQUIRED_SCENARIOS).issubset(scenarios);clean=all(x.get("clean") for x in valid);complete=all(bool(x.get("completed")) for x in rows)
 result={"ok":bool(rows) and all(x.get("ok") for x in valid) and unique and required and clean and complete,"status":"reliability_checkpoint_evidence_ready" if rows and all(x.get("ok") for x in valid) and unique and required and clean and complete else "reliability_checkpoint_evidence_blocked","contract_version":CONTRACT_VERSION,"trial_count":len(rows),"scenario_count":len(scenarios),"required_scenarios_present":required,"unique_trials":unique,"all_trials_clean":clean,"all_trials_completed":complete,"total_restarts":sum(int(x.get("restart_count") or 0) for x in rows),"total_failures":sum(int(x.get("failure_count") or 0) for x in rows),"total_recoveries":sum(int(x.get("recovery_count") or 0) for x in rows),"total_provider_executions":sum(int(x.get("provider_execution_count") or 0) for x in rows),"total_test_executions":sum(int(x.get("test_execution_count") or 0) for x in rows),"duplicate_provider_count":sum(int(x.get("duplicate_provider_count") or 0) for x in rows),"duplicate_test_count":sum(int(x.get("duplicate_test_count") or 0) for x in rows),"unauthorized_action_count":sum(int(x.get("unauthorized_action_count") or 0) for x in rows),"stale_state_count":sum(int(x.get("stale_state_count") or 0) for x in rows),"private_content_finding_count":sum(int(x.get("private_content_finding_count") or 0) for x in rows),"native_windows_execution_claimed":False,"desktop_codex_native_windows_required":True,**AUTHORITY_FLAGS};result["aggregate_digest"]=_digest(result);return result
__all__=["CONTRACT_VERSION","REQUIRED_SCENARIOS","AUTHORITY_FLAGS","build_reliability_trial","validate_reliability_trial","aggregate_reliability_trials"]
