from __future__ import annotations
"""v1391 representative small-greenfield calculator website task."""
import hashlib,json,os,re,subprocess,time
from pathlib import Path
from typing import Any
CONTRACT_VERSION='v1391.8';TASK=re.compile(r'^gamma_[a-f0-9]{12,64}$')
DENIED={'selected_project_mutation_authorized':False,'eidolon_source_mutation_authorized':False,'installation_authorized':False,'promotion_authorized':False,'release_authorized':False,'independent_authority_granted':False}
def _d(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True,default=str).encode()).hexdigest()
def _files():
 html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calculator</title><link rel="stylesheet" href="styles.css"></head><body><main class="calculator" aria-label="Calculator"><output id="display" aria-live="polite">0</output><div class="keys"><button data-action="clear">C</button><button data-value="7">7</button><button data-value="8">8</button><button data-value="9">9</button><button data-op="/">÷</button><button data-value="4">4</button><button data-value="5">5</button><button data-value="6">6</button><button data-op="*">×</button><button data-value="1">1</button><button data-value="2">2</button><button data-value="3">3</button><button data-op="-">−</button><button data-value="0">0</button><button data-value=".">.</button><button data-action="equals">=</button><button data-op="+">+</button></div></main><script src="app.js"></script></body></html>'''
 css='''*{box-sizing:border-box}body{min-height:100vh;margin:0;display:grid;place-items:center;font-family:system-ui,sans-serif}.calculator{width:min(92vw,22rem);padding:1rem;border:1px solid #aaa;border-radius:1rem}#display{display:block;min-height:3rem;padding:.5rem;text-align:right;font-size:2rem;overflow-wrap:anywhere}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem}button{min-height:3rem;font:inherit;font-size:1.1rem}button:focus-visible{outline:3px solid currentColor;outline-offset:2px}@media(max-width:360px){.calculator{padding:.65rem}.keys{gap:.35rem}}'''
 js='''(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;if(root)root.CalculatorCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){function calculate(a,op,b){a=Number(a);b=Number(b);if(!Number.isFinite(a)||!Number.isFinite(b))throw new Error("Invalid number");if(op==="+")return a+b;if(op==="-")return a-b;if(op==="*")return a*b;if(op==="/"){if(b===0)throw new Error("Cannot divide by zero");return a/b}throw new Error("Unknown operation")}function format(n){return Number.isInteger(n)?String(n):String(Number(n.toFixed(10)))}if(typeof document!=="undefined"){const display=document.querySelector("#display");let left="",op="",right="";const render=()=>display.textContent=right||op||left||"0";document.querySelector(".keys").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.action==="clear"){left=op=right="";render();return}if(b.dataset.value!==undefined){let target=op?right:left;if(b.dataset.value==="."&&target.includes("."))return;target+=b.dataset.value;op?right=target:left=target;render();return}if(b.dataset.op&&left){op=b.dataset.op;right="";render();return}if(b.dataset.action==="equals"&&left&&op&&right){try{left=format(calculate(left,op,right));op=right=""}catch(_){left="Error";op=right=""}render()}});document.addEventListener("keydown",e=>{const map={Enter:"equals",Escape:"clear"};if(/[0-9.]/.test(e.key)){document.querySelector(`[data-value="${e.key}"]`)?.click()}else if(/[-+*/]/.test(e.key)){document.querySelector(`[data-op="${e.key}"]`)?.click()}else if(map[e.key])document.querySelector(`[data-action="${map[e.key]}"]`)?.click()})}return{calculate,format}});'''
 test='''const assert=require("assert");const {calculate,format}=require("./app.js");assert.strictEqual(calculate(2,"+",3),5);assert.strictEqual(calculate(9,"-",4),5);assert.strictEqual(calculate(6,"*",7),42);assert.strictEqual(calculate(8,"/",2),4);assert.strictEqual(format(1/3),"0.3333333333");assert.throws(()=>calculate(1,"/",0),/divide by zero/);console.log("calculator tests passed");'''
 readme='# Calculator Website\n\nOpen `index.html` in a browser. Keyboard digits/operators, Enter, and Escape are supported. Run `node test.js` for core arithmetic verification.\n'
 return {'index.html':html+'\n','styles.css':css+'\n','app.js':js+'\n','test.js':test+'\n','README.md':readme}
def run_small_greenfield_task(*,request:str,runtime_root:str|Path,task_id:str,node_executable:str='node',timeout_seconds:int=20)->dict[str,Any]:
 text=' '.join(str(request or '').split());root=Path(runtime_root).expanduser().resolve();active=Path(__file__).resolve().parents[1]
 if not TASK.fullmatch(str(task_id or '')) or len(text)>4000 or not re.search(r'\bcalculator\b',text,re.I) or not re.search(r'\b(?:website|web\s*page|web\s*app)\b',text,re.I):return {'ok':False,'status':'greenfield_request_unsupported','action_executed':False,**DENIED}
 try:root.relative_to(active);return {'ok':False,'status':'greenfield_runtime_must_be_external','action_executed':False,**DENIED}
 except ValueError:pass
 work=root/'gamma_tasks'/task_id
 if work.exists():return {'ok':False,'status':'greenfield_task_already_exists','action_executed':False,**DENIED}
 work.mkdir(parents=True);arts=_files()
 for rel,content in arts.items():(work/rel).write_text(content,encoding='utf-8')
 st=time.monotonic()
 try:cp=subprocess.run([node_executable,'test.js'],cwd=work,capture_output=True,timeout=timeout_seconds)
 except Exception as e:return {'ok':False,'status':'greenfield_test_execution_failed','reason_digest':_d(type(e).__name__),'action_executed':True,**DENIED}
 files=[{'path':p,'sha256':hashlib.sha256(c.encode()).hexdigest(),'bytes':len(c.encode())} for p,c in sorted(arts.items())]
 structural={'lang_declared':'<html lang="en">' in arts['index.html'],'viewport_declared':'name="viewport"' in arts['index.html'],'live_output':'aria-live="polite"' in arts['index.html'],'focus_visible':':focus-visible' in arts['styles.css'],'responsive_breakpoint':'@media' in arts['styles.css']}
 passed=cp.returncode==0 and all(structural.values());core={'contract_version':CONTRACT_VERSION,'task_id':task_id,'request_digest':_d(text),'workspace_digest':_d(str(work)),'workspace_path':str(work),'runnable_entrypoint':'index.html','file_count':len(files),'files':files,'node_test_exit_code':cp.returncode,'node_test_output_digest':hashlib.sha256((cp.stdout or b'')+(cp.stderr or b'')).hexdigest(),'test_duration_ms':int((time.monotonic()-st)*1000),'structural_checks':structural,'runnable_result_ready':passed,'conversational_request_consumed':True,'content_free_evidence':True,'action_executed':True,**DENIED};core['task_digest']=_d({k:v for k,v in core.items() if k!='workspace_path'})
 return {'ok':passed,'status':'greenfield_calculator_ready' if passed else 'greenfield_calculator_validation_failed','greenfield_task':core,'action_executed':True,**DENIED}
def process_greenfield_task_control(text:str,*,project_state=None,**_):
 if str(text or '').strip().lower() not in {'show greenfield task','inspect greenfield task','show calculator task'}:return {'active':False}
 rec=dict((project_state or {}).get('greenfield_task') or {});return {'active':True,'ok':bool(rec),'status':'greenfield_task_found' if rec else 'greenfield_task_missing','greenfield_task':rec,'action_executed':False,**DENIED}
