from __future__ import annotations
"""Strictly read-only v1132.5 Revisable World Model deliberation checkpoint."""
import hashlib, os
from pathlib import Path
from revisable_world_model_deliberation_sessions import build_revisable_world_model_deliberation_session_inspection
from revisable_world_model_arbitration import build_revisable_world_model_arbitration_inspection, OUTCOMES
CONTRACT_VERSION='v1132.5'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_revisable_world_model_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); sessions=build_revisable_world_model_deliberation_session_inspection(runtime); arbitration=build_revisable_world_model_arbitration_inspection(runtime)
 checks=[('session_contract',sessions.get('contract_version')=='v1132.3'),('arbitration_contract',arbitration.get('contract_version')=='v1132.4'),('bounded_sessions',all(1<=x.get('deliberation_budget',0)<=6 for x in sessions.get('recent_sessions',[]))),('exact_candidate_lineage',all(x.get('candidate_id') and x.get('signal_ids') for x in sessions.get('recent_sessions',[]))),('evidence_and_predecessor_lineage',all(x.get('evidence_ids') is not None and x.get('predecessor_candidate_ids') is not None for x in sessions.get('recent_sessions',[]))),('scope_preserved',all(x.get('scope_digest') is not None for x in sessions.get('recent_sessions',[]))),('acceptance_recommendation','relationship_acceptance_recommended' in OUTCOMES),('causal_review','causal_relationship_review_recommended' in OUTCOMES),('contradiction_reconciliation','contradiction_reconciliation_recommended' in OUTCOMES),('correction_acceptance','correction_acceptance_recommended' in OUTCOMES),('temporal_review','temporal_relationship_review_recommended' in OUTCOMES),('deliberate_non_acceptance','deliberate_non_acceptance' in OUTCOMES),('recovery_focus_budget_deferral',{'defer_for_recovery','defer_for_focus','defer_for_cognitive_budget'}<=OUTCOMES),('operator_prerequisite_contradiction_deferral',{'defer_for_operator_review','await_prerequisite','await_contradiction_review'}<=OUTCOMES),('unsupported_causation_suppression','suppress_unsupported_causation' in OUTCOMES),('false_certainty_suppression','suppress_false_certainty' in OUTCOMES),('content_free_outcomes',all(not x.get('world_model_revision_id') and not x.get('belief_revision_id') and not x.get('memory_revision_id') for x in arbitration.get('recent_outcomes',[]))),('privacy_boundary',not sessions.get('raw_content_exposed') and not arbitration.get('evidence_text_exposed') and not sessions.get('hidden_reasoning_exposed')),('no_provider_or_action',not sessions.get('provider_contacted') and not arbitration.get('provider_contacted') and not arbitration.get('external_action_executed')),('authority_separation',not any(sessions.get('authority_boundary',{}).values()) and not any(arbitration.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'sessions':sessions,'arbitration':arbitration,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'evidence_text_exposed':False,'belief_text_exposed':False,'memory_text_exposed':False,'goal_text_exposed':False,'identity_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'provider_contacted':False,'message_sent':False,'notification_created':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
