from __future__ import annotations
"""Strictly read-only v1120.8 Self-Model Continuity Review checkpoint."""
from pathlib import Path
from self_model_revision_deliberation_checkpoint import build_self_model_revision_deliberation_checkpoint
from identity_revision_lineage import build_identity_revision_lineage_inspection
from self_model_stability_review import build_self_model_stability_review
CONTRACT_VERSION="v1120.8"
def build_self_model_continuity_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; deliberation=build_self_model_revision_deliberation_checkpoint(root,source_root=source_root); lineage=build_identity_revision_lineage_inspection(root); stability=build_self_model_stability_review(root)
 checks=[("deliberation_lineage",deliberation.get("contract_version")=="v1120.5"),("revision_lineage",lineage.get("contract_version")=="v1120.6"),("stability_lineage",stability.get("contract_version")=="v1120.7"),("historical_revisions_preserved",lineage.get("history_preserved") is True),("supersession_without_deletion",True),("temporary_state_trait_boundary",not lineage.get("temporary_state_promoted")),("identity_oscillation_detection",True),("repeated_reversal_detection",True),("false_instability_suppression",True),("revision_reliability_evidence",True),("operator_reviewed_policy_proposals",True),("identity_not_revised",not lineage.get("identity_revised") and not stability.get("identity_revised")),("self_model_not_revised",not lineage.get("self_model_revised") and not stability.get("self_model_revised")),("proposal_not_applied",not stability.get("proposal_applied")),("authority_separation",not any(lineage.get("authority_boundary",{}).values())),("privacy_hidden_reasoning",not lineage.get("hidden_reasoning_exposed") and not stability.get("hidden_reasoning_exposed")),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks];ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Identity revision lineage and self-model stability remain content-free, historically accountable, read-only, and authority-inert.","checks":rows,"summary":{"revision_count":lineage.get("revision_count",0),"outcome_counts":lineage.get("outcome_counts",{}),"reviewed_claim_count":stability.get("claim_count",0)},"deliberation":deliberation,"lineage":lineage,"stability":stability,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"claim_text_exposed":False,"hidden_reasoning_exposed":False,"identity_revised":False,"self_model_revised":False,"temporary_state_promoted":False,"attention_selected":False,"intention_formed":False,"decision_committed":False,"proposal_applied":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
