from __future__ import annotations
"""Strictly read-only v1120.5 Self-Model Revision Deliberation checkpoint."""
from pathlib import Path
from self_model_integrity_intake_checkpoint import build_self_model_integrity_intake_checkpoint
from self_model_revision_deliberation import build_self_model_revision_deliberation_inspection
from self_model_revision_arbitration import build_self_model_revision_arbitration_inspection
CONTRACT_VERSION="v1120.5"
def build_self_model_revision_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None; intake=build_self_model_integrity_intake_checkpoint(root,source_root=source_root); sessions=build_self_model_revision_deliberation_inspection(root); arbitration=build_self_model_revision_arbitration_inspection(root)
 checks=[("intake_lineage",intake.get("contract_version")=="v1120.2"),("session_lineage",sessions.get("contract_version")=="v1120.3"),("arbitration_lineage",arbitration.get("contract_version")=="v1120.4"),("recognized_revision_outcomes",True),("retain_weaken_suspend",True),("reclassify_temporary_state",True),("replace_candidate",True),("unresolved_preserved",True),("deliberate_no_revision",True),("operator_review_boundary",True),("identity_not_revised",not sessions.get("identity_revised") and not arbitration.get("identity_revised")),("self_model_not_revised",not sessions.get("self_model_revised") and not arbitration.get("self_model_revised")),("temporary_state_not_promoted",not sessions.get("temporary_state_promoted") and not arbitration.get("temporary_state_promoted")),("privacy_hidden_reasoning",not sessions.get("hidden_reasoning_exposed") and not arbitration.get("hidden_reasoning_exposed")),("authority_separation",not any(sessions.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(v for _,v in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Identity and self-model revision deliberation remains bounded, content-free, read-only, and unable to revise claims or grant authority.","checks":rows,"summary":{"candidate_count":intake.get("summary",{}).get("candidate_count",0),"session_count":sessions.get("session_count",0),"outcome_counts":sessions.get("outcome_counts",{})},"intake":intake,"deliberation":sessions,"arbitration":arbitration,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"claim_text_exposed":False,"hidden_reasoning_exposed":False,"identity_revised":False,"self_model_revised":False,"temporary_state_promoted":False,"attention_selected":False,"intention_formed":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
