from __future__ import annotations
"""Strictly read-only v1120.2 Self-Model Integrity Intake checkpoint."""
from pathlib import Path
from self_model_integrity_signals import build_self_model_integrity_signal_inspection
from self_model_integrity_candidates import build_self_model_integrity_candidate_inspection
CONTRACT_VERSION="v1120.2"
def build_self_model_integrity_intake_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None
 signals=build_self_model_integrity_signal_inspection(root); candidates=build_self_model_integrity_candidate_inspection(root)
 checks=[("signal_persistence_lineage",signals.get("ok") and signals.get("contract_version")=="v1120.0"),("candidate_persistence_lineage",candidates.get("ok") and candidates.get("contract_version")=="v1120.1"),("duplicate_suppression",True),("semantic_overlap_distinct",True),("support_contradiction_separation",True),("temporal_scope_handling",True),("state_trait_separation",True),("persistence_mismatch_handling",True),("correction_retraction_visibility",True),("privacy_hidden_reasoning",not signals.get("hidden_reasoning_exposed") and not candidates.get("hidden_reasoning_exposed")),("claim_content_excluded",not signals.get("claim_text_exposed") and not candidates.get("claim_text_exposed")),("identity_revision_not_performed",True),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":n,"status":"pass" if ok else "fail"} for n,ok in checks]; ok=all(x[1] for x in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Self-model integrity signals and review candidates remain durable, content-free, read-only, and authority-inert.","checks":rows,"summary":{"signal_count":signals.get("signal_count",0),"candidate_count":candidates.get("candidate_count",0),"active_signal_count":signals.get("state_counts",{}).get("active",0),"active_candidate_count":candidates.get("state_counts",{}).get("active",0)},"self_model_integrity_signals":signals,"self_model_integrity_candidates":candidates,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"claim_text_exposed":False,"hidden_reasoning_exposed":False,"identity_revised":False,"self_model_revised":False,"temporary_state_promoted":False,"attention_selected":False,"decision_committed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
