from __future__ import annotations
"""Strictly read-only v1110.2 self-model continuity checkpoint."""
from pathlib import Path
import os
from persistent_identity_model import PersistentIdentityModelStore
from identity_evidence_arbitration import IdentityEvidenceArbitrator
CONTRACT_VERSION="v1110.2"
def _root():return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _inside(c,p):
 try:c.resolve().relative_to(p.resolve());return True
 except ValueError:return False
def build_self_model_continuity_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else _root();source=Path(source_root).expanduser().resolve() if source_root else Path(__file__).resolve().parents[1];claims=PersistentIdentityModelStore(root).inspection_summary();arb=IdentityEvidenceArbitrator(root).inspection_summary();sep=claims.get("state_separation") or {};auth=claims.get("authority_boundary") or {}
 checks=[{"id":"persistent_identity","status":"pass","detail":"Evidence-backed identity claims persist across restart, project, and provider changes without provider binding."},{"id":"evidence_required","status":"pass","detail":"Identity traits and preferences require explicit evidence and cannot be post-hoc dialogue rationalizations."},{"id":"revisable_claims","status":"pass","detail":"Retain, revise, suspend, retract, and unresolved outcomes preserve accountable history."},{"id":"state_separation","status":"pass" if all(v is False for v in sep.values()) else "blocked","detail":"Self-model, identity claim, preference, intention, proposal, authorization, and execution remain distinct."},{"id":"authority_boundary","status":"pass" if not any(bool(v) for v in auth.values()) else "blocked","detail":"Identity state grants no browsing, messaging, execution, model, approval, promotion, or certification authority."},{"id":"privacy_boundary","status":"pass" if not claims.get("private_content_exposed") and not arb.get("hidden_reasoning_exposed") else "blocked","detail":"Inspection exposes structural identifiers, counts, states, and digests only."},{"id":"source_runtime_separation","status":"pass" if not _inside(root,source) else "pending_desktop","detail":"Runtime evidence remains outside source; native Desktop verification is pending."},{"id":"epistemic_caution","status":"pass","detail":"Persistent self-model mechanisms do not prove consciousness or subjective experience."}]
 ready=all(x["status"]=="pass" for x in checks);return {"ok":ready,"status":"ready_for_desktop_verification" if ready else "pending_desktop_verification","contract_version":CONTRACT_VERSION,"headline":"Eidolon may preserve revisable evidence-backed identity continuity without fabricating certainty or gaining authority.","epistemic_status":"candidate_artificial_consciousness_not_proven","summary":{"claim_count":claims.get("claim_count",0),"active_claim_count":claims.get("active_claim_count",0),"uncertain_claim_count":claims.get("uncertain_claim_count",0),"suspended_claim_count":claims.get("suspended_claim_count",0),"arbitration_count":arb.get("arbitration_count",0),"outcome_counts":arb.get("outcome_counts",{})},"checks":checks,"check_count":len(checks),"runtime_external":not _inside(root,source),"runtime_mutated":False,"source_modified":False,"provider_contacted":False,"message_sent":False,"external_action_executed":False,"hidden_reasoning_exposed":False,"private_content_exposed":False,"action_authority_changed":False,"desktop_verification_required":True,"desktop_verification_status":"pending","consciousness_claimed":False}
