from __future__ import annotations
"""Strictly read-only v1139.2 supervised sandbox-change intake checkpoint."""
import hashlib, os
from pathlib import Path
from sandbox_change_eligibility import build_sandbox_change_eligibility_inspection, CHANGE_CATEGORIES, OPERATION_CATEGORIES
from sandbox_change_candidates import build_sandbox_change_candidate_inspection, STATES
CONTRACT_VERSION="v1139.2"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob("*") if x.is_file() and "__pycache__" not in x.parts and x.suffix!=".pyc"):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_sandbox_change_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); eligibility=build_sandbox_change_eligibility_inspection(runtime); candidates=build_sandbox_change_candidate_inspection(runtime)
 checks=[("eligibility_contract",eligibility.get("contract_version")=="v1139.0"),("candidate_contract",candidates.get("contract_version")=="v1139.1"),("category_coverage",len(CHANGE_CATEGORIES)>=8 and len(OPERATION_CATEGORIES)>=7),("candidate_states",len(STATES)==11),("exact_test_plan_lineage",all(x.get("arbitration_id") and x.get("test_plan_candidate_id") for x in eligibility.get("recent_records",[]))),("supported_vs_eligible",all(x.get("supported_test_plan") is not None and x.get("eligible_test_plan") is not None for x in eligibility.get("recent_records",[]))),("structural_scope_only",all(x.get("component_ids") and x.get("path_digests") and not x.get("patch_text_digest") for x in candidates.get("recent_candidates",[]))),("isolation_budget_reversibility",all(x.get("isolation_profile_id") and x.get("reversibility") is not None and x.get("containment_confidence") is not None for x in eligibility.get("recent_records",[]))),("bounded_operations",all(x.get("operation_categories") for x in eligibility.get("recent_records",[]))),("prerequisite_operator_review",all(x.get("prerequisite_ids") is not None and x.get("operator_review_required") is not None for x in eligibility.get("recent_records",[]))),("duplicate_overlap",all(x.get("semantic_overlap_key") for x in candidates.get("recent_candidates",[]))),("correction_lineage",all(x.get("contradiction_ids") is not None and x.get("retraction_ids") is not None for x in candidates.get("recent_candidates",[]))),("no_patch_or_sandbox",not eligibility.get("patch_text_exposed") and not candidates.get("patch_text_exposed")),("privacy_boundary",not eligibility.get("raw_source_exposed") and not candidates.get("private_path_exposed") and not candidates.get("hidden_reasoning_exposed")),("authority_separation",not any(eligibility.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("no_provider_or_action",not eligibility.get("provider_contacted") and not candidates.get("external_action_executed")),("read_only",rb==_sig(runtime) and sb==_sig(source)),("desktop_pending",True)]
 return {"ok":all(v for _,v in checks),"contract_version":CONTRACT_VERSION,"checks":[{"id":i,"status":"pass" if v else "fail"} for i,v in checks],"eligibility":eligibility,"candidates":candidates,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_source_exposed":False,"patch_text_exposed":False,"private_path_exposed":False,"evidence_text_exposed":False,"hidden_reasoning_exposed":False,"provider_contacted":False,"source_modified_by_checkpoint":False,"sandbox_created":False,"sandbox_change_created":False,"commands_executed":False,"tests_executed":False,"installation_performed":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification":"pending"}
