from __future__ import annotations
"""Strictly read-only v1138.2 supervised test-plan intake checkpoint."""
import hashlib, os
from pathlib import Path
from test_plan_eligibility import build_test_plan_eligibility_inspection, TEST_PLAN_CATEGORIES
from test_plan_candidates import build_test_plan_candidate_inspection, STATES
CONTRACT_VERSION='v1138.2'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_test_plan_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); eligibility=build_test_plan_eligibility_inspection(runtime); candidates=build_test_plan_candidate_inspection(runtime)
 checks=[('eligibility_contract',eligibility.get('contract_version')=='v1138.0'),('candidate_contract',candidates.get('contract_version')=='v1138.1'),('category_coverage',len(TEST_PLAN_CATEGORIES)>=9),('candidate_states',len(STATES)==11),('exact_specification_lineage',all(x.get('arbitration_id') and x.get('specification_candidate_id') for x in eligibility.get('recent_records',[]))),('supported_vs_eligible',all(x.get('supported_specification') is not None and x.get('eligible_specification') is not None for x in eligibility.get('recent_records',[]))),('coverage_without_test_text',all(x.get('component_ids') and not x.get('test_plan_text_digest') for x in candidates.get('recent_candidates',[]))),('cost_reproducibility_determinism',all(x.get('estimated_cost') is not None and x.get('reproducibility') is not None and x.get('determinism') is not None for x in eligibility.get('recent_records',[]))),('environment_dependencies',all(x.get('environment_ids') is not None and x.get('dependency_ids') is not None for x in eligibility.get('recent_records',[]))),('prerequisite_operator_review',all(x.get('prerequisite_ids') is not None and x.get('operator_review_required') is not None for x in eligibility.get('recent_records',[]))),('duplicate_overlap',all(x.get('semantic_overlap_key') for x in candidates.get('recent_candidates',[]))),('correction_lineage',all(x.get('contradiction_ids') is not None and x.get('retraction_ids') is not None for x in candidates.get('recent_candidates',[]))),('no_test_plan_or_code',not eligibility.get('test_plan_text_exposed') and not candidates.get('test_plan_text_exposed') and not candidates.get('test_code_exposed')),('privacy_boundary',not eligibility.get('raw_source_exposed') and not candidates.get('evidence_text_exposed') and not candidates.get('hidden_reasoning_exposed')),('authority_separation',not any(eligibility.get('authority_boundary',{}).values()) and not any(candidates.get('authority_boundary',{}).values())),('no_provider_or_action',not eligibility.get('provider_contacted') and not candidates.get('external_action_executed')),('read_only',rb==_sig(runtime) and sb==_sig(source)),('desktop_pending',True)]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':i,'status':'pass' if v else 'fail'} for i,v in checks],'eligibility':eligibility,'candidates':candidates,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_source_exposed':False,'test_plan_text_exposed':False,'test_code_exposed':False,'evidence_text_exposed':False,'hidden_reasoning_exposed':False,'provider_contacted':False,'source_modified_by_checkpoint':False,'test_plan_created':False,'test_code_created':False,'fixture_created':False,'sandbox_created':False,'tests_executed':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
