from __future__ import annotations
"""Strictly read-only v1140.5 supervised isolated_sandbox_execution deliberation checkpoint."""
import hashlib, json, os
from pathlib import Path
from isolated_sandbox_execution_deliberation_sessions import build_isolated_sandbox_execution_deliberation_session_inspection
from isolated_sandbox_execution_arbitration import build_isolated_sandbox_execution_arbitration_inspection, OUTCOMES
CONTRACT_VERSION='v1140.5'
def _sig(root:Path):
 if not root.exists(): return ''
 rows=[]
 for p in sorted(x for x in root.rglob('*') if x.is_file()): rows.append((str(p.relative_to(root)).replace('\\','/'),hashlib.sha256(p.read_bytes()).hexdigest()))
 return hashlib.sha256(json.dumps(rows,separators=(',',':')).encode()).hexdigest()
def build_supervised_isolated_sandbox_execution_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root or Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data')/'cognition').resolve(); source=Path(source_root or Path(__file__).resolve().parents[1]).resolve(); rb,sb=_sig(runtime),_sig(source); sessions=build_isolated_sandbox_execution_deliberation_session_inspection(runtime); arbitration=build_isolated_sandbox_execution_arbitration_inspection(runtime)
 checks=[('session_contract',sessions.get('contract_version')=='v1140.3'),('arbitration_contract',arbitration.get('contract_version')=='v1140.4'),('outcome_coverage',len(OUTCOMES)>=16),('bounded_budget',all(1<=x.get('deliberation_budget',1)<=6 for x in sessions.get('recent_sessions',[]))),('exact_candidate_lineage',all(x.get('candidate_id') and x.get('eligibility_ids') is not None for x in sessions.get('recent_sessions',[]))),('evidence_scope_containment_reversibility_isolation',all(all(k in x for k in ('evidence_support','scope_support','containment_support','reversibility_support','isolation_support')) for x in arbitration.get('recent_outcomes',[]))),('deliberate_no_isolated_sandbox_execution','deliberate_no_isolated_sandbox_execution' in OUTCOMES),('change_vs_execution_boundary',all(not x.get('sandbox_id') and not x.get('isolated_sandbox_execution_id') for x in arbitration.get('recent_outcomes',[]))),('no_patch_text',not sessions.get('patch_text_exposed') and not arbitration.get('patch_text_exposed')),('no_source_patch_or_sandbox',not any(sessions.get('authority_boundary',{}).get(k) for k in ('can_modify_source','can_write_sandbox_files','can_create_sandbox','can_run_tests'))),('no_approval_execution',not any(arbitration.get('authority_boundary',{}).get(k) for k in ('can_approve','can_authorize','can_execute','can_promote','can_certify'))),('privacy_boundary',not sessions.get('raw_source_exposed') and not arbitration.get('hidden_reasoning_exposed')),('read_only',rb==_sig(runtime) and sb==_sig(source)),('desktop_pending',True)]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'check_id':k,'ok':v} for k,v in checks],'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'patch_text_exposed':False,'source_modified_by_checkpoint':False,'external_action_executed':False,'desktop_verification':'pending','session_summary':sessions,'arbitration_summary':arbitration}
