from __future__ import annotations
"""Strictly read-only v1136.8 supervised development-proposal integration checkpoint."""
import hashlib, os
from pathlib import Path
from development_proposal_outcome_lineage import build_development_proposal_outcome_lineage_inspection, STATES
from development_proposal_reliability_review import build_development_proposal_reliability_review_inspection, FINDINGS
CONTRACT_VERSION='v1136.8'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_development_proposal_integration_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); lineage=build_development_proposal_outcome_lineage_inspection(runtime); reliability=build_development_proposal_reliability_review_inspection(runtime)
 checks=[('lineage_contract',lineage.get('contract_version')=='v1136.6'),('reliability_contract',reliability.get('contract_version')=='v1136.7'),('continuity_states',{'active','continued','superseded','stale','retracted','retired'}<=STATES),('exact_outcome_lineage',all(x.get('arbitration_id') and x.get('structural_digest') for x in lineage.get('recent_lineage',[]))),('restart_and_project_continuity',all(x.get('project_digests') is not None and x.get('scope_digests') is not None for x in lineage.get('recent_lineage',[]))),('false_positive_review','repeated_false_positive' in FINDINGS),('missed_proposal_review','possible_missed_proposal' in FINDINGS),('continuity_gap_review','continuity_gap' in FINDINGS),('scope_and_risk_drift','scope_drift' in FINDINGS and 'risk_drift' in FINDINGS),('staleness_review','stale_outcome' in FINDINGS),('operator_review_visibility','operator_review_required' in FINDINGS),('deliberate_no_change','deliberate_no_change' in FINDINGS),('no_proposal_text',all(not x.get('proposal_id') for x in reliability.get('recent_reviews',[]))),('no_specification_or_test_plan',all(not x.get('specification_id') and not x.get('test_plan_id') for x in reliability.get('recent_reviews',[]))),('no_policy_self_approval',all(not x.get('policy_proposal_id') and not x.get('approval_id') for x in reliability.get('recent_reviews',[]))),('privacy_boundary',not lineage.get('proposal_text_exposed') and not reliability.get('raw_source_exposed') and not reliability.get('hidden_reasoning_exposed')),('no_provider_or_action',not lineage.get('provider_contacted') and not reliability.get('external_action_executed')),('authority_separation',not any(lineage.get('authority_boundary',{}).values()) and not any(reliability.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'lineage':lineage,'reliability':reliability,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'raw_source_exposed':False,'failure_log_exposed':False,'evidence_text_exposed':False,'proposal_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'provider_contacted':False,'proposal_created':False,'specification_created':False,'test_plan_created':False,'sandbox_created':False,'tests_executed':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
