from __future__ import annotations
import hashlib,json
from pathlib import Path
from typing import Any
from checkpoint_registry import inspect_checkpoint_registry
from supervised_work_dispatch_execution_session_preparation import AUTHORITY_FLAGS, CONTRACT_VERSION as RETAINED_CONTRACT_VERSION, MAX_PREPARED_SESSIONS, PREPARABLE_QUEUE_STATES, REVIEW_DECISIONS, TERMINAL_REVIEW_DECISIONS, _base, _public_session, _requirements, _sealed, _validate_session
CONTRACT_VERSION="v1225.9"
def _digest(v): return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def _tree_signature(root):
 rows=[]
 for p in sorted(root.rglob("*")):
  if p.is_file() and "__pycache__" not in p.parts and p.suffix not in {".pyc",".pyo"}: rows.append((p.relative_to(root).as_posix(),hashlib.sha256(p.read_bytes()).hexdigest()))
 return _digest(rows),len(rows)
def _synthetic_session()->dict[str,Any]:
 req=_requirements(); sid="session_0123456789abcdef01234567"; sd=hashlib.sha256(b"schedule").hexdigest(); sl=hashlib.sha256(b"slot").hexdigest(); qd=hashlib.sha256(b"queue").hexdigest(); rd=_digest(req)
 dig=_digest({"session_id":sid,"generation":1,"source_schedule_digest":sd,"source_schedule_slot_digest":sl,"source_queue_digest":qd,"queue_item_id":"work_0123456789abcdef01234567","project_reference":"project_0123456789abcdef","proposal_id":"devc_0123456789abcdef01234567","requirements_digest":rd})
 row={"ok":True,"status":"prepared_development_execution_session_ready","session_id":sid,"session_digest":dig,"generation":1,"source_schedule_generation":1,"source_schedule_digest":sd,"source_schedule_review_digest":hashlib.sha256(b"review").hexdigest(),"source_schedule_slot":1,"source_schedule_slot_digest":sl,"source_prioritization_digest":hashlib.sha256(b"priority").hexdigest(),"source_queue_digest":qd,"queue_item_id":"work_0123456789abcdef01234567","project_reference":"project_0123456789abcdef","proposal_id":"devc_0123456789abcdef01234567","current_stage":"grounded-planning","safe_next_step":"review","priority_rank":1,"priority_level":"high","dependency_item_ids":[],"requirements":req,"requirements_digest":rd,"accept_phrase":f"Accept prepared development execution session {sid} digest {dig}.","reject_phrase":f"Reject prepared development execution session {sid} digest {dig}.","defer_phrase":f"Defer prepared development execution session {sid} digest {dig}.","cancel_phrase":f"Cancel prepared development execution session {sid} digest {dig}.",**_base()}
 return _sealed(row,"prepared_execution_session_record_digest")
def build_supervised_work_dispatch_execution_session_preparation_checkpoint(*,source_root=None,runtime_root=None):
 source=Path(source_root or Path(__file__).resolve().parents[1]).resolve(); runtime=Path(runtime_root) if runtime_root is not None else None; existed=runtime.exists() if runtime is not None else False; before,count=_tree_signature(source); checks=[]; check=lambda v: checks.append(bool(v))
 session=_synthetic_session(); public=_public_session(session)
 for v in [_validate_session(session),public["ok"] is True,public["status"]=="prepared_development_execution_session_ready",public["session_id"].startswith("session_"),len(public["session_digest"])==64,public["queue_item_id"].startswith("work_"),public["project_reference"].startswith("project_"),public["proposal_id"].startswith("devc_"),public["source_schedule_slot"]==1,public["priority_rank"]==1,public["priority_level"]=="high",public["dependency_item_ids"]==[],public["requirements"]==_requirements(),public["requirements_digest"]==_digest(_requirements()),public["content_free"] is True,public["prepared_session_is_planning_evidence_only"] is True,public["accepted_schedule_preserved_as_authority_source"] is True,public["fresh_launch_authorization_required"] is True,public["goal_alignment_review_required"] is True,public["uncertainty_review_required"] is True,public["outcome_reflection_required"] is True,public["operator_review_required"] is True,public["runtime_records_external"] is True]: check(v)
 for k,v in AUTHORITY_FLAGS.items(): check(public.get(k) is v)
 for k in ("provider_contacted","commands_executed","tests_executed","workspace_created","project_modified","selected_project_modified","source_modified","private_request_exposed","private_path_exposed","private_content_exposed","project_name_exposed","raw_provider_output_exposed","raw_test_output_exposed","cognition_written"): check(public.get(k) is False)
 check(all(public["requirements"].values())); check(set(REVIEW_DECISIONS)=={"accept","reject","defer","cancel"}); check(set(TERMINAL_REVIEW_DECISIONS)=={"reject","cancel"}); check(set(PREPARABLE_QUEUE_STATES)=={"active","awaiting_approval","resumable"}); check(MAX_PREPARED_SESSIONS==100); check(RETAINED_CONTRACT_VERSION=="v1225.8")
 tam=dict(session); tam["priority_level"]="critical"; check(_validate_session(tam) is False); mal=dict(session); mal["session_digest"]="0"*64; mal=_sealed(mal,"prepared_execution_session_record_digest"); check(_validate_session(mal) is False)
 module=(source/"conscious_agent"/"supervised_work_dispatch_execution_session_preparation.py").read_text(); ordinary=(source/"conscious_agent"/"ordinary_chat_development_campaign.py").read_text()
 for v in ["process_supervised_work_dispatch_control" in ordinary,"LocalModelClient" not in module,"fresh_launch_authorization_required" in module,"goal_alignment_review_required" in module,"outcome_reflection_required" in module,'execution_session_launch_authorized": False' in module,'provider_execution_authorized": False' in module,'project_mutation_authorized": False' in module]: check(v)
 reg=inspect_checkpoint_registry(source_root=source); desc=next((r for r in reg["checkpoints"] if r["checkpoint_id"]=="supervised-work-dispatch-execution-session-preparation-checkpoint"),None)
 for v in [desc is not None,(desc or {}).get("contract_version")==CONTRACT_VERSION,(desc or {}).get("read_only") is True,(desc or {}).get("post_available") is False,(desc or {}).get("required_input_count")==0]: check(v)
 after,ac=_tree_signature(source); check(before==after and count==ac); check(runtime is None or runtime.exists() is existed)
 return {"ok":all(checks),"status":"supervised_work_dispatch_execution_session_preparation_checkpoint_ready" if all(checks) else "supervised_work_dispatch_execution_session_preparation_checkpoint_failed","contract_version":CONTRACT_VERSION,"read_only":True,"runtime_data_read":False,"source_modified":False,"project_modified":False,"authority_granted":False,"provider_contacted":False,"commands_executed":False,"tests_executed":False,"execution_session_launch_authorized":False,"content_free":True,"checks":len(checks),"passed":sum(checks),"source_file_count":count,"source_signature":before,"checkpoint_digest":_digest({"contract_version":CONTRACT_VERSION,"checks":len(checks),"passed":sum(checks),"source_signature":before})}
