from __future__ import annotations
"""Strictly read-only v1140.2 supervised isolated sandbox execution intake checkpoint."""
import hashlib, os
from pathlib import Path
from isolated_sandbox_execution_eligibility import build_isolated_sandbox_execution_eligibility_inspection, EXECUTION_MODES
from isolated_sandbox_execution_candidates import build_isolated_sandbox_execution_candidate_inspection, STATES
CONTRACT_VERSION="v1140.2"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob("*") if x.is_file() and "__pycache__" not in x.parts and x.suffix!=".pyc"):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_isolated_sandbox_execution_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); eligibility=build_isolated_sandbox_execution_eligibility_inspection(runtime); candidates=build_isolated_sandbox_execution_candidate_inspection(runtime)
 checks=[("eligibility_contract",eligibility.get("contract_version")=="v1140.0"),("candidate_contract",candidates.get("contract_version")=="v1140.1"),("execution_mode_coverage",len(EXECUTION_MODES)>=6),("candidate_states",len(STATES)==11),("exact_sandbox_change_lineage",all(x.get("sandbox_change_arbitration_id") and x.get("sandbox_change_candidate_id") for x in eligibility.get("recent_records",[]))),("supported_vs_eligible",all(x.get("supported_sandbox_change") is not None and x.get("eligible_sandbox_change") is not None for x in eligibility.get("recent_records",[]))),("isolation_manifest",all(x.get("isolation_profile_id") and x.get("workspace_manifest_digest") for x in eligibility.get("recent_records",[]))),("containment_reversibility",all(x.get("containment_confidence") is not None and x.get("reversibility") is not None for x in eligibility.get("recent_records",[]))),("bounded_execution_modes",all(x.get("execution_modes") for x in eligibility.get("recent_records",[]))),("resource_command_profiles",all(x.get("resource_budget_id") is not None and x.get("command_profile_id") is not None for x in eligibility.get("recent_records",[]))),("duplicate_overlap",all(x.get("semantic_overlap_key") for x in candidates.get("recent_candidates",[]))),("correction_lineage",all(x.get("contradiction_ids") is not None and x.get("retraction_ids") is not None for x in candidates.get("recent_candidates",[]))),("no_sandbox_or_patch",not eligibility.get("sandbox_created") and not candidates.get("patch_text_exposed")),("privacy_boundary",not eligibility.get("raw_source_exposed") and not candidates.get("private_path_exposed") and not candidates.get("hidden_reasoning_exposed")),("authority_separation",not any(eligibility.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("no_provider_or_action",not eligibility.get("provider_contacted") and not candidates.get("external_action_executed")),("read_only",rb==_sig(runtime) and sb==_sig(source)),("desktop_pending",True)]
 return {"ok":all(v for _,v in checks),"contract_version":CONTRACT_VERSION,"checks":[{"id":i,"status":"pass" if v else "fail"} for i,v in checks],"eligibility":eligibility,"candidates":candidates,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_source_exposed":False,"patch_text_exposed":False,"private_path_exposed":False,"hidden_reasoning_exposed":False,"provider_contacted":False,"sandbox_created":False,"sandbox_files_written":False,"commands_executed":False,"tests_executed":False,"source_modified_by_checkpoint":False,"installation_performed":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification":"pending"}
