from __future__ import annotations
"""Strictly read-only v1135.5 supervised deficiency deliberation checkpoint."""
import hashlib, os
from pathlib import Path
from deficiency_deliberation_sessions import build_deficiency_deliberation_session_inspection
from deficiency_arbitration import build_deficiency_arbitration_inspection, OUTCOMES
CONTRACT_VERSION='v1135.5'
def _root(): return Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').expanduser().resolve()/'cognition'
def _sig(root:Path):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob('*') if x.is_file() and '__pycache__' not in x.parts and x.suffix!='.pyc'):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_deficiency_deliberation_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); sessions=build_deficiency_deliberation_session_inspection(runtime); arbitration=build_deficiency_arbitration_inspection(runtime)
 checks=[('session_contract',sessions.get('contract_version')=='v1135.3'),('arbitration_contract',arbitration.get('contract_version')=='v1135.4'),('bounded_deliberation',all(1<=x.get('deliberation_budget',0)<=6 for x in sessions.get('recent_sessions',[]))),('exact_candidate_lineage',all(x.get('candidate_id') and x.get('signal_ids') for x in sessions.get('recent_sessions',[]))),('structural_project_scope_lineage',all(x.get('project_digests') is not None and x.get('scope_digests') is not None for x in sessions.get('recent_sessions',[]))),('evidence_sufficiency','defer_for_more_evidence' in OUTCOMES),('verified_vs_probable',{'verified_deficiency','probable_deficiency'}<=OUTCOMES),('operator_and_prerequisite_deferral',{'defer_for_operator_review','await_prerequisite'}<=OUTCOMES),('recovery_and_resource_deferral',{'defer_for_recovery','defer_for_resource_budget'}<=OUTCOMES),('impact_and_feasibility_review',{'await_impact_review','await_feasibility_review'}<=OUTCOMES),('single_sample_suppression','suppress_single_sample' in OUTCOMES),('false_severity_suppression','suppress_false_severity' in OUTCOMES),('low_confidence_suppression','suppress_low_confidence' in OUTCOMES),('architectural_suspicion_separation','architectural_suspicion_only' in OUTCOMES),('contradiction_and_retraction',{'contradicted','retracted'}<=OUTCOMES),('deliberate_no_deficiency','deliberate_no_deficiency' in OUTCOMES),('no_proposal_or_patch',all(not x.get('proposal_id') and not x.get('sandbox_change_id') for x in arbitration.get('recent_outcomes',[]))),('privacy_boundary',not sessions.get('raw_content_exposed') and not arbitration.get('source_content_exposed') and not sessions.get('hidden_reasoning_exposed')),('no_provider_or_action',not sessions.get('provider_contacted') and not arbitration.get('external_action_executed')),('authority_separation',not any(sessions.get('authority_boundary',{}).values()) and not any(arbitration.get('authority_boundary',{}).values())),('read_only',rb==_sig(runtime) and sb==_sig(source))]
 return {'ok':all(v for _,v in checks),'contract_version':CONTRACT_VERSION,'checks':[{'id':k,'status':'pass' if v else 'fail'} for k,v in checks],'sessions':sessions,'arbitration':arbitration,'runtime_mutated':rb!=_sig(runtime),'source_modified':sb!=_sig(source),'raw_content_exposed':False,'source_content_exposed':False,'failure_log_exposed':False,'evidence_text_exposed':False,'proposal_text_exposed':False,'prompt_exposed':False,'provider_payload_exposed':False,'hidden_reasoning_exposed':False,'provider_contacted':False,'proposal_created':False,'sandbox_created':False,'tests_executed':False,'approval_created':False,'authorization_created':False,'external_action_executed':False,'promotion_performed':False,'certification_performed':False,'desktop_verification':'pending'}
