from __future__ import annotations
"""Strictly read-only v1135.2 supervised deficiency intake checkpoint."""
import hashlib, os
from pathlib import Path
from deficiency_signals import build_deficiency_signal_inspection, DEFICIENCY_CATEGORIES, SOURCE_CATEGORIES
from deficiency_candidates import build_deficiency_candidate_inspection, STATES
CONTRACT_VERSION="v1135.2"
def _root(): return Path(os.environ.get("EIDOLON_DATA_DIR") or Path(__file__).resolve().parents[1]/"data").expanduser().resolve()/"cognition"
def _sig(root):
 d=hashlib.sha256()
 if not root.exists(): return d.hexdigest()
 for p in sorted(x for x in root.rglob("*") if x.is_file() and "__pycache__" not in x.parts and x.suffix!=".pyc"):
  s=p.stat(); d.update(p.relative_to(root).as_posix().encode()); d.update(str(s.st_size).encode()); d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_supervised_deficiency_intake_checkpoint(runtime_root=None,*,source_root=None):
 runtime=Path(runtime_root).resolve() if runtime_root else _root(); source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1]; rb=_sig(runtime); sb=_sig(source); signals=build_deficiency_signal_inspection(runtime); candidates=build_deficiency_candidate_inspection(runtime)
 checks=[("signal_contract",signals.get("contract_version")=="v1135.0"),("candidate_contract",candidates.get("contract_version")=="v1135.1"),("category_coverage",len(DEFICIENCY_CATEGORIES)>=8),("source_coverage",{"project_perception","failed_checkpoint","operator_confirmed_problem","architectural_structure"}.issubset(SOURCE_CATEGORIES)),("candidate_states",len(STATES)==11),("exact_lineage",all(r.get("origin_ids") and r.get("evidence_ids") and r.get("component_ids") for r in signals.get("recent_signals",[]))),("severity_vs_urgency",all(r.get("severity") is not None and r.get("urgency") is not None for r in signals.get("recent_signals",[]))),("impact_vs_authority",all(r.get("observed_impact_only") is True for r in signals.get("recent_signals",[]))),("recurrence_reproducibility",all(r.get("recurrence_count") is not None and r.get("reproducibility") is not None for r in signals.get("recent_signals",[]))),("suspicion_vs_verified",all(r.get("architectural_suspicion") is not None and r.get("verified_defect") is not None for r in signals.get("recent_signals",[]))),("false_severity_suppression",all(r.get("single_sample_suppressed") is not None and r.get("unsupported_severity_suppressed") is not None for r in signals.get("recent_signals",[]))),("duplicate_overlap",all(r.get("semantic_overlap_key") for r in candidates.get("recent_candidates",[]))),("correction_lineage",all(r.get("contradiction_ids") is not None and r.get("retraction_ids") is not None for r in candidates.get("recent_candidates",[]))),("recovery_resource",all(r.get("recovery_compatible") is not None and r.get("resource_compatible") is not None for r in candidates.get("recent_candidates",[]))),("continuity_identifiers",all(r.get("project_digest") is not None and r.get("scope_digest") is not None for r in signals.get("recent_signals",[]))),("privacy_boundary",not signals.get("raw_content_exposed") and not candidates.get("proposal_text_exposed") and not signals.get("hidden_reasoning_exposed")),("no_provider_or_action",not signals.get("provider_contacted") and not candidates.get("external_action_executed")),("authority_separation",not any(signals.get("authority_boundary",{}).values()) and not any(candidates.get("authority_boundary",{}).values())),("read_only",rb==_sig(runtime) and sb==_sig(source)),("desktop_pending",True)]
 return {"ok":all(v for _,v in checks),"contract_version":CONTRACT_VERSION,"checks":[{"id":i,"status":"pass" if v else "fail"} for i,v in checks],"signals":signals,"candidates":candidates,"runtime_mutated":rb!=_sig(runtime),"source_modified":sb!=_sig(source),"raw_content_exposed":False,"source_content_exposed":False,"failure_log_exposed":False,"conversation_exposed":False,"prompt_exposed":False,"provider_payload_exposed":False,"evidence_text_exposed":False,"proposal_text_exposed":False,"private_project_record_exposed":False,"hidden_reasoning_exposed":False,"provider_contacted":False,"source_modified_by_checkpoint":False,"sandbox_created":False,"tests_executed":False,"goal_mutated":False,"plan_mutated":False,"initiative_mutated":False,"approval_created":False,"authorization_created":False,"external_action_executed":False,"promotion_performed":False,"certification_performed":False,"desktop_verification":"pending"}
