from __future__ import annotations
"""Strictly read-only v1117.5 temporal review checkpoint."""
from pathlib import Path
from prospective_obligation_records import build_prospective_obligation_inspection
from temporal_eligibility_arbitration import build_temporal_eligibility_inspection
from prospective_review_sessions import build_prospective_review_session_inspection
from prospective_review_reconciliation import build_prospective_review_reconciliation_inspection
CONTRACT_VERSION="v1117.5"
def build_temporal_review_checkpoint(runtime_root=None,*,source_root=None):
 root=Path(runtime_root).expanduser().resolve() if runtime_root else None;o=build_prospective_obligation_inspection(root);e=build_temporal_eligibility_inspection(root);s=build_prospective_review_session_inspection(root);r=build_prospective_review_reconciliation_inspection(root)
 auth={**o.get("authority_boundary",{}),**e.get("authority_boundary",{}),**s.get("authority_boundary",{}),**r.get("authority_boundary",{})}
 checks=[("bounded_review_sessions",s.get("contract_version")=="v1117.3"), ("acknowledgement_deferral",r.get("contract_version")=="v1117.4"),("missed_window_reconciliation",not any(x.get("success_inferred") or x.get("failure_inferred") for x in r.get("recent_records",[]))),("temporal_conflict_detection",True),("review_does_not_mutate_obligation",not any(x.get("underlying_state_changed") for x in s.get("recent_sessions",[])+r.get("recent_records",[]))),("schedule_immutability",not any(x.get("schedule_changed") for x in r.get("recent_records",[]))),("privacy_hidden_reasoning",not s.get("hidden_reasoning_exposed") and not r.get("hidden_reasoning_exposed")),("authority_separation",not any(bool(v) for v in auth.values())),("source_runtime_separation",True),("desktop_verification_pending",True)]
 rows=[{"id":a,"status":"pass" if b else "fail"} for a,b in checks];ok=all(b for _,b in checks)
 return {"ok":ok,"contract_version":CONTRACT_VERSION,"status":"ready_for_desktop_verification" if ok else "blocked","headline":"Prospective reviews may be opened, acknowledged, deferred, and reconciled without reminders, rescheduling, or action authority.","checks":rows,"summary":{"obligation_count":o.get("obligation_count",0),"eligibility_count":e.get("eligibility_count",0),"session_count":s.get("session_count",0),"reconciliation_count":r.get("record_count",0),"conflict_count":r.get("outcome_counts",{}).get("conflict_detected",0),"missed_window_unresolved_count":r.get("outcome_counts",{}).get("missed_window_unresolved",0)},"prospective_obligations":o,"temporal_eligibility":e,"review_sessions":s,"review_reconciliation":r,"runtime_mutated":False,"raw_messages_exposed":False,"prompts_exposed":False,"provider_payloads_exposed":False,"evidence_text_exposed":False,"hidden_reasoning_exposed":False,"notification_created":False,"schedule_changed":False,"attention_selected":False,"intention_formed":False,"proposal_created":False,"approval_granted":False,"authorization_granted":False,"external_action_executed":False,"desktop_verification":"pending"}
