from __future__ import annotations
"""Strictly read-only v1146.8 Understandable Cognitive Controls reliability checkpoint."""
import hashlib,os
from pathlib import Path
from typing import Any
from understandable_cognitive_control_activation import build_cognitive_control_activation_inspection
from understandable_cognitive_control_enforcement import build_cognitive_control_enforcement_inspection
from understandable_cognitive_control_continuity import build_cognitive_control_continuity_inspection
from understandable_cognitive_control_reliability import build_cognitive_control_reliability_inspection
from understandable_cognitive_control_definitions import AUTHORITY_BOUNDARY, CONTROL_DOMAINS
CONTRACT_VERSION="v1146.8"
def _sig(root:Path)->str:
 d=hashlib.sha256()
 if root.exists():
  for p in sorted(x for x in root.rglob('*') if x.is_file() and x.suffix not in {'.pyc','.pyo'} and '__pycache__' not in x.parts):
   s=p.stat();d.update(p.relative_to(root).as_posix().encode());d.update(str(s.st_size).encode());d.update(str(s.st_mtime_ns).encode())
 return d.hexdigest()
def build_understandable_cognitive_controls_reliability_checkpoint(runtime_root:Path|str|None=None,*,source_root:Path|str|None=None)->dict[str,Any]:
 runtime=Path(runtime_root).resolve() if runtime_root else (Path(os.environ.get('EIDOLON_DATA_DIR') or Path(__file__).resolve().parents[1]/'data').resolve()/'cognition');source=Path(source_root).resolve() if source_root else Path(__file__).resolve().parents[1];rb,sb=_sig(runtime),_sig(source)
 a=build_cognitive_control_activation_inspection(runtime);e=build_cognitive_control_enforcement_inspection(runtime);c=build_cognitive_control_continuity_inspection(runtime);r=build_cognitive_control_reliability_inspection(runtime);rows=(c.get('recent_records') or [])+(r.get('recent_reviews') or [])
 checks=[('continuity_contract',c.get('contract_version')=='v1146.6'),('reliability_contract',r.get('contract_version')=='v1146.7'),('execution_lineage',a.get('contract_version')=='v1146.3' and e.get('contract_version')=='v1146.4'),('bounded_domains',all(set(x.get('active_domains') or []).issubset(CONTROL_DOMAINS) for x in c.get('recent_records') or [])),('stale_detection',all('stale_domains' in x for x in c.get('recent_records') or [])),('conflict_detection',all('conflicting_domains' in x for x in c.get('recent_records') or [])),('drift_detection',all('drifted_domains' in x for x in c.get('recent_records') or [])),('safe_default_recovery',all(x.get('safe_default_recovery_available') for x in c.get('recent_records') or [])),('operator_correction_lineage',all('operator_correction_id' in x for x in c.get('recent_records') or [])),('visible_behavior_bounded',all(x.get('visible_state') in {'steady','changed','attention'} for x in c.get('recent_records') or [])),('reliability_bounded',all(0<=x.get('reliability_score',0)<=1 and 0<=x.get('uncertainty',0)<=1 for x in r.get('recent_reviews') or [])),('review_state_bounded',all(x.get('state') in {'reliable','review_required'} for x in r.get('recent_reviews') or [])),('content_free',c.get('content_free') and r.get('content_free')),('privacy_boundary',not any(any(k in x for k in ('text','content','prompt','message','reasoning','memory','relationship','provider_payload','source_code')) for x in rows)),('no_execution',all(not x.get('execution_performed') for x in rows)),('no_cognition_mutation',all(not x.get('cognition_mutated') for x in rows)),('no_provider_contact',all(not x.get('provider_contacted') for x in rows)),('no_message_send',all(not x.get('message_sent') for x in rows)),('no_proposal_creation',all(not x.get('proposal_created') for x in rows)),('authority_separation',all(v is False for v in AUTHORITY_BOUNDARY.values())),('checkpoint_read_only',True),('post_checkpoint_unavailable',True),('source_runtime_separation',str(runtime)!=str(source) and source not in runtime.parents),('desktop_verification_pending',True)]
 ra,sa=_sig(runtime),_sig(source);checks += [('runtime_read_only',rb==ra),('source_read_only',sb==sa)];passed=sum(bool(v) for _,v in checks)
 return {'contract_version':CONTRACT_VERSION,'ok':passed==len(checks),'passed':passed,'total':len(checks),'checks':[{'name':n,'passed':bool(v)} for n,v in checks],'summary':{'active_control_count':a.get('active_control_count',0),'enforcement_receipt_count':e.get('receipt_count',0),'continuity_record_count':c.get('record_count',0),'reliability_review_count':r.get('review_count',0),'stale_count':c.get('stale_count',0),'conflict_count':c.get('conflict_count',0),'drift_count':c.get('drift_count',0),'review_required_count':r.get('review_required_count',0)},'continuity_inspection':c,'reliability_inspection':r,'read_only':True,'post_available':False,'desktop_verification':'pending','authority_boundary':AUTHORITY_BOUNDARY}
